(()=>{'use strict';const c=document.getElementById('game'),x=c.getContext('2d'),W=480,H=640,$=id=>document.getElementById(id);let state='title',score=0,high=+localStorage.getItem('breakout-high')||0,level=1,lives=3,bar,ball,bricks=[],keys=new Set(),last=0,dragging=false;const colors=['#ef8b70','#f3b95f','#f6d66b','#9fd8a4','#84c5df','#a99add'];
function reset(){score=0;level=1;lives=3;bar={x:W/2-48,y:H-42,w:96,h:11,v:390};ball={x:W/2,y:H-57,vx:190,vy:-250,r:6,stuck:true};makeBricks();hud();draw()}
function makeBricks(){bricks=[];for(let row=0;row<6+Math.min(level,4);row++)for(let col=0;col<9;col++)bricks.push({x:28+col*47,y:52+row*27,w:41,h:20,color:colors[row%colors.length],alive:true,row,col})}
function hud(){$('score').textContent=String(score).padStart(6,'0');$('high').textContent=String(high).padStart(6,'0');$('level').textContent=String(level).padStart(2,'0');$('lives').textContent='♥'.repeat(lives)+'·'.repeat(3-lives)}
function msg(t,h,b){$('title').textContent=t;$('hint').textContent=h;$('start').textContent=b;$('overlay').classList.remove('hide')}
function start(){reset();state='play';$('overlay').classList.add('hide')}
function pause(){if(state==='play'){state='pause';msg('RESTING GARDEN','THE FIREFLY IS WAITING','RESUME')}else if(state==='pause'){state='play';$('overlay').classList.add('hide')}}
function launch(){if(ball.stuck){ball.stuck=false;ball.vx=(Math.random()>.5?1:-1)*190;ball.vy=-250}}
function startAndLaunch(){if(state==='pause')pause();if(state!=='play')start();launch()}
function lose(){lives--;hud();if(lives<=0){state='over';if(score>high){high=score;localStorage.setItem('breakout-high',high)}hud();msg('THE GARDEN IS QUIET','FINAL GLOW '+String(score).padStart(6,'0'),'PLAY AGAIN')}else{ball={x:W/2,y:H-57,vx:190,vy:-250,r:6,stuck:true}}}
function moveBar(e){const r=c.getBoundingClientRect();bar.x=Math.max(8,Math.min(W-bar.w-8,(e.clientX-r.left)/r.width*W-bar.w/2))}
function update(dt){let d=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0);bar.x=Math.max(8,Math.min(W-bar.w-8,bar.x+d*bar.v*dt));if(ball.stuck){ball.x=bar.x+bar.w/2;return}ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;if(ball.x-ball.r<=0&&ball.vx<0){ball.x=ball.r;ball.vx=Math.abs(ball.vx)}else if(ball.x+ball.r>=W&&ball.vx>0){ball.x=W-ball.r;ball.vx=-Math.abs(ball.vx)}if(ball.y-ball.r<=0&&ball.vy<0){ball.y=ball.r;ball.vy=Math.abs(ball.vy)}if(ball.y>H+20){lose();return}if(ball.y+ball.r>=bar.y&&ball.y-ball.r<=bar.y+bar.h&&ball.x>=bar.x&&ball.x<=bar.x+bar.w&&ball.vy>0){let hit=(ball.x-(bar.x+bar.w/2))/(bar.w/2);ball.vx=hit*300;ball.vy=-Math.abs(ball.vy)}for(const b of bricks)if(b.alive&&ball.x+ball.r>b.x&&ball.x-ball.r<b.x+b.w&&ball.y+ball.r>b.y&&ball.y-ball.r<b.y+b.h){b.alive=false;score+=10*level;if(score>high)high=score;hud();ball.vy*=-1;break}if(bricks.every(b=>!b.alive)){level++;makeBricks();ball={x:W/2,y:H-57,vx:190,vy:-250,r:6,stuck:true};hud()}}
function flower(b){x.save();x.translate(b.x+b.w/2,b.y+b.h/2);x.fillStyle=b.color;for(let i=0;i<4;i++){x.rotate(Math.PI/2);x.beginPath();x.ellipse(0,-7,7,10,0,0,Math.PI*2);x.fill()}x.fillStyle='#fff1a8';x.beginPath();x.arc(0,0,5,0,Math.PI*2);x.fill();x.restore()}
function draw(){const light=document.documentElement?.dataset?.theme==='light';x.fillStyle=light?'#fff7df':'#10213a';x.fillRect(0,0,W,H);x.fillStyle=light?'rgba(20,38,61,.12)':'rgba(255,244,207,.13)';for(let i=0;i<26;i++){x.beginPath();x.arc((i*83)%W,36+(i*47)%H,1.5+(i%3),0,Math.PI*2);x.fill()}x.fillStyle=light?'#f3d98a':'#263f58';x.beginPath();x.arc(405,70,32,0,Math.PI*2);x.fill();x.fillStyle=light?'#fff7df':'#10213a';x.beginPath();x.arc(419,61,29,0,Math.PI*2);x.fill();bricks.forEach(b=>{if(b.alive)flower(b)});x.strokeStyle=light?'#568c5c':'#6aa16f';x.lineWidth=3;x.beginPath();x.moveTo(0,H-20);x.quadraticCurveTo(90,H-52,190,H-25);x.quadraticCurveTo(310,H+4,480,H-28);x.stroke();x.fillStyle=light?'#6aa16f':'#9fd8a4';x.beginPath();x.ellipse(bar.x+bar.w/2,bar.y+bar.h/2,bar.w/2,bar.h/2,0,0,Math.PI*2);x.fill();x.strokeStyle=light?'#29333c':'#10213a';x.lineWidth=2;x.stroke();if(ball){x.save();x.shadowColor=light?'#f3b95f':'#ffe27a';x.shadowBlur=18;x.fillStyle='#ffe27a';x.beginPath();x.arc(ball.x,ball.y,ball.r,0,Math.PI*2);x.fill();x.restore()}}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;if(state==='play')update(dt);draw();requestAnimationFrame(loop)}
$('start').onclick=startAndLaunch;$('new').onclick=startAndLaunch;$('pause').onclick=pause;$('mobileLaunch').onclick=startAndLaunch;window.onkeydown=e=>{keys.add(e.key);if(e.key===' '){e.preventDefault();startAndLaunch()}if(e.key==='p'||e.key==='P')pause()};window.onkeyup=e=>keys.delete(e.key);c.addEventListener('pointerdown',e=>{e.preventDefault();if(state!=='play')start();dragging=true;c.setPointerCapture?.(e.pointerId);moveBar(e);launch()});c.addEventListener('pointermove',e=>{if(dragging){e.preventDefault();moveBar(e)}});c.addEventListener('pointerup',e=>{e.preventDefault();dragging=false;c.releasePointerCapture?.(e.pointerId)});c.addEventListener('pointercancel',()=>{dragging=false});reset();msg('FIRELIGHT GARDEN','TAP START TO RELEASE THE FIREFLY','START');requestAnimationFrame(loop)})();
