(() => {
  'use strict';
  const canvas=document.getElementById('game');const ctx=canvas.getContext('2d');const W=canvas.width,H=canvas.height,CX=W/2;const R=window.ColorRules;const STORAGE_KEY='paint-parade-best-v1';
  const COLORS=['#e66c68','#75bc88','#64b4d0','#f2c75d'];const $=id=>document.getElementById(id);const ui={scoreStat:$('scoreStat'),bestStat:$('bestStat'),overlay:$('overlay'),title:$('overlayTitle'),text:$('overlayText'),start:$('startButton'),pause:$('pauseButton')};
  let state='title',score=0,best=Number(localStorage.getItem(STORAGE_KEY)||0),ball=null,cameraY=0,obstacles=[],pickups=[],particles=[],lastTime=0,nextObstacleY=0;
  function randomColorExcept(current){const choices=[0,1,2,3].filter(c=>c!==current);return choices[Math.floor(Math.random()*choices.length)]}
  function spawnObstacle(y){obstacles.push({type:'circle',y,radius:75,thickness:17,angle:Math.random()*Math.PI*2,speed:(.7+Math.random()*.5)*(Math.random()<.5?1:-1),colors:[0,1,2,3]});pickups.push({type:'star',x:CX,y,radius:12,collected:false});pickups.push({type:'switcher',x:CX,y:y-150,radius:14,collected:false})}
  function resetGame(){score=0;cameraY=0;ball={x:CX,y:480,vy:0,r:9,color:Math.floor(Math.random()*4)};obstacles=[];pickups=[];particles=[];nextObstacleY=240;for(let i=0;i<4;i++){spawnObstacle(nextObstacleY);nextObstacleY-=300}updateHud()}
  function updateHud(){$('scoreStat').textContent=String(score);$('bestStat').textContent=String(best)}
  function jump(){if(state==='title'||state==='over'){resetGame();state='playing';ui.overlay.classList.add('hide');ui.pause.textContent='PAUSE';ball=R.applyJump(ball,-430);lastTime=performance.now();return}if(state!=='playing'||!ball)return;ball=R.applyJump(ball,-430);if(navigator.vibrate)navigator.vibrate(10)}
  function togglePause(){if(state==='playing'){state='paused';ui.title.textContent='PAUSED';ui.text.textContent=`CURRENT SPLASHES: ${score}`;ui.start.textContent='RESUME';ui.overlay.classList.remove('hide');ui.pause.textContent='RESUME'}else if(state==='paused'){state='playing';ui.overlay.classList.add('hide');ui.pause.textContent='PAUSE';lastTime=performance.now()}}
  function triggerExplosion(x,y,color){for(let i=0;i<30;i++){const ang=Math.random()*Math.PI*2,spd=60+Math.random()*220;particles.push({x,y,vx:Math.cos(ang)*spd,vy:Math.sin(ang)*spd,life:.8+Math.random()*.4,color:COLORS[color]})}}
  function gameOver(){state='over';if(score>best){best=score;localStorage.setItem(STORAGE_KEY,String(best))}updateHud();if(ball)triggerExplosion(ball.x,ball.y,ball.color);ball=null;setTimeout(()=>{ui.title.textContent='PAINT SPLASH';ui.text.textContent=`SPLASHES ${score} · BEST ${best}`;ui.start.textContent='PLAY AGAIN';ui.overlay.classList.remove('hide')},400);if(navigator.vibrate)navigator.vibrate([60,40,80])}
  function update(dt){if(ball){ball=R.updatePhysics(ball,dt,1200);if(ball.y<cameraY+320)cameraY=ball.y-320;if(ball.y>cameraY+H+40){gameOver();return}for(const obs of obstacles){if(R.checkObstacleCollision(ball,CX,obs)==='hit'){gameOver();return}}for(const p of pickups){if(p.collected)continue;if(Math.hypot(ball.x-p.x,ball.y-p.y)<=ball.r+p.radius){p.collected=true;if(p.type==='star'){score++;if(score>best)best=score;updateHud();if(navigator.vibrate)navigator.vibrate(25)}else{ball.color=randomColorExcept(ball.color);if(navigator.vibrate)navigator.vibrate(35)}}}}for(const obs of obstacles)obs.angle+=obs.speed*dt;if(nextObstacleY>cameraY-400){spawnObstacle(nextObstacleY);nextObstacleY-=300}obstacles=obstacles.filter(o=>o.y<cameraY+H+200);pickups=pickups.filter(p=>p.y<cameraY+H+200);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}particles=particles.filter(p=>p.life>0)}
  function drawBackground(light){ctx.fillStyle=light?'#fff1cc':'#193844';ctx.fillRect(0,0,W,H);ctx.fillStyle=light?'rgba(230,108,104,.12)':'rgba(242,199,93,.13)';for(let i=0;i<18;i++){ctx.beginPath();ctx.arc((i*67)%W,40+(i*83)%H,2+(i%3),0,Math.PI*2);ctx.fill()}ctx.strokeStyle=light?'#d7a96b':'#557d77';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,48);ctx.quadraticCurveTo(110,85,220,42);ctx.quadraticCurveTo(330,6,400,62);ctx.stroke();for(let i=0;i<7;i++){ctx.fillStyle=COLORS[i%4];ctx.beginPath();ctx.arc(30+i*58,62+(i%2)*10,5,0,Math.PI*2);ctx.fill()}}
  function drawHoop(obs){const seg=(Math.PI*2)/4;for(let i=0;i<4;i++){const a=obs.angle+i*seg;ctx.save();ctx.strokeStyle=COLORS[obs.colors[i]];ctx.lineWidth=obs.thickness;ctx.lineCap='round';ctx.beginPath();ctx.arc(CX,obs.y,obs.radius,a+.06,a+seg-.06);ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.35)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(CX,obs.y,obs.radius-7,a+.1,a+.33);ctx.stroke();ctx.restore()}}
  function drawChameleon(){if(!ball)return;ctx.save();ctx.translate(ball.x,ball.y);ctx.fillStyle=COLORS[ball.color];ctx.beginPath();ctx.ellipse(0,0,16,12,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#3c3a38';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle=COLORS[(ball.color+1)%4];ctx.beginPath();ctx.arc(13,-3,9,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fffdf7';ctx.beginPath();ctx.arc(16,-6,4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#3c3a38';ctx.beginPath();ctx.arc(17,-6,1.7,0,Math.PI*2);ctx.fill();ctx.strokeStyle=COLORS[ball.color];ctx.lineWidth=4;ctx.beginPath();ctx.arc(-13,8,12,0,Math.PI*1.3);ctx.stroke();ctx.restore()}
  function draw(){const light=document.documentElement?.dataset?.theme==='light';ctx.clearRect(0,0,W,H);ctx.save();ctx.translate(0,-cameraY);drawBackground(light);for(const obs of obstacles){if(obs.y<cameraY-10)continue;drawHoop(obs)};for(const p of pickups){if(p.collected)continue;ctx.save();ctx.translate(p.x,p.y);if(p.type==='star'){ctx.fillStyle='#f2c75d';ctx.rotate(Math.PI/4);ctx.fillRect(-7,-7,14,14);ctx.fillStyle='#fff7e8';ctx.fillRect(-3,-3,6,6)}else{for(let i=0;i<4;i++){ctx.fillStyle=COLORS[i];ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,p.radius,i*Math.PI/2+.1,(i+1)*Math.PI/2-.1);ctx.fill()}}ctx.restore()}for(const p of particles){ctx.save();ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,4,0,Math.PI*2);ctx.fill();ctx.restore()}drawChameleon();ctx.restore()}
  function loop(time){const dt=Math.min(.04,(time-lastTime)/1000||0);lastTime=time;if(state==='playing')update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
  canvas.addEventListener('pointerdown',e=>{e.preventDefault();jump()});window.addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='ArrowUp'||e.code==='KeyW'){e.preventDefault();jump()}else if(e.code==='KeyP'||e.code==='Escape'){e.preventDefault();togglePause()}});ui.start.addEventListener('click',jump);ui.pause.addEventListener('click',togglePause);resetGame();updateHud();window.ColorGame={jump,getSnapshot:()=>({state,score,best,hasBall:Boolean(ball)})};
})();
