(() => {
'use strict';
const R=window.BubbleShooterRules,canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),$=id=>document.getElementById(id);
const COLS=8,ROWS=13,RADIUS=27,DX=56,DY=48,TOP=29,COLORS=['cyan','orange','pink','green'];
let grid,current,next,score,best=Number(localStorage.getItem('bubble-shooter-best')||0),misses,active,aim={x:240,y:300},shot=null,pointerId=null;
function css(name,fallback){return typeof getComputedStyle==='function'?(getComputedStyle(document.documentElement).getPropertyValue(name).trim()||fallback):fallback}
function palette(){return{cyan:css('--cyan','#64e6e0'),orange:css('--orange','#ffb45c'),pink:css('--pink','#ff668f'),green:css('--green','#83d483'),board:css('--board','#0d151f'),line:css('--line','#243241'),ink:css('--ink','#e8f0f7')}}
function randomColor(){const used=new Set();for(const row of grid||[])for(const cell of row)if(cell)used.add(cell);const options=used.size?[...used]:COLORS;return options[Math.floor(Math.random()*options.length)]}
function center(row,col){return{x:RADIUS+col*DX+(row%2?DX/2:0),y:TOP+row*DY}}
function nearestCell(x,y){let bestCell=null,bestDist=Infinity;for(let r=0;r<grid.length;r++)for(let c=0;c<COLS;c++){const p=center(r,c),d=Math.hypot(x-p.x,y-p.y);if(d<bestDist){bestDist=d;bestCell={row:r,col:c}}}return bestCell}
function initialize(){grid=R.emptyGrid(ROWS,COLS);for(let r=0;r<5;r++)for(let c=0;c<COLS;c++)if(!(r===4&&Math.random()<.35))grid[r][c]=COLORS[Math.floor(Math.random()*COLORS.length)];current=randomColor();next=randomColor();score=0;misses=5;active=true;shot=null;$('resultOverlay').classList.remove('show');updateHud();draw()}
function updateHud(){$('score').textContent=String(score).padStart(6,'0');$('best').textContent=String(best).padStart(6,'0');$('misses').textContent=String(misses).padStart(2,'0');$('nextBubble').style.background=palette()[next]}
function drawBubble(x,y,color,alpha=1){const p=palette();ctx.globalAlpha=alpha;ctx.fillStyle=p[color];ctx.beginPath();ctx.arc(x,y,RADIUS-2,0,Math.PI*2);ctx.fill();ctx.strokeStyle=p.line;ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#fff8';ctx.beginPath();ctx.arc(x-8,y-9,5,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}
function draw(){const p=palette();ctx.fillStyle=p.board;ctx.fillRect(0,0,canvas.width,canvas.height);for(let r=0;r<grid.length;r++)for(let c=0;c<COLS;c++)if(grid[r][c]){const pos=center(r,c);drawBubble(pos.x,pos.y,grid[r][c])}if(active&&!shot){traceAim();drawBubble(240,675,current);ctx.fillStyle=p.muted||p.ink;ctx.fillRect(237,704,6,10)}if(shot)drawBubble(shot.x,shot.y,shot.color)}
function normalizedAim(){let dx=aim.x-240,dy=aim.y-675;if(dy>-80)dy=-80;const length=Math.hypot(dx,dy)||1;return{x:dx/length,y:dy/length}}
function traceAim(){const p=palette(),v=normalizedAim();let x=240,y=675,vx=v.x,vy=v.y;ctx.strokeStyle=p.ink;ctx.globalAlpha=.28;ctx.lineWidth=2;ctx.setLineDash([4,8]);ctx.beginPath();ctx.moveTo(x,y);for(let i=0;i<90;i++){x+=vx*7;y+=vy*7;if(x<RADIUS){x=RADIUS;vx=Math.abs(vx)}if(x>canvas.width-RADIUS){x=canvas.width-RADIUS;vx=-Math.abs(vx)}ctx.lineTo(x,y);if(y<TOP||collisionAt(x,y))break}ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1}
function collisionAt(x,y){for(let r=0;r<grid.length;r++)for(let c=0;c<COLS;c++)if(grid[r][c]){const p=center(r,c);if(Math.hypot(x-p.x,y-p.y)<RADIUS*1.85)return true}return false}
function shoot(){if(!active||shot)return;const v=normalizedAim();shot={x:240,y:675,vx:v.x*9,vy:v.y*9,color:current};requestAnimationFrame(animate)}
function animate(){if(!shot)return;for(let step=0;step<2;step++){shot.x+=shot.vx;shot.y+=shot.vy;if(shot.x<RADIUS){shot.x=RADIUS;shot.vx=Math.abs(shot.vx)}if(shot.x>canvas.width-RADIUS){shot.x=canvas.width-RADIUS;shot.vx=-Math.abs(shot.vx)}if(shot.y<=TOP||collisionAt(shot.x,shot.y)){attachShot();return}}draw();requestAnimationFrame(animate)}
function attachShot(){const cell=nearestCell(shot.x,shot.y);if(!cell){shot=null;return}let {row,col}=cell;if(grid[row][col]){const open=R.neighbors(row,col).filter(([r,c])=>R.inside(grid,r,c)&&!grid[r][c]).sort((a,b)=>{const pa=center(...a),pb=center(...b);return Math.hypot(shot.x-pa.x,shot.y-pa.y)-Math.hypot(shot.x-pb.x,shot.y-pb.y)});if(!open.length){end(false);return}[row,col]=open[0]}grid[row][col]=shot.color;shot=null;const result=R.resolve(grid,row,col);if(result.matched){score+=result.matched*10+result.dropped*20;misses=5}else{misses--;if(misses<=0)addPressureRow()}if(score>best){best=score;localStorage.setItem('bubble-shooter-best',best)}if(R.occupied(grid)===0){end(true);return}if(grid.some((line,r)=>r>=11&&line.some(Boolean))){end(false);return}current=next;next=randomColor();updateHud();draw()}
function addPressureRow(){const row=Array.from({length:COLS},()=>COLORS[Math.floor(Math.random()*COLORS.length)]);R.addRow(grid,row);if(grid.length>ROWS)grid.pop();misses=5}
function end(won){active=false;shot=null;$('resultTitle').textContent=won?'FIELD CLEAR':'GAME OVER';$('resultText').textContent=won?'NO BUBBLES REMAIN':'THE BUBBLES REACHED THE LINE';$('resultOverlay').classList.add('show');updateHud();draw()}
function point(event){const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*canvas.width/rect.width,y:(event.clientY-rect.top)*canvas.height/rect.height}}
canvas.addEventListener('pointerdown',event=>{event.preventDefault();if(!active)return;pointerId=event.pointerId;canvas.setPointerCapture?.(pointerId);aim=point(event);draw()});canvas.addEventListener('pointermove',event=>{if(pointerId!==event.pointerId||!active)return;event.preventDefault();aim=point(event);draw()});canvas.addEventListener('pointerup',event=>{if(pointerId!==event.pointerId)return;event.preventDefault();aim=point(event);pointerId=null;shoot()});canvas.addEventListener('pointercancel',()=>pointerId=null);$('newButton').addEventListener('click',initialize);$('resultButton').addEventListener('click',initialize);document.addEventListener('themechange',draw);
initialize();
})();
