(() => {
'use strict';
const R=window.BubbleShooterRules,canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),$=id=>document.getElementById(id);const COLS=8,ROWS=13,RADIUS=27,DX=56,DY=48,TOP=30,COLORS=['mint','coral','yellow','blue'];let grid,current,next,score,best=Number(localStorage.getItem('bubble-shooter-best')||0),misses,active,aim={x:240,y:300},shot=null,pointerId=null,clock=0;
function css(name,fallback){const value=getComputedStyle(document.documentElement).getPropertyValue(name).trim();return value||fallback}function palette(){return{mint:css('--mint','#9eddbd'),coral:css('--coral','#f28c78'),yellow:css('--yellow','#f7d66c'),blue:css('--blue','#8fc9eb'),paper:css('--paper','#fffaf0'),board:css('--board','#fffdf7'),grid:css('--grid','#c7e4dd'),line:css('--line','#d9cfc1'),ink:css('--ink','#3d3832'),muted:css('--muted','#8a7c6e'),purple:css('--purple','#b8a7e8')}}
function randomColor(){const used=new Set();for(const row of grid||[])for(const cell of row)if(cell)used.add(cell);const options=used.size?[...used]:COLORS;return options[Math.floor(Math.random()*options.length)]}function center(row,col){return{x:RADIUS+col*DX+(row%2?DX/2:0),y:TOP+row*DY}}function nearestCell(x,y){let bestCell=null,bestDist=Infinity;for(let r=0;r<grid.length;r++)for(let c=0;c<COLS;c++){const pos=center(r,c),dist=Math.hypot(x-pos.x,y-pos.y);if(dist<bestDist){bestDist=dist;bestCell={row:r,col:c}}}return bestCell}
function initialize(){grid=R.emptyGrid(ROWS,COLS);for(let r=0;r<5;r++)for(let c=0;c<COLS;c++)if(!(r===4&&Math.random()<.35))grid[r][c]=COLORS[Math.floor(Math.random()*COLORS.length)];current=randomColor();next=randomColor();score=0;misses=5;active=true;shot=null;aim={x:240,y:300};$('resultOverlay').classList.remove('show');updateHud();draw()}
function updateHud(){$('score').textContent=String(score).padStart(6,'0');$('best').textContent=String(best).padStart(6,'0');$('misses').textContent=String(misses).padStart(2,'0');$('nextBubble').style.background=palette()[next]}
function drawFlower(x,y,color,alpha=1){const p=palette(),fill=p[color]||p.mint;ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.fillStyle=fill;ctx.strokeStyle=p.ink;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,RADIUS-2,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.globalAlpha=alpha*.75;ctx.fillStyle=p.paper;for(let i=0;i<5;i++){const a=i*Math.PI*2/5;ctx.beginPath();ctx.ellipse(Math.cos(a)*10,Math.sin(a)*10,5,8,a,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=alpha;ctx.fillStyle=p.yellow;ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=p.paper;ctx.globalAlpha=alpha*.6;ctx.beginPath();ctx.arc(-8,-10,5,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawGarden(p){ctx.fillStyle=p.board;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle=p.grid;ctx.globalAlpha=.52;ctx.lineWidth=1;for(let x=0;x<=canvas.width;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke()}for(let y=0;y<=canvas.height;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}ctx.globalAlpha=1;ctx.strokeStyle=p.coral;ctx.lineWidth=2;ctx.lineCap='round';for(let i=0;i<7;i++){const x=22+i*70,y=12+(i%3)*15;ctx.beginPath();ctx.moveTo(x,y+7);ctx.lineTo(x+6,y);ctx.lineTo(x+12,y+7);ctx.stroke()}ctx.fillStyle=p.mint;ctx.beginPath();ctx.moveTo(0,704);ctx.quadraticCurveTo(95,680,190,704);ctx.quadraticCurveTo(300,730,480,696);ctx.lineTo(480,720);ctx.lineTo(0,720);ctx.closePath();ctx.fill();ctx.strokeStyle=p.ink;ctx.globalAlpha=.35;ctx.beginPath();ctx.moveTo(0,704);ctx.quadraticCurveTo(95,680,190,704);ctx.quadraticCurveTo(300,730,480,696);ctx.stroke();ctx.globalAlpha=1}
function normalizedAim(){let dx=aim.x-240,dy=aim.y-675;if(dy>-80)dy=-80;const length=Math.hypot(dx,dy)||1;return{x:dx/length,y:dy/length}}
function traceAim(){const p=palette(),v=normalizedAim();let x=240,y=675,vx=v.x,vy=v.y;ctx.save();ctx.strokeStyle=p.ink;ctx.globalAlpha=.3;ctx.lineWidth=2;ctx.setLineDash([4,8]);ctx.beginPath();ctx.moveTo(x,y);for(let i=0;i<90;i++){x+=vx*7;y+=vy*7;if(x<RADIUS){x=RADIUS;vx=Math.abs(vx)}if(x>canvas.width-RADIUS){x=canvas.width-RADIUS;vx=-Math.abs(vx)}ctx.lineTo(x,y);if(y<TOP||collisionAt(x,y))break}ctx.stroke();ctx.restore();ctx.setLineDash([])}
function collisionAt(x,y){for(let r=0;r<grid.length;r++)for(let c=0;c<COLS;c++)if(grid[r][c]){const pos=center(r,c);if(Math.hypot(x-pos.x,y-pos.y)<RADIUS*1.85)return true}return false}
function drawShooter(p){ctx.save();ctx.translate(240,687);ctx.fillStyle=p.mint;ctx.strokeStyle=p.ink;ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(-42,31);ctx.quadraticCurveTo(-35,0,0,-5);ctx.quadraticCurveTo(35,0,42,31);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle=p.yellow;ctx.beginPath();ctx.arc(-15,14,4,0,Math.PI*2);ctx.arc(15,14,4,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=p.coral;ctx.beginPath();ctx.arc(0,13,7,0,Math.PI);ctx.stroke();ctx.restore()}
function shoot(){if(!active||shot)return;const v=normalizedAim();shot={x:240,y:675,vx:v.x*9,vy:v.y*9,color:current};requestAnimationFrame(animate)}function animate(){if(!shot)return;for(let step=0;step<2;step++){shot.x+=shot.vx;shot.y+=shot.vy;if(shot.x<RADIUS){shot.x=RADIUS;shot.vx=Math.abs(shot.vx)}if(shot.x>canvas.width-RADIUS){shot.x=canvas.width-RADIUS;shot.vx=-Math.abs(shot.vx)}if(shot.y<=TOP||collisionAt(shot.x,shot.y)){attachShot();return}}draw();requestAnimationFrame(animate)}
function attachShot(){const cell=nearestCell(shot.x,shot.y);if(!cell){shot=null;return}let{row,col}=cell;if(grid[row][col]){const open=R.neighbors(row,col).filter(([r,c])=>R.inside(grid,r,c)&&!grid[r][c]).sort((a,b)=>{const pa=center(...a),pb=center(...b);return Math.hypot(shot.x-pa.x,shot.y-pa.y)-Math.hypot(shot.x-pb.x,shot.y-pb.y)});if(!open.length){end(false);return}[row,col]=open[0]}grid[row][col]=shot.color;shot=null;const result=R.resolve(grid,row,col);if(result.matched){score+=result.matched*10+result.dropped*20;misses=5}else{misses--;if(misses<=0)addPressureRow()}if(score>best){best=score;localStorage.setItem('bubble-shooter-best',String(best))}if(R.occupied(grid)===0){end(true);return}if(grid.some((line,r)=>r>=11&&line.some(Boolean))){end(false);return}current=next;next=randomColor();updateHud();draw()}
function addPressureRow(){const row=Array.from({length:COLS},()=>COLORS[Math.floor(Math.random()*COLORS.length)]);R.addRow(grid,row);if(grid.length>ROWS)grid.pop();misses=5}
function end(won){active=false;shot=null;$('resultTitle').textContent=won?'GARDEN CLEAR':'GARDEN OVERGROWN';$('resultText').textContent=won?'ALL FLOWERS ARE BLOOMING':'THE BUBBLES REACHED THE GROUND';$('resultOverlay').classList.add('show');updateHud();draw()}
function point(event){const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*canvas.width/rect.width,y:(event.clientY-rect.top)*canvas.height/rect.height}}
function draw(){const p=palette();drawGarden(p);for(let r=0;r<grid.length;r++)for(let c=0;c<COLS;c++)if(grid[r][c]){const pos=center(r,c);drawFlower(pos.x,pos.y,grid[r][c])}if(active&&!shot){traceAim();drawFlower(240,675,current)}if(shot)drawFlower(shot.x,shot.y,shot.color);drawShooter(p);clock+=1}
canvas.addEventListener('pointerdown',event=>{event.preventDefault();if(!active)return;pointerId=event.pointerId;canvas.setPointerCapture?.(pointerId);aim=point(event);draw()});canvas.addEventListener('pointermove',event=>{if(pointerId!==event.pointerId||!active)return;event.preventDefault();aim=point(event);draw()});canvas.addEventListener('pointerup',event=>{if(pointerId!==event.pointerId)return;event.preventDefault();aim=point(event);pointerId=null;shoot()});canvas.addEventListener('pointercancel',()=>pointerId=null);$('newButton').addEventListener('click',initialize);$('resultButton').addEventListener('click',initialize);document.addEventListener('themechange',draw);initialize();
})();
