(() => {
 'use strict';
 const {Content:C,Rules:R,Progress:P,Simulation:S,Input:I,Render:D}=window.FishFeast;
 const $=id=>document.getElementById(id),canvas=$('game'),arena=$('arena'),ctx=canvas.getContext('2d'),KEYS=P.keys;
 const words={
  zh:{title:'小鱼成长记',back:'← 合集',level:'关卡',size:'体型',lives:'生命',score:'得分',growth:'成长',choose:'选择关卡',eat:'小鱼可吃',avoid:'大鱼 / 水母要躲',equal:'同级安全',desktop:'鼠标 / WASD / 方向键游动 · 空格冲刺 · P 暂停',mobile:'按住画布 1:1 拖动 · 松手停下 · 另一指点冲刺',persistence:'3 篇 · 12 关 · 解锁与纪录仅保存在本机；刷新从所选关卡重开，不保存战斗中途状态。',ready:'从小鱼开始',start:'开始游动',pause:'暂停',resume:'继续游动',paused:'歇一会儿',pauseHelp:'水域已经暂停。准备好再继续。',dash:'冲刺',cooldown:'冷却',won:'本关完成',winHelp:'你长大了！下一关已解锁，也可以回头重游。',graduate:'海域毕业！',graduateHelp:'12 关全部完成。选择喜欢的水域，继续挑战自己的纪录。',lost:'下次再来',lossHelp:'本关成长会重置，已解锁关卡和纪录会保留。',again:'再游一次',restart:'重开本关',next:'下一关',menu:'返回选关',confirm:'重开本关？本次成长和分数将重置。',confirmMenu:'返回选关？本次成长和分数将重置，已解锁关卡与纪录保留。',controls:'游动操作',field:'小鱼成长记水域',status:'游戏状态',record:'本关最高分',complete:'已完成',locked:'未解锁',clear:'清除数据',clearHelp:'清除本游戏的本机进度与设置',clearConfirm:'清除本游戏进度与设置并重新载入？其他游戏纪录、语言和主题会保留。',theme:'主题'},
  en:{title:'FISH FEAST',back:'← PLAY',level:'LEVEL',size:'SIZE',lives:'LIVES',score:'SCORE',growth:'GROWTH',choose:'CHOOSE LEVEL',eat:'SMALLER: EAT',avoid:'BIG / JELLY: AVOID',equal:'SAME SIZE: SAFE',desktop:'MOUSE / WASD / ARROWS · SPACE TO DASH · P TO PAUSE',mobile:'HOLD & DRAG 1:1 · RELEASE TO STOP · TAP DASH WITH ANOTHER FINGER',persistence:'3 CHAPTERS · 12 LEVELS · UNLOCKS & RECORDS STAY ON THIS DEVICE. RELOAD RESTARTS THE SELECTED LEVEL; ACTIVE SWIMS ARE NOT SAVED.',ready:'START SMALL',start:'START SWIMMING',pause:'PAUSE',resume:'KEEP SWIMMING',paused:'TAKE A BREATH',pauseHelp:'The water is paused. Continue when you are ready.',dash:'DASH',cooldown:'WAIT',won:'LEVEL COMPLETE',winHelp:'You grew! The next level is unlocked, or revisit this water.',graduate:'OCEAN GRADUATE!',graduateHelp:'All 12 levels cleared. Revisit your favorite water and beat your records.',lost:'TRY ANOTHER SWIM',lossHelp:'Retry resets this swim. Unlocked levels and records stay safe.',again:'SWIM AGAIN',restart:'RESTART LEVEL',next:'NEXT LEVEL',menu:'LEVEL SELECT',confirm:'Restart this level? Current growth and score will reset.',confirmMenu:'Return to level select? Current growth and score reset; unlocks and records stay safe.',controls:'Swimming controls',field:'Fish Feast playfield',status:'Game status',record:'LEVEL BEST',complete:'CLEARED',locked:'LOCKED',clear:'CLEAR DATA',clearHelp:'Clear this game’s local progress and settings',clearConfirm:'Clear this game’s progress and settings and reload? Other games, language and theme stay safe.',theme:'Theme'}
 };
 function get(key){try{return localStorage.getItem(key);}catch(_){return null;}}
 let language=get('play-lang')==='en'?'en':'zh',progress=P.read(get(KEYS.progress)),settings=P.settings(get(KEYS.settings),progress);
 const initialSeed=window.crypto?.getRandomValues?crypto.getRandomValues(new Uint32Array(1))[0]:Date.now()>>>0;
 const state=S.create(760,520,initialSeed);S.start(state,settings.lastLevel-1);state.mode='title';
 let raf=0,last=0,frames=0,clearing=false,oldMode='',lastHUD='',lastSaved='';
 const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
 const input=I.create(canvas,$('dashButton'),{active:()=>state.mode==='playing',player:()=>state.player,world:()=>state,dash:()=>{if(S.dash(state)){sync();paint();}}});
 function write(key,value){if(clearing)return;try{localStorage.setItem(key,JSON.stringify(value));}catch(_) {}}
 function paint(){const scale=canvas.getBoundingClientRect().width/state.width;D.draw(ctx,{...state,goalStatus:S.objective(state)},{palette:D.palettes[document.documentElement.dataset.theme||'light'],scale,dpr:Math.min(2,window.devicePixelRatio||1),language,reduced:reduced.matches});frames++;}
 function text(id,value){const node=$(id),next=String(value);if(node.textContent!==next)node.textContent=next;}
 function fillLevels(){const w=words[language];$('levelSelect').replaceChildren(...C.levels.map(level=>{const o=document.createElement('option');o.value=level.id-1;o.textContent=String(level.id).padStart(2,'0')+' · '+level.chapter[language]+' / '+level.name[language]+(progress.completed.includes(level.id)?' · '+w.complete:!P.canPlay(progress,level.id)?' · '+w.locked:'');o.disabled=!P.canPlay(progress,level.id);return o;}));$('levelSelect').value=state.levelIndex;}
 function utilities(){const w=words[language],clear=document.querySelector('.clear-data-toggle');if(clear){const holder=document.querySelector('.bottom-row');if(holder&&clear.parentElement!==holder)holder.appendChild(clear);clear.dataset.confirm=w.clearConfirm;clear.textContent=w.clear;clear.setAttribute('aria-label',w.clearHelp);clear.setAttribute('title',w.clearHelp);}document.querySelector('.theme-toggle')?.setAttribute('aria-label',w.theme+': '+(document.documentElement.dataset.themeMode||'auto'));}
 function translate(){const w=words[language];document.documentElement.lang=language==='zh'?'zh-CN':'en';document.title=w.title+' · PLAY';for(const node of document.querySelectorAll('[data-text]'))node.textContent=w[node.dataset.text];$('languageButton').textContent=language==='zh'?'EN':'中';$('languageButton').setAttribute('aria-label',language==='zh'?'Switch to English':'切换为中文');canvas.setAttribute('aria-label',w.field);$('growthBar').setAttribute('aria-label',w.growth);$('levelSelect').setAttribute('aria-label',w.choose);$('pauseButton').setAttribute('aria-label',w.pause);$('dashButton').setAttribute('aria-label',w.dash);document.querySelector('.action-row').setAttribute('aria-label',w.controls);document.querySelector('.hud')?.setAttribute('aria-label',w.status);fillLevels();utilities();lastHUD='';sync();paint();}
 function saveRecord(){if(clearing||!['won','lost'].includes(state.mode))return;const marker=state.mode+':'+state.time+':'+state.player.score;if(marker===lastSaved)return;lastSaved=marker;P.record(progress,state.level.id,state.player.score,state.mode==='won');write(KEYS.progress,progress);fillLevels();}
 function goalText(o){const zh=language==='zh',name=o.type?C.species[o.type].name[language]:'',count=Math.min(o.current,o.need)+' / '+o.need;if(o.kind==='revenge')return(zh?'◇ 反吃 ':'◇ REVENGE: ')+name+' '+count;if(o.kind==='catch')return(zh?'◇ 捕获 ':'◇ CATCH: ')+name+' '+count;if(o.kind==='shoal')return(zh?'◇ 同群连吃 ':'◇ SHOAL CHAIN: ')+count;if(o.kind==='lanes')return(zh?'◇ 换道进食 ':'◇ FEED IN LANES: ')+count;return zh?'成长':'GROW';}
 function sync(){const p=state.player,w=words[language],o=S.objective(state),stamp=[state.level.id,state.mode,p.tier,p.growth,p.lives,p.score,Math.ceil(p.cooldown*10),language,o.kind,o.current].join('|');if(stamp===lastHUD)return;lastHUD=stamp;
  text('phaseValue',language==='zh'?({forage:'觅食',hunt:'捕食',reverse:'反杀'})[o.phase]:({forage:'FORAGE',hunt:'HUNT',reverse:'REVERSE'})[o.phase]);text('objectiveValue',o.kind==='grow'?(language==='zh'?'成长':'GROW')+' '+Math.min(p.growth,state.level.goal)+' / '+state.level.goal:goalText(o));
  text('levelValue',String(state.level.id).padStart(2,'0'));text('tierValue',String(p.tier).padStart(2,'0'));text('livesValue',p.lives+' / 3');text('scoreValue',p.score);text('growthValue',p.growth+' / '+state.level.goal);$('growthFill').style.width=Math.min(100,p.growth/state.level.goal*100)+'%';$('growthBar').setAttribute('aria-valuemin','0');$('growthBar').setAttribute('aria-valuemax',state.level.goal);$('growthBar').setAttribute('aria-valuenow',Math.min(p.growth,state.level.goal));
  const playing=state.mode==='playing';$('overlay').hidden=playing;$('pauseButton').disabled=!playing;text('pauseButton',w.pause);$('dashButton').disabled=!playing||p.cooldown>0;text('dashButton',p.cooldown>0?w.cooldown+' '+p.cooldown.toFixed(1):w.dash);
  if(!playing){saveRecord();const mode=state.mode,final=mode==='won'&&state.level.id===C.levels.length;const title=mode==='paused'?w.paused:final?w.graduate:mode==='won'?w.won:mode==='lost'?w.lost:w.ready;const detail=mode==='paused'?w.pauseHelp:final?w.graduateHelp:mode==='won'?w.winHelp:mode==='lost'?w.lossHelp:state.level.brief[language];text('chapterName',String(state.level.id).padStart(2,'0')+' / '+state.level.chapter[language]+' · '+state.level.name[language]);text('message',title);text('detail',detail+(['won','lost'].includes(mode)?' '+w.record+': '+(progress.best[state.level.id]||0):''));text('startButton',mode==='paused'?w.resume:mode==='title'?w.start:w.again);text('restartButton',w.restart);text('nextButton',w.next);text('menuButton',w.menu);$('restartButton').hidden=mode!=='paused';$('nextButton').hidden=mode!=='won'||final;$('menuButton').hidden=mode==='title';$('levelPicker').hidden=mode!=='title';if(oldMode!==mode)$('startButton').focus({preventScroll:true});}
  oldMode=state.mode;
 }
 function cancelLoop(){if(raf)cancelAnimationFrame(raf);raf=0;}
 function schedule(){if(raf||state.mode!=='playing'||document.hidden)return;last=performance.now();raf=requestAnimationFrame(loop);}
 function loop(now){raf=0;if(state.mode!=='playing'||document.hidden)return;S.advance(state,Math.min(.1,(now-last)/1000),input.sample());last=now;paint();sync();if(state.mode==='playing')raf=requestAnimationFrame(loop);else input.clear();}
 function start(){if(document.hidden||clearing)return;cancelLoop();input.clear();if(state.mode==='paused')S.resume(state);else{let index=Number($('levelSelect').value);if(!Number.isInteger(index)||!P.canPlay(progress,index+1))index=state.levelIndex;S.start(state,index);settings.lastLevel=index+1;write(KEYS.settings,settings);lastSaved='';}lastHUD='';sync();canvas.focus({preventScroll:true});paint();schedule();}
 function pause(){input.clear();if(S.pause(state)){cancelLoop();lastHUD='';sync();paint();}}
 function choose(index){if(clearing||!Number.isInteger(index)||!P.canPlay(progress,index+1)){ $('levelSelect').value=state.levelIndex;return false;}cancelLoop();input.clear();S.start(state,index);state.mode='title';settings.lastLevel=index+1;write(KEYS.settings,settings);lastSaved='';fillLevels();lastHUD='';sync();paint();return true;}
 function resize(){const rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;input.clear();const height=760*rect.height/rect.width;S.resize(state,760,height);const dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(state.width*dpr);canvas.height=Math.round(state.height*dpr);paint();}
 $('startButton').addEventListener('click',start);$('pauseButton').addEventListener('click',pause);$('restartButton').addEventListener('click',()=>{if(!clearing&&window.confirm(words[language].confirm)){state.mode='title';start();}});
 $('nextButton').addEventListener('click',()=>{if(state.mode==='won'&&choose(state.levelIndex+1))start();});
 $('menuButton').addEventListener('click',()=>{if(clearing)return;if(state.mode==='paused'&&!window.confirm(words[language].confirmMenu))return;choose(state.levelIndex);});
 $('levelSelect').addEventListener('change',()=>{if(state.mode==='title')choose(Number($('levelSelect').value));});
 $('languageButton').addEventListener('click',()=>{language=language==='zh'?'en':'zh';if(!clearing)try{localStorage.setItem('play-lang',language);}catch(_) {}translate();});
 window.addEventListener('keydown',e=>{if(e.repeat||/INPUT|SELECT|TEXTAREA/.test(e.target?.tagName||''))return;if(e.code==='KeyP'||e.code==='Escape'){e.preventDefault();if(state.mode==='playing')pause();else if(state.mode==='paused'&&e.code==='KeyP')start();}});
 window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
 document.addEventListener('themechange',()=>{utilities();lastHUD='';sync();paint();});reduced.addEventListener('change',paint);window.addEventListener('load',utilities);
 window.addEventListener('game-data-clearing',()=>{clearing=true;pause();cancelLoop();input.clear();});window.addEventListener('pagehide',()=>{pause();saveRecord();});
 new ResizeObserver(resize).observe(arena);window.addEventListener('resize',resize);
 window.FishFeastGame=Object.freeze({snapshot:()=>({...S.snapshot(state),language,frames,input:input.snapshot(),progress:JSON.parse(JSON.stringify(progress)),settings:{...settings},clearPending:clearing,storageKeys:{...KEYS}})});
 translate();resize();
})();
