(() => {
  'use strict';
  const canvas=document.getElementById('board'),ctx=canvas.getContext('2d');
  const COLS=20,ROWS=20,CELL=20,$=id=>document.getElementById(id),scoreEl=$('score'),highScoreEl=$('highScore'),speedEl=$('speed'),message=$('message'),messageTitle=$('messageTitle'),messageHint=$('messageHint');
  let snake,food,direction,nextDirection,score=0,highScore=Number(localStorage.getItem('classic-snake-high-score')||0),state='title',timer=0,last=0,stepMs=145,clock=0;
  highScoreEl.textContent=String(highScore).padStart(6,'0');
  function key(x,y){return x+','+y}function wrap(value,max){return(value+max)%max}
  function randomFood(){const occupied=new Set(snake.map(part=>key(part.x,part.y))),free=[];for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++)if(!occupied.has(key(x,y)))free.push({x,y});if(!free.length)return null;const spot=free[Math.floor(Math.random()*free.length)];spot.kind=['apple','berry','leaf'][Math.floor(Math.random()*3)];return spot}
  function reset(){snake=[{x:10,y:10},{x:9,y:10},{x:8,y:10},{x:7,y:10}];direction={x:1,y:0};nextDirection={x:1,y:0};food=randomFood();score=0;timer=0;stepMs=145;updateHud();draw()}
  function updateHud(){scoreEl.textContent=String(score).padStart(6,'0');highScoreEl.textContent=String(highScore).padStart(6,'0');speedEl.textContent=String(Math.max(1,Math.floor((145-stepMs)/10)+1)).padStart(2,'0')}
  function showMessage(title,hint,button='START'){messageTitle.textContent=title;messageHint.textContent=hint;$('startButton').textContent=button;message.classList.remove('hidden')}function hideMessage(){message.classList.add('hidden')}
  function start(){reset();state='playing';hideMessage();last=performance.now()}function pause(){if(state==='playing'){state='paused';showMessage('PAUSED','PRESS P OR RESUME','RESUME')}else if(state==='paused'){state='playing';hideMessage();last=performance.now()}}
  function saveHigh(){if(score>highScore){highScore=score;localStorage.setItem('classic-snake-high-score',String(highScore))}}
  function gameOver(){state='over';saveHigh();updateHud();showMessage('GARDEN REST','SCORE '+String(score).padStart(6,'0'),'PLAY AGAIN')}
  function gameWon(){state='won';saveHigh();updateHud();showMessage('FULL GARDEN','EVERY APPLE FOUND · SCORE '+String(score).padStart(6,'0'),'PLAY AGAIN')}
  function setDirection(x,y){if(state!=='playing')return;if(x===-direction.x&&y===-direction.y)return;if(x===-nextDirection.x&&y===-nextDirection.y)return;nextDirection={x,y}}
  function tick(){direction=nextDirection;const head=snake[0],next={x:wrap(head.x+direction.x,COLS),y:wrap(head.y+direction.y,ROWS)},eating=food&&next.x===food.x&&next.y===food.y,body=eating?snake:snake.slice(0,-1);if(body.some(part=>part.x===next.x&&part.y===next.y)){gameOver();return}snake.unshift(next);if(eating){score+=10;if(score>highScore)highScore=score;stepMs=Math.max(65,145-Math.floor(score/50)*5);food=randomFood();updateHud();if(!food)gameWon()}else snake.pop()}
  function color(name,fallback){const value=getComputedStyle(document.documentElement).getPropertyValue(name).trim();return value||fallback}
  function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath()}
  function drawGarden(){ctx.fillStyle=color('--canvas-bg','#fffaf0');ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle=color('--canvas-grid','rgba(75,156,149,.14)');ctx.lineWidth=1;for(let i=1;i<COLS;i++){ctx.beginPath();ctx.moveTo(i*CELL+.5,0);ctx.lineTo(i*CELL+.5,canvas.height);ctx.stroke()}for(let i=1;i<ROWS;i++){ctx.beginPath();ctx.moveTo(0,i*CELL+.5);ctx.lineTo(canvas.width,i*CELL+.5);ctx.stroke()}ctx.strokeStyle=color('--coral','#f28c78');ctx.lineWidth=2;ctx.lineCap='round';for(let i=0;i<7;i++){const x=16+i*59,y=10+(i%4)*18;ctx.beginPath();ctx.moveTo(x,y+6);ctx.lineTo(x+5,y);ctx.lineTo(x+11,y+6);ctx.stroke()}ctx.fillStyle=color('--mint','#9eddbd');ctx.globalAlpha=.55;for(let i=0;i<10;i++){const x=(i*47+13)%400,y=387-(i%3)*4;ctx.beginPath();ctx.ellipse(x,y,5,10,(i%2?-1:1)*.5,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
  function drawApple(item){if(!item)return;const p={coral:color('--coral','#f28c78'),yellow:color('--yellow','#f7d66c'),mint:color('--mint','#9eddbd'),ink:color('--ink','#3d3832')},x=item.x*CELL+CELL/2,y=item.y*CELL+CELL/2;ctx.save();ctx.translate(x,y);ctx.strokeStyle=p.ink;ctx.lineWidth=2;ctx.lineJoin='round';if(item.kind==='berry'){ctx.fillStyle=p.purple||color('--purple','#b8a7e8');ctx.beginPath();ctx.arc(-5,2,6,0,Math.PI*2);ctx.arc(5,2,6,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=p.mint;ctx.beginPath();ctx.ellipse(0,-8,5,3,-.3,0,Math.PI*2);ctx.fill();ctx.stroke()}else if(item.kind==='leaf'){ctx.fillStyle=p.mint;ctx.beginPath();ctx.ellipse(0,2,7,10,.5,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle=p.ink;ctx.beginPath();ctx.moveTo(-2,9);ctx.lineTo(4,-7);ctx.stroke()}else{ctx.fillStyle=p.coral;ctx.beginPath();ctx.arc(-5,1,7,0,Math.PI*2);ctx.arc(5,1,7,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=p.mint;ctx.beginPath();ctx.ellipse(5,-9,7,3,-.4,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle=p.ink;ctx.beginPath();ctx.moveTo(0,-4);ctx.lineTo(2,-10);ctx.stroke()}ctx.restore()}
  function drawWorm(){if(!snake)return;const p={mint:color('--mint','#9eddbd'),blue:color('--blue','#8fc9eb'),yellow:color('--yellow','#f7d66c'),ink:color('--ink','#3d3832'),eye:color('--snake-eye','#fffaf0')};for(let i=snake.length-1;i>=0;i--){const part=snake[i],x=part.x*CELL+2,y=part.y*CELL+2,head=i===0;ctx.save();ctx.fillStyle=head?p.mint:(i%2?p.blue:p.mint);ctx.strokeStyle=p.ink;ctx.lineWidth=2;roundRect(x,y,CELL-4,CELL-4,head?8:6);ctx.fill();ctx.stroke();if(head){const ex=part.x*CELL+(direction.x<0?5:direction.x>0?13:7),ey=part.y*CELL+(direction.y<0?5:direction.y>0?13:5);ctx.fillStyle=p.eye;ctx.beginPath();ctx.arc(ex,ey,3,0,Math.PI*2);ctx.arc(ex+(direction.x===0?7:0),ey+(direction.y===0?7:0),3,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=p.ink;ctx.beginPath();ctx.arc(ex,ey,1.3,0,Math.PI*2);ctx.arc(ex+(direction.x===0?7:0),ey+(direction.y===0?7:0),1.3,0,Math.PI*2);ctx.fill();ctx.strokeStyle=p.ink;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x+5,y+2);ctx.lineTo(x+2,y-5);ctx.moveTo(x+13,y+2);ctx.lineTo(x+16,y-5);ctx.stroke()}else{ctx.fillStyle=p.yellow;ctx.globalAlpha=.8;ctx.beginPath();ctx.arc(x+6,y+6,2,0,Math.PI*2);ctx.fill()}ctx.restore()}}
  function draw(){drawGarden();drawApple(food);drawWorm();clock++;if(state==='paused'){ctx.fillStyle=color('--paper','#fffaf0')+'bb';ctx.fillRect(0,0,canvas.width,canvas.height)}}
  function action(name){if(name==='up')setDirection(0,-1);if(name==='down')setDirection(0,1);if(name==='left')setDirection(-1,0);if(name==='right')setDirection(1,0)}
  function loop(time){const dt=Math.min(100,time-last||0);last=time;if(state==='playing'){timer+=dt;if(timer>=stepMs){timer=0;tick();draw()}}requestAnimationFrame(loop)}
  $('startButton').addEventListener('click',()=>{if(state==='paused')pause();else start()});$('newGameButton').addEventListener('click',start);$('pauseButton').addEventListener('click',pause);window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d','W','A','S','D','p','P'].includes(e.key))e.preventDefault();if(e.key==='ArrowUp'||e.key==='w'||e.key==='W')action('up');if(e.key==='ArrowDown'||e.key==='s'||e.key==='S')action('down');if(e.key==='ArrowLeft'||e.key==='a'||e.key==='A')action('left');if(e.key==='ArrowRight'||e.key==='d'||e.key==='D')action('right');if(e.key==='p'||e.key==='P')pause()});document.querySelectorAll('[data-action]').forEach(button=>{button.addEventListener('pointerdown',e=>{e.preventDefault();action(button.dataset.action)});button.addEventListener('contextmenu',e=>e.preventDefault())});document.addEventListener('themechange',draw);reset();showMessage('WORM & APPLE','PRESS START TO PLAY','START GROWING');requestAnimationFrame(loop);
})();
