'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../bubble-tanks/combat.js'),W=require('../bubble-tanks/world.js'),D=require('../bubble-tanks/content.js');
function fixture(id,branch=false){const s=C.create('weapon-'+id);C.start(s);s.player.mass=285;s.player.angle=0;s.player.growth=0;s.player.branches[id]=branch;const def=D.guns.find(g=>g.id===id),gun={id,cost:def.cost,level:1,slot:1,angle:0};s.player.loadout.push(gun);s.player.blueprints[id]=1;s.cooldowns={0:100,1:100};const r=W.current(s.world);r.drops=[];r.cleared=false;r.enemies=[enemy('target',520,400)];return{s,r,gun,target:r.enemies[0]};}
function enemy(id,x,y){return{id,kind:'shooter',x,y,r:18,hp:1000,maxHp:1000,phase:0,angle:0,cooldown:100,slow:0,hit:0,rewarded:false};}
function tick(s,seconds){for(let t=0;t<seconds;t+=.02)C.step(s,{},.02);}
test('twin bursts fire in separate timed beats and the branch adds a third beat',()=>{
 const f=fixture('twin');C.fireWeapon(f.s,f.r,f.gun,f.target);assert.equal(f.r.shots.length,2);assert.equal(f.r.shots.filter(b=>b.delay>0).length,1);const delayed=f.r.shots.find(b=>b.delay>0),x=delayed.x;tick(f.s,.08);assert.equal(delayed.x,x);tick(f.s,.1);assert.ok(delayed.x>x);
 const b=fixture('twin',true);C.fireWeapon(b.s,b.r,b.gun,b.target);assert.equal(b.r.shots.length,3);
});
test('needle has an aim wind-up, fast heavy projectile and a piercing branch',()=>{const f=fixture('needle');C.fireWeapon(f.s,f.r,f.gun,f.target);assert.ok(f.r.shots[0].delay>0);assert.ok(Math.hypot(f.r.shots[0].vx,f.r.shots[0].vy)>500);assert.ok(f.r.shots[0].damage>10);const b=fixture('needle',true);C.fireWeapon(b.s,b.r,b.gun,b.target);assert.equal(b.r.shots[0].pierce,2);});
test('long bubbles pierce unique lined-up foes and focused lances charge before firing',()=>{const f=fixture('pierce');f.r.enemies.push(enemy('second',570,400));C.fireWeapon(f.s,f.r,f.gun,f.target);tick(f.s,.7);assert.ok(f.r.enemies.every(e=>e.hp<e.maxHp));const b=fixture('pierce',true);C.fireWeapon(b.s,b.r,b.gun,b.target);assert.ok(b.r.shots[0].delay>0);assert.ok(b.r.shots[0].pierce>3);});
test('stream has a mandatory heat-stop window and an alternating branch',()=>{const f=fixture('stream');for(let i=0;i<15;i++)C.fireWeapon(f.s,f.r,f.gun,f.target);assert.ok(f.r.shots.length<15);assert.ok(f.s.cooldowns[1]>.5);const b=fixture('stream',true);C.fireWeapon(b.s,b.r,b.gun,b.target);C.fireWeapon(b.s,b.r,b.gun,b.target);assert.notEqual(b.r.shots[0].vy,b.r.shots[1].vy);const hot=fixture('stream');hot.s.player.relics.hot_chamber=1;hot.s.player.heat[1]=.8;C.fireWeapon(hot.s,hot.r,hot.gun,hot.target);assert.ok(hot.r.shots[0].damage>f.r.shots[0].damage);});
test('beam damages contact targets without projectile frames and its branch sweeps',()=>{const f=fixture('beam');C.fireWeapon(f.s,f.r,f.gun,f.target);assert.ok(f.target.hp<1000);assert.equal(f.r.shots.length,0);assert.ok(f.r.effects.some(e=>e.kind==='beam'));const b=fixture('beam',true);for(let i=0;i<3;i++)C.fireWeapon(b.s,b.r,b.gun,b.target);assert.equal(new Set(b.r.effects.map(e=>e.angle)).size,3);});
test('seekers bend gradually, reacquire dead targets and launch an angled branch salvo',()=>{const f=fixture('missile');C.fireWeapon(f.s,f.r,f.gun,f.target);assert.equal(f.r.shots[0].tracking,true);f.target.y=470;tick(f.s,.2);assert.ok(f.r.shots[0].vy>0);f.target.hp=0;f.r.enemies.push(enemy('replacement',540,490));tick(f.s,.04);assert.equal(f.r.shots[0].targetId,'replacement');const b=fixture('missile',true);C.fireWeapon(b.s,b.r,b.gun,b.target);assert.equal(b.r.shots.length,2);assert.notEqual(b.r.shots[0].vy,b.r.shots[1].vy);});
test('mines wait before arming, explode once, stay bounded and branch into a slow field',()=>{const f=fixture('mine',true);f.target.x=450;for(let i=0;i<8;i++)C.fireWeapon(f.s,f.r,f.gun,f.target);assert.equal(f.r.shots.length,4);tick(f.s,.2);assert.equal(f.target.hp,1000);tick(f.s,.4);assert.ok(f.target.hp<1000);assert.ok(f.r.effects.some(e=>e.kind==='coldfield'));assert.equal(f.r.shots.filter(s=>s.weapon==='mine').length,0);});
test('orbit guards intercept a real hostile bubble, refill with a cooldown and change branch radius',()=>{const f=fixture('orbit');f.s.player.shield=0;f.s.player.passives.shield=1;C.fireWeapon(f.s,f.r,f.gun,f.target);assert.equal(f.r.shots.length,3);const radius=49+5*3;C.spawnShot(f.s,f.r,400+radius,400,0,{owner:'enemy',vx:0,vy:0});const hostile=f.r.shots.at(-1);tick(f.s,.02);assert.ok(hostile.ttl<=0);assert.ok(!f.r.shots.some(b=>b.owner==='enemy'));assert.ok(f.s.player.shield>=1);assert.ok(f.s.player.shield<1.1);const b=fixture('orbit',true);C.fireWeapon(b.s,b.r,b.gun,b.target);tick(b.s,.2);assert.notEqual(Math.round(Math.hypot(b.r.shots[0].x-400,b.r.shots[0].y-400)),radius);});
test('vortex pulls small foes, deals timed damage and its expiry branch pulses outward',()=>{const f=fixture('vortex',true);C.fireWeapon(f.s,f.r,f.gun,f.target);assert.equal(f.r.shots[0].weapon,'vortex');assert.ok(f.r.shots[0].fieldRadius>50);f.target.x=575;const x=f.target.x;tick(f.s,.2);assert.ok(f.target.x<x);assert.ok(f.target.hp<1000);f.r.shots[0].ttl=.03;tick(f.s,.04);assert.ok(f.r.effects.some(e=>e.kind==='vortexPulse'));});
test('pulse branch reflects once without renewing projectile lifetime',()=>{const f=fixture('pulse',true);f.target.x=400;f.target.y=560;C.fireWeapon(f.s,f.r,f.gun,f.target);assert.equal(f.r.shots[0].bounces,1);tick(f.s,.96);assert.ok(f.r.shots[0].vx<0);assert.equal(f.r.shots[0].bounces,0);assert.ok(f.r.shots[0].ttl<1.8);});
test('scatter branch emits one-generation fragments without a passive',()=>{const f=fixture('scatter',true);C.fireWeapon(f.s,f.r,f.gun,f.target);assert.equal(f.r.shots.length,5);assert.ok(f.r.shots.every(b=>b.canSplit));tick(f.s,.5);assert.ok(f.r.shots.some(b=>b.weapon==='fragment'));assert.ok(f.r.shots.filter(b=>b.weapon==='fragment').every(b=>b.generation===1&&!b.canSplit));});
test('branched arc adds exactly one side target with target deduplication',()=>{const f=fixture('arc',true);f.r.enemies.push(enemy('b',550,400),enemy('c',550,445),enemy('d',550,355));C.fireWeapon(f.s,f.r,f.gun,f.target);assert.ok(f.r.enemies.every(e=>e.hp<1000));const ids=f.r.effects.filter(e=>e.kind==='arc').map(e=>e.targetId);assert.equal(ids.length,4);assert.equal(new Set(ids).size,4);});
test('live stream heat cools down while jam blocks actual spawning',()=>{const f=fixture('stream');f.s.cooldowns[1]=0;let jam=false;for(let i=0;i<250;i++){C.step(f.s,{},.02);if(f.s.cooldowns[1]>.6){jam=true;break;}}assert.equal(jam,true);const count=f.s.nextId,heat=f.s.player.heat[1];tick(f.s,.3);assert.equal(f.s.nextId,count);assert.ok(f.s.player.heat[1]<heat);tick(f.s,1);assert.ok(f.s.nextId>count);});
test('beam damage remains stable across 50fps and 60fps simulation steps',()=>{function damage(dt){const f=fixture('beam');f.s.cooldowns[1]=0;for(let time=0;time<2-dt/2;time+=dt)C.step(f.s,{},dt);return 1000-f.target.hp;}assert.ok(Math.abs(damage(.02)-damage(1/60))<=2.71);});
// WEAPON CASES
