'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../bubble-tanks/combat.js'),W=require('../bubble-tanks/world.js'),D=require('../bubble-tanks/content.js');
function fixture(skill){const s=C.create('skill-'+skill);C.start(s);s.player.mass=115;s.player.growth=0;s.player.angle=0;s.player.skill=skill;s.player.skills=['overload',skill];s.cooldowns={0:100};const r=W.current(s.world);r.drops=[];r.cleared=false;r.enemies=[{id:'target',kind:'chaser',x:480,y:400,r:18,hp:1000,maxHp:1000,phase:0,angle:0,cooldown:100,slow:0,hit:0,rewarded:false}];return{s,r,target:r.enemies[0]};}
function tick(s,time){for(let t=0;t<time;t+=.02)C.step(s,{},.02);}
test('EMP freezes local threats and consumes charge exactly once',()=>{const f=fixture('emp');f.target.charge=2;C.spawnShot(f.s,f.r,430,400,0,{owner:'enemy',vx:0,vy:0});assert.equal(C.useSkill(f.s),true);assert.ok(f.target.frozen>0);assert.equal(f.target.charge,0);assert.ok(f.r.shots.every(b=>b.ttl<=0));assert.equal(C.useSkill(f.s),false);const x=f.target.x;tick(f.s,.2);assert.equal(f.target.x,x);});
test('blink stays inside the room and leaves only a temporary anchored orbit afterimage',()=>{const f=fixture('blink');f.s.player.x=700;f.s.player.loadout.push({id:'orbit',cost:4,level:1,slot:1,angle:0});f.s.cooldowns[1]=100;const old=f.s.player.x;C.useSkill(f.s);assert.ok(Math.hypot(f.s.player.x-400,f.s.player.y-400)<=330);assert.ok(f.s.player.invulnerable>0);assert.equal(f.r.shots.filter(b=>b.weapon==='orbit').length,3);assert.ok(f.r.shots.every(b=>b.anchorX===old&&b.ttl<1));tick(f.s,1);assert.ok(!f.r.shots.some(b=>b.weapon==='orbit'));});
test('barrier catches side shots but retains a front gap and bulwark reinforces coverage',()=>{const f=fixture('barrier');C.useSkill(f.s);const radius=f.s.player.barrierRadius;C.spawnShot(f.s,f.r,400,400-radius,0,{owner:'enemy',vx:0,vy:0});C.spawnShot(f.s,f.r,400+radius,400,0,{owner:'enemy',vx:0,vy:0});tick(f.s,.02);assert.equal(f.r.shots.filter(b=>b.owner==='enemy').length,1);assert.ok(f.r.shots[0].x>400);const b=fixture('barrier');b.s.player.chassis='bulwark';C.useSkill(b.s);assert.ok(b.s.player.barrierGap<f.s.player.barrierGap);});
test('burst knocks back foes and recycles at most four bullets without growth',()=>{const f=fixture('burst');f.s.player.passives.converter=2;for(let i=0;i<10;i++)C.spawnShot(f.s,f.r,420,400+i,0,{owner:'enemy',vx:0,vy:0});const x=f.target.x,growth=f.s.player.growth;C.useSkill(f.s);assert.ok(f.target.hp<1000);assert.ok(f.target.x>x);assert.equal(f.r.drops.length,4);assert.ok(f.r.drops.every(d=>d.source==='self'));tick(f.s,.5);assert.equal(f.s.player.growth,growth);});
test('decoy redirects enemy aim and expires into one armed-later mine',()=>{const f=fixture('decoy');f.s.player.loadout.push({id:'mine',cost:3,level:1,slot:1,angle:0});f.s.cooldowns[1]=100;C.useSkill(f.s);tick(f.s,.02);assert.notEqual(f.target.angle,Math.atan2(f.s.player.y-f.target.y,f.s.player.x-f.target.x));tick(f.s,3.1);assert.ok(!f.r.effects.some(e=>e.kind==='decoy'));assert.equal(f.r.shots.filter(b=>b.weapon==='mine').length,1);});
test('overdrive actually accelerates fire for four seconds and then expires',()=>{const f=fixture('overdrive'),base=fixture('overload');f.s.cooldowns={};base.s.cooldowns={};C.useSkill(f.s);assert.ok(f.s.player.overdriveTime>0);tick(f.s,1.2);tick(base.s,1.2);assert.ok(f.s.nextId>base.s.nextId);tick(f.s,3);assert.equal(f.s.player.overdriveTime,0);});
test('rally launches bounded temporary drones that fire and disappear',()=>{const f=fixture('swarm');f.s.player.passives.swarm_expand=2;f.s.player.chassis='swarmbody';C.useSkill(f.s);assert.equal(f.r.shots.filter(b=>b.weapon==='drone').length,6);tick(f.s,.8);assert.ok(f.s.nextId>6);assert.ok(f.target.hp<1000);tick(f.s,6);assert.ok(!f.r.shots.some(b=>b.weapon==='drone'));});
// SKILL CASES
