'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {environment}=require('./helpers/bubble-runtime');
const C=require('../bubble-tanks/combat'),W=require('../bubble-tanks/world'),S=require('../bubble-tanks/storage');
const files=['render.js','input.js','ui.js','sound.js','game.js'];
test('clearing data cannot resurrect an expedition on blur, pagehide or a queued action',()=>{const b=environment(files);b.elements.get('startButton').click();b.window.emit('game-data-clearing');b.stored.clear();b.window.emit('blur');b.window.emit('pagehide');b.elements.get('resumeButton').click();b.elements.get('startButton').click();b.frames(4);assert.equal(b.stored.size,0);assert.notEqual(b.B.snapshot().mode,'running');});
test('closing a modal after native suspension returns to pause, not combat',()=>{for(const modal of ['map','assembly']){const b=environment(files);b.elements.get('startButton').click();b.elements.get(modal==='map'?'mapButton':'roomActionButton').click();assert.equal(b.B.snapshot().mode,modal);b.document.hidden=true;b.document.emit('visibilitychange');b.document.hidden=false;b.document.emit('visibilitychange');b.elements.get(modal==='map'?'mapCloseButton':'assemblyCancelButton').click();assert.equal(b.B.snapshot().mode,'paused');}});
test('hidden documents reject start and resume actions',()=>{const b=environment(files);b.document.hidden=true;b.elements.get('startButton').click();assert.equal(b.B.snapshot().mode,'title');b.document.hidden=false;b.elements.get('startButton').click();b.window.emit('blur');b.document.hidden=true;b.elements.get('resumeButton').click();assert.equal(b.B.snapshot().mode,'paused');});
test('old evolution-card handlers cannot act on a replaced or repeated offer',()=>{const b=environment(['ui.js']),chosen=[],ui=b.B.UI.create({action(){},choose:id=>chosen.push(id),buy(){},edit(){}});const s=b.B.Combat.create('card-owner');s.lang='en';s.mode='upgrade';s.pending=2;s.offers=[b.B.Content.upgrades.find(u=>u.id==='rapid')];const settings={};ui.update(s,settings);const old=b.elements.get('upgradeChoices').children[0];s.level++;s.player.passives.rapid=1;s.offers=[s.offers[0]];ui.update(s,settings);old.click();assert.equal(chosen.length,0);const current=b.elements.get('upgradeChoices').children[0];current.click();current.click();assert.equal(chosen.length,1);});
