'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {environment,Element}=require('./helpers/bubble-runtime');
function input(){const b=environment(['input.js']),actions=[];const api=b.B.Input.create(b.elements.get('game'),{isRunning:()=>true,action:name=>actions.push(name)});api.configure({dualStick:true},()=>({x:400,y:400}));for(const id of ['joystick','aimJoystick'])b.elements.get(id).rect={left:0,top:0,width:100,height:100};return {...b,api,actions};}
const pointer=(id,x=80,y=50,extra={})=>({pointerId:id,pointerType:'touch',button:0,clientX:x,clientY:y,...extra});
test('touch dash and skill activate while movement is held, without a compatibility-click duplicate',()=>{const b=input(),stick=b.elements.get('joystick');stick.emit('pointerdown',pointer(1));for(const [id,action]of [['dashButton','dash'],['skillButton','skill']]){const button=b.elements.get(id);button.emit('pointerdown',pointer(2));assert.equal(b.actions.at(-1),action);button.emit('pointerup',pointer(2));button.emit('click',{detail:1});assert.equal(b.actions.filter(a=>a===action).length,1);assert.ok(b.api.sample().x>0);}b.elements.get('dashButton').emit('click',{detail:0});assert.equal(b.actions.filter(a=>a==='dash').length,2,'native keyboard click remains available');});
test('aim stick returns to auto aim at its neutral deadzone and ignores another pointer release',()=>{const b=input(),stick=b.elements.get('aimJoystick');stick.emit('pointerdown',pointer(3));assert.ok(b.api.sample().aim);stick.emit('pointerup',pointer(4));assert.ok(b.api.sample().aim);stick.emit('pointermove',pointer(3,50,50));assert.equal(b.api.sample().aim,null);assert.equal(b.elements.get('aimThumb').style.transform,'translate(-50%,-50%)');});
test('secondary mouse buttons never acquire a movement or aim stick',()=>{for(const id of ['joystick','aimJoystick']){const b=input();b.elements.get(id).emit('pointerdown',pointer(1,80,50,{pointerType:'mouse',button:2}));assert.equal(b.api.sample().x,0);assert.equal(b.api.sample().aim,null);}});
test('keyboard shortcuts preserve browser modifiers, editable fields and native button Space',()=>{const b=input();for(const props of [{code:'KeyW',ctrlKey:true},{code:'KeyE',metaKey:true},{code:'Space',target:new Element('button')},{code:'KeyW',target:{isContentEditable:true}}]){const event=b.window.emit('keydown',props);assert.equal(event.defaultPrevented,false);}assert.equal(b.actions.length,0);assert.equal(b.api.sample().y,0);b.window.emit('keydown',{code:'KeyW'});assert.equal(b.api.sample().y,-1);b.api.clear();b.window.emit('keydown',{code:'KeyW',repeat:true});assert.equal(b.api.sample().y,0,'held repeat after suspension needs a fresh press');});
