'use strict';const test=require('node:test'),assert=require('node:assert/strict'),C=require('../bubble-tanks/combat.js'),W=require('../bubble-tanks/world.js'),R=require('../bubble-tanks/rules.js');
function fixture(){const s=C.create('modifiers');C.start(s);s.player.mass=115;s.player.growth=0;s.player.angle=0;s.cooldowns={0:100};const r=W.current(s.world);r.drops=[];r.cleared=false;const e={id:'target',kind:'shooter',x:520,y:400,r:18,hp:1000,maxHp:1000,phase:0,angle:0,cooldown:100,slow:0,hit:0,rewarded:false};r.enemies=[e];return{s,r,e,p:s.player};}
function tick(s,time){for(let t=0;t<time;t+=.02)C.step(s,{},.02);}
test('cannon cores increase actual direct damage',()=>{const f=fixture();f.p.passives.damage=1;C.hurtEnemy(f.s,f.r,f.e,10,{weapon:'pulse'});assert.equal(f.e.hp,988.5);});
test('glass core increases actual outgoing damage by its declared factor',()=>{const f=fixture();f.p.relics.glass_core=1;C.hurtEnemy(f.s,f.r,f.e,10,{weapon:'pulse'});assert.equal(f.e.hp,986.5);});
test('echo shells retain their constant damage penalty',()=>{const f=fixture();f.p.relics.echo_shell=1;C.hurtEnemy(f.s,f.r,f.e,10,{weapon:'pulse'});assert.ok(Math.abs(f.e.hp-991.2)<.0001);});
test('active hives penalize regular weapons but not drone shots',()=>{const f=fixture();f.p.relics.active_hive=1;C.hurtEnemy(f.s,f.r,f.e,10,{weapon:'pulse'});assert.equal(f.e.hp,992);C.hurtEnemy(f.s,f.r,f.e,10,{weapon:'drone_pulse'});assert.equal(f.e.hp,982);});
test('duplicate cannons have diminishing output instead of linear stacking',()=>{const f=fixture();f.p.loadout.push({...f.p.loadout[0],slot:1});C.hurtEnemy(f.s,f.r,f.e,10,{weapon:'pulse'});assert.ok(1000-f.e.hp<7);});
test('valid weapon hits leave bounded slow, arc charge and a living-target marker',()=>{const f=fixture();f.p.passives.frost=2;f.p.passives.conductive=1;f.p.passives.mark=1;C.hurtEnemy(f.s,f.r,f.e,10,{weapon:'arc'});assert.ok(f.e.slow>0);assert.ok(f.e.charge>0);assert.ok(f.e.mark>0);tick(f.s,3);assert.equal(f.e.charge,0);assert.equal(f.e.mark,0);C.hurtEnemy(f.s,f.r,f.e,2000,{weapon:'pulse'});assert.equal(f.e.mark,0);});
test('sonar exposes only distant targets to needle damage',()=>{const f=fixture();f.p.passives.sonar=2;f.e.x=680;C.hurtEnemy(f.s,f.r,f.e,10,{weapon:'needle'});assert.equal(f.e.hp,987);f.e.x=520;C.hurtEnemy(f.s,f.r,f.e,10,{weapon:'needle'});assert.equal(f.e.hp,977);});
test('siphon uses effective damage, per-second quotas, and grants no growth',()=>{const f=fixture();f.p.mass=100;f.p.passives.siphon=2;for(let i=0;i<30;i++)C.hurtEnemy(f.s,f.r,f.e,10,{weapon:'pulse'});assert.ok(Math.abs(f.p.mass-104)<.0001);f.p.overdriveTime=4;for(let i=0;i<10;i++)C.hurtEnemy(f.s,f.r,f.e,10,{weapon:'pulse'});assert.ok(Math.abs(f.p.mass-106)<.0001);assert.equal(f.p.growth,0);f.s.time=1;f.e.hp=3;const mass=f.p.mass;C.hurtEnemy(f.s,f.r,f.e,999999,{weapon:'pulse'});assert.ok(f.p.mass-mass<.4);});
test('crystal beams need sustained contact and retain a freeze immunity gap',()=>{const f=fixture();f.p.relics.ice_crystal=1;for(let i=0;i<4;i++)C.hurtEnemy(f.s,f.r,f.e,1,{weapon:'beam'});assert.ok(f.e.frozen>0);f.e.frozen=0;for(let i=0;i<20;i++)C.hurtEnemy(f.s,f.r,f.e,1,{weapon:'beam'});assert.equal(f.e.frozen,0);assert.ok(f.e.freezeImmuneUntil>1);});
test('pierce couplers let a real direct bubble hit three unique enemies',()=>{const f=fixture();f.p.passives.pierce_amp=2;f.r.enemies.push({...f.e,id:'b',x:555},{...f.e,id:'c',x:590});C.spawnShot(f.s,f.r,420,400,0,{weapon:'pulse'});assert.equal(f.r.shots[0].pierce,3);tick(f.s,.6);assert.ok(f.r.enemies.every(e=>e.hp<1000));});
test('fission applies one-generation splitting and shortens actual lifetimes',()=>{const f=fixture();f.p.relics.fission_core=1;C.spawnShot(f.s,f.r,420,400,0,{weapon:'pulse'});assert.ok(f.r.shots[0].canSplit);assert.ok(f.r.shots[0].ttl<1.8);tick(f.s,.4);assert.ok(f.r.shots.some(b=>b.weapon==='fragment'));assert.ok(f.r.shots.filter(b=>b.weapon==='fragment').every(b=>b.generation===1&&!b.canSplit));});
test('refraction films reflect once with a rank-based damage bonus and unchanged lifetime',()=>{const f=fixture();f.e.y=560;f.p.passives.refract=2;C.spawnShot(f.s,f.r,420,400,0,{weapon:'pulse'});tick(f.s,.96);const b=f.r.shots[0];assert.ok(b.vx<0);assert.equal(b.bounces,0);assert.ok(b.damage>5);assert.ok(b.ttl<1.8);});
test('three twin hits strengthen only the next volley and a miss resets the streak',()=>{const f=fixture();f.p.passives.focus=2;f.p.loadout.push({id:'twin',level:1,cost:2,slot:1,angle:0});for(let i=0;i<3;i++)C.hurtEnemy(f.s,f.r,f.e,1,{weapon:'twin'});assert.equal(f.p.focusReady,true);C.fireWeapon(f.s,f.r,f.p.loadout[1],f.e);assert.ok(f.r.shots.every(b=>b.focusBoost===1.5));assert.equal(f.p.focusReady,false);const hp=f.e.hp;C.hurtEnemy(f.s,f.r,f.e,5,{weapon:'twin',focusBoost:f.r.shots[0].focusBoost});assert.equal(hp-f.e.hp,7.5);f.r.shots=[];f.s.cooldowns[1]=100;f.p.focusHits=2;C.spawnShot(f.s,f.r,410,450,0,{weapon:'twin',ttl:.01,mount:1});tick(f.s,.02);assert.equal(f.p.focusHits,0);});
test('every third direct volley echoes once without recursion or double fission shortening',()=>{const f=fixture();f.p.relics.echo_shell=1;f.p.relics.fission_core=1;for(let i=0;i<3;i++)C.fireWeapon(f.s,f.r,f.p.loadout[0],f.e);assert.equal(f.r.shots.length,4);const echo=f.r.shots.find(b=>b.echo);assert.ok(echo);assert.equal(echo.ttl,f.r.shots[0].ttl);assert.ok(echo.delay>0);tick(f.s,.5);assert.ok(f.r.shots.length<12);});
test('conductive seas add one bounded real arc jump',()=>{const f=fixture();f.p.relics.conductive_sea=1;f.p.loadout.push({id:'arc',cost:6,level:1,slot:1,angle:0});for(let i=1;i<4;i++)f.r.enemies.push({...f.e,id:'e'+i,x:520+i*35});C.fireWeapon(f.s,f.r,f.p.loadout[1],f.e);assert.equal(f.r.enemies.filter(e=>e.hp<1000).length,4);});
// MODIFIER CASES
