'use strict';const test=require('node:test'),assert=require('node:assert/strict'),C=require('../bubble-tanks/combat.js'),W=require('../bubble-tanks/world.js'),D=require('../bubble-tanks/content.js');
function fixture(kind){const s=C.create('enemy-'+kind);C.start(s);s.player.mass=115;s.player.growth=0;s.player.invulnerable=100;s.cooldowns={0:100};const r=W.current(s.world);r.drops=[];r.cleared=false;const def=D.enemies.find(e=>e.id===kind),e={id:'target',kind,x:600,y:400,r:def.r,hp:100,maxHp:100,phase:0,angle:Math.PI,cooldown:0,slow:0,hit:0,warning:0,rewarded:false};r.enemies=[e];return{s,r,e};}
function tick(s,t){for(let a=0;a<t;a+=.02)C.step(s,{},.02);}
test('aimed drifters sidestep instead of only wandering',()=>{const f=fixture('grazer');f.s.target=f.e.id;tick(f.s,.1);assert.ok(f.e.y<400);});
test('burst towers stay fixed and fire three timed beats',()=>{const f=fixture('shooter');tick(f.s,1);assert.equal(f.e.x,600);assert.equal(f.e.y,400);assert.equal(f.r.shots.filter(b=>b.owner==='enemy').length,3);assert.ok(new Set(f.r.shots.map(b=>Math.round(b.x))).size>1);});
test('sniper telegraphs a long line before a genuinely fast needle',()=>{const f=fixture('sniper');tick(f.s,.2);assert.ok(f.r.effects.some(e=>e.kind==='aim'&&e.length>=600));assert.equal(f.r.shots.length,0);tick(f.s,.9);assert.ok(f.r.shots.some(b=>Math.hypot(b.vx,b.vy)>=300));});
test('fan walkers fire a warned five-direction fan',()=>{const f=fixture('scatterer');tick(f.s,.8);assert.equal(f.r.shots.length,5);assert.equal(new Set(f.r.shots.map(b=>Math.round(b.vy))).size,5);});
test('guardian front is protected while the rear remains exposed',()=>{const f=fixture('guardian');C.hurtEnemy(f.s,f.r,f.e,20,{x:400,y:400});assert.ok(f.e.hp>80);const hp=f.e.hp;C.hurtEnemy(f.s,f.r,f.e,20,{x:700,y:400});assert.equal(hp-f.e.hp,20);});
test('broods summon bounded rewardless minions and stop after death',()=>{const f=fixture('spawner');tick(f.s,.9);assert.equal(f.r.enemies.filter(e=>e.rewardless).length,2);tick(f.s,15);assert.ok(f.r.enemies.length<=7);C.hurtEnemy(f.s,f.r,f.e,1000);const count=f.r.enemies.length;tick(f.s,5);assert.equal(f.r.enemies.length,count);});
test('mine layers lay stationary delayed-arming hostile mines',()=>{const f=fixture('miner');tick(f.s,.1);const mine=f.r.shots.find(b=>b.weapon==='hostile_mine');assert.ok(mine);assert.ok(mine.arm>0);assert.equal(mine.vx,0);assert.equal(mine.vy,0);assert.ok(mine.ttl<=7);});
test('splitters create exactly two nonrecursive rewardless children',()=>{const f=fixture('splitter');C.hurtEnemy(f.s,f.r,f.e,1000);const children=f.r.enemies.filter(e=>e.rewardless);assert.equal(children.length,2);assert.ok(children.every(e=>e.kind==='chaser'));for(const e of children)C.hurtEnemy(f.s,f.r,e,1000);assert.equal(f.r.enemies.length,3);assert.equal(f.s.score,10);assert.equal(f.r.drops.length,4);});
test('laser foes warn first then sustain a short beam rather than emit ordinary bubbles',()=>{const f=fixture('laser');tick(f.s,.2);assert.ok(f.e.warning>.4);tick(f.s,.8);assert.ok(f.r.effects.some(e=>e.kind==='enemyBeam'));assert.equal(f.r.shots.length,0);});
test('gravity keepers telegraph temporary pull fields',()=>{const f=fixture('vortexer');tick(f.s,.1);assert.ok(f.r.effects.some(e=>e.kind==='enemyPullWarning'));tick(f.s,.9);assert.ok(f.r.effects.some(e=>e.kind==='enemyPull'&&e.ttl<=1.8));});
test('detonators visibly count down and cannot create farmable enemy rewards',()=>{const f=fixture('bomber');f.e.x=470;tick(f.s,.2);assert.ok(f.e.fuse>0);assert.ok(f.r.effects.some(e=>e.kind==='fuse'));tick(f.s,.8);assert.equal(f.e.hp,0);assert.equal(f.s.score,0);});
test('menders visibly repair only damaged live allies',()=>{const f=fixture('healer');const ally={...f.e,id:'ally',kind:'chaser',x:560,hp:20,maxHp:100,cooldown:100};f.r.enemies.push(ally);tick(f.s,.1);assert.ok(ally.hp>20);assert.ok(f.r.effects.some(e=>e.kind==='healLink'));assert.equal(f.e.hp,100);});
test('leeches heal only from actual mass drain and remain rate limited',()=>{const f=fixture('leecher');f.s.player.invulnerable=0;f.e.x=450;f.e.hp=50;tick(f.s,.02);assert.ok(f.e.hp>50);assert.ok(f.s.player.mass<115);const hp=f.e.hp;tick(f.s,.3);assert.equal(f.e.hp,hp);assert.equal(f.s.player.growth,0);});
test('lobbers warn on a landing point before creating a bounded explosion',()=>{const f=fixture('lobber');tick(f.s,.2);assert.ok(f.r.effects.some(e=>e.kind==='bombWarning'));assert.ok(!f.r.effects.some(e=>e.danger));tick(f.s,.8);assert.ok(f.r.effects.some(e=>e.kind==='enemyBlast'&&e.danger&&e.ttl<=.4));});
test('blinkers mark a safe destination before moving there',()=>{const f=fixture('teleporter');tick(f.s,.2);assert.equal(f.e.x,600);assert.ok(f.r.effects.some(e=>e.kind==='warpMark'));tick(f.s,.7);assert.notEqual(f.e.x,600);assert.ok(Math.hypot(f.e.x-f.s.player.x,f.e.y-f.s.player.y)>=100);});
test('reflectors return frontal bubbles but expose their rear',()=>{const f=fixture('reflector');C.spawnShot(f.s,f.r,580,400,0,{weapon:'pulse'});tick(f.s,.02);assert.equal(f.e.hp,100);assert.ok(f.r.shots.some(b=>b.owner==='enemy'&&b.vx<0));const back=fixture('reflector');C.spawnShot(back.s,back.r,620,400,Math.PI,{weapon:'pulse'});tick(back.s,.02);assert.ok(back.e.hp<100);});
test('breaker needles deplete shields without increasing mass damage',()=>{const f=fixture('breaker');tick(f.s,.9);assert.ok(f.r.shots.some(b=>b.shieldBreak));f.s.player.invulnerable=0;f.s.player.shield=18;C.spawnShot(f.s,f.r,430,400,0,{owner:'enemy',vx:0,vy:0,damage:6,shieldBreak:true});tick(f.s,.02);assert.equal(f.s.player.shield,0);assert.equal(f.s.player.mass,115);});
test('escort cores lose protection when their two destructible nodes die',()=>{const f=fixture('escort');tick(f.s,.02);const nodes=f.r.enemies.filter(e=>e.parent===f.e.id);assert.equal(nodes.length,2);C.hurtEnemy(f.s,f.r,f.e,20);assert.ok(f.e.hp>80);for(const n of nodes)C.hurtEnemy(f.s,f.r,n,100);const hp=f.e.hp;C.hurtEnemy(f.s,f.r,f.e,20);assert.equal(hp-f.e.hp,20);assert.equal(f.s.score,0);});
// ENEMY CASES
