'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../bubble-tanks/combat.js'),W=require('../bubble-tanks/world.js'),R=require('../bubble-tanks/rules.js');
function f(){const s=C.create('remaining');C.start(s);const p=s.player;p.mass=115;p.growth=0;p.angle=0;s.cooldowns={0:100};const r=W.current(s.world);r.drops=[];r.cleared=false;const e={id:'foe',kind:'shooter',x:550,y:400,r:18,hp:999,maxHp:999,phase:0,angle:0,cooldown:100,hit:0};r.enemies=[e];return{s,p,r,e};}
function tick(s,t){for(let i=0;i<Math.round(t/.02);i++)C.step(s,{},.02);}
test('heavy core and gravity sac slow actual movement; phase extends dash protection',()=>{const a=f(),b=f();b.p.relics.heavy_core=1;b.p.relics.gravity_sac=1;C.step(a.s,{x:1},.04);C.step(b.s,{x:1},.04);assert.ok(b.p.x-400<(a.p.x-400)*.8);b.p.chassis='phase';C.dash(b.s,{x:1});assert.ok(b.p.invulnerable>.3);});
test('cooling reduces actual skill and dash cooldown while tail pays its extra second',()=>{const a=f(),b=f();b.p.passives.cooling=3;C.dash(a.s);C.dash(b.s);assert.ok(b.p.dashClock<a.p.dashClock);C.useSkill(a.s);C.useSkill(b.s);assert.ok(b.p.skillClock<a.p.skillClock);const x=f();x.p.relics.turbulent_tail=1;C.dash(x.s);assert.equal(x.p.dashClock,4.2);});
test('economy and crystal penalties apply to real firing intervals',()=>{const a=f(),b=f();a.s.cooldowns={};b.s.cooldowns={};b.p.relics.efficiency=1;b.p.relics.ice_crystal=1;C.step(a.s,{},.02);C.step(b.s,{},.02);assert.ok(b.s.cooldowns[0]>a.s.cooldowns[0]*1.3);});
test('shed recycler raises recovered mass but not growth',()=>{const a=f(),b=f();b.p.passives.recycler=3;C.hurtPlayer(a.s,a.r,20);C.hurtPlayer(b.s,b.r,20);assert.ok(b.r.drops.reduce((n,d)=>n+d.value,0)>a.r.drops.reduce((n,d)=>n+d.value,0));assert.ok(b.r.drops.every(d=>d.source==='self'));assert.equal(b.p.growth,0);});
test('emergency membrane triggers only once per room and never revives fatal hits',()=>{const a=f();a.p.mass=25;a.p.passives.emergency=2;C.hurtPlayer(a.s,a.r,10);assert.ok(a.p.shield>0);a.p.shield=0;a.p.invulnerable=0;C.hurtPlayer(a.s,a.r,1);assert.equal(a.p.shield,0);const b=f();b.s.rescueLeft=0;b.p.mass=1;b.p.passives.emergency=2;C.hurtPlayer(b.s,b.r,100);assert.equal(b.s.mode,'over');});
test('collector consumes remaining drops on first clear without repeating growth',()=>{const a=f();a.p.passives.collector=1;a.e.hp=0;a.r.drops=[{id:'reward',x:650,y:400,value:8,source:'enemy',collected:false}];C.step(a.s,{},.02);assert.equal(a.p.mass,123);assert.equal(a.p.growth,8);C.step(a.s,{},.02);assert.equal(a.p.growth,8);});
test('steering gently snaps only a close manual aim',()=>{const a=f();a.p.passives.steering=3;C.step(a.s,{aim:{x:550,y:420}},.02);assert.ok(a.p.angle<Math.atan2(20,150));const b=f();b.p.passives.steering=3;C.step(b.s,{aim:{x:400,y:200}},.02);assert.equal(b.p.angle,-Math.PI/2);});
test('cold mist actually slows enemies and tail deals bounded temporary damage',()=>{const a=f();a.r.effects.push({kind:'coldfield',x:a.e.x,y:a.e.y,r:85,ttl:2,duration:2});C.step(a.s,{},.02);assert.ok(a.e.slow>0);const b=f();b.e.x=400;b.p.relics.turbulent_tail=1;C.dash(b.s,{x:1});tick(b.s,.5);assert.ok(b.e.hp<999);assert.ok(b.r.effects.some(e=>e.kind==='tail'));tick(b.s,2);assert.ok(!b.r.effects.some(e=>e.kind==='tail'));});
