const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');

function element(id=''){const classes=new Set(id==='resultOverlay'?[]:[]);return{id,textContent:'',value:id==='difficulty'?'medium':id==='firstPlayer'?'human':'',disabled:false,dataset:{},children:[],style:{},listeners:{},className:'',classList:{add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x)},appendChild(x){this.children.push(x)},replaceChildren(){this.children=[]},setAttribute(){},addEventListener(t,f){this.listeners[t]=f},getBoundingClientRect(){return{left:0,width:700}}}}
function boot({fixedAi=false}={}){const ids=['board','status','turnDot','difficulty','firstPlayer','undoButton','newButton','wins','losses','draws','resultOverlay','resultTitle','resultText','resultButton'],nodes=Object.fromEntries(ids.map(id=>[id,element(id)]));const cols=Array.from({length:7},(_,i)=>{const e=element();e.dataset.column=String(i);return e});const timers=[];const sandbox={window:{ConnectFourRules:null,setTimeout:fn=>{timers.push(fn)}},document:{getElementById:id=>nodes[id],querySelectorAll:()=>cols,createElement:()=>element(),addEventListener(){}},localStorage:{getItem(){return null},setItem(){}},console};const rulesSandbox={module:{exports:{}},exports:{}};vm.runInNewContext(fs.readFileSync('connect-four/rules.js','utf8'),rulesSandbox);sandbox.window.ConnectFourRules=fixedAi?{...rulesSandbox.module.exports,chooseMove:()=>6}:rulesSandbox.module.exports;vm.createContext(sandbox);vm.runInContext(fs.readFileSync('connect-four/game.js','utf8'),sandbox);return{nodes,cols,flush(){while(timers.length)timers.shift()()}}}
test('one human column click creates one human disc and one AI reply',()=>{const app=boot();app.cols[3].listeners.click();app.flush();const cells=app.nodes.board.children;assert.equal(cells.filter(c=>c.className.includes('human')).length,1);assert.equal(cells.filter(c=>c.className.includes('computer')).length,1)});
test('undo restores the board before the latest human and AI turn',()=>{const app=boot();app.cols[3].listeners.click();app.flush();app.nodes.undoButton.listeners.click();assert.equal(app.nodes.board.children.filter(c=>/human|computer/.test(c.className)).length,0)});
test('a completed game opens a clear result overlay with replay action',()=>{const app=boot({fixedAi:true});for(const col of [0,1,2]){app.cols[col].listeners.click();app.flush()}app.cols[3].listeners.click();assert.equal(app.nodes.resultOverlay.classList.contains('show'),true);assert.equal(app.nodes.resultTitle.textContent,'YOU WIN');assert.equal(app.nodes.resultButton.textContent,'PLAY AGAIN')});
