const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const read=p=>fs.readFileSync(p,'utf8');

test('Endless Runner has a complete mobile entrypoint',()=>{const html=read('endless-runner/index.html'),css=read('endless-runner/style.css');assert.match(html,/viewport-fit=cover/);assert.doesNotMatch(html,/user-scalable=no/);for(const id of ['game','startButton','pauseButton','jumpButton','dropButton','distance','best','speed','stickers'])assert.match(html,new RegExp(`id="${id}"`));assert.match(css,/touch-action:\s*none/);assert.match(css,/-webkit-touch-callout:\s*none/);});
test('runner supports variable-height jump, coyote time, jump buffering, and fast fall',()=>{const js=read('endless-runner/game.js');assert.match(js,/JUMP_SPEED/);assert.match(js,/GRAVITY/);assert.match(js,/jumpHeld/);assert.match(js,/jumpHoldTime/);assert.match(js,/fastFall/);assert.match(js,/jumpBuffer/);assert.match(js,/coyoteTime/);assert.match(js,/function jump/);assert.match(js,/function drawPlayer/)});
test('mobile controls put fast fall on the left and the primary jump action on the right',()=>{const html=read('endless-runner/index.html');assert.ok(html.indexOf('id="dropButton"')<html.indexOf('id="jumpButton"'));});
test('obstacle generator uses speed-aware reaction distance and avoids impossible patterns',()=>{const js=read('endless-runner/game.js');assert.match(js,/function spawnPattern/);assert.match(js,/reactionDistance/);assert.match(js,/MIN_REACTION_TIME/);assert.match(js,/lastPattern/);assert.match(js,/safe|fair/i);});
test('game includes varied stationery obstacles, combos, gaps, coins and progressive speed',()=>{const js=read('endless-runner/game.js');for(const marker of ['spike','crate','pencil','ruler','ink','combo','gap','coin','scrollSpeed'])assert.match(js,new RegExp(marker));});
test('runner uses four staged pace bands with a gentler cap',()=>{const js=read('endless-runner/game.js');assert.match(js,/const RUN_STAGES/);assert.match(js,/WARM UP/);assert.match(js,/DESK FLOW/);assert.match(js,/BUSY DESK/);assert.match(js,/STICKER RUSH/);assert.match(js,/function currentStage/);assert.match(js,/endSpeed:\s*1325/);assert.match(js,/travelDistance/);});
test('collision handles ground obstacles gaps and game over once',()=>{const js=read('endless-runner/game.js');assert.match(js,/function checkCollision/);assert.match(js,/function gameOver/);assert.match(js,/state\s*=\s*['"]over['"]/);assert.match(js,/onGround/);});
test('eraser and pencil use distinct pixel art with the existing collision geometry',()=>{const js=read('endless-runner/game.js');assert.match(js,/h\.type\s*===\s*['"]crate['"][\s\S]*?pixelRect/);assert.match(js,/pixelPolygon\(hazardPolygon\(h\)/);assert.doesNotMatch(js,/ctx\.(?:roundRect|rotate|arc|ellipse)\(/);});
test('touch and keyboard input are state aware and long press safe',()=>{const js=read('endless-runner/game.js'),css=read('endless-runner/style.css');assert.match(js,/pointerdown/);assert.match(js,/pointerup/);assert.match(js,/selectstart/);assert.match(js,/contextmenu/);assert.match(js,/event\.code\s*===\s*['"]Space/);assert.match(js,/state\s*!==\s*['"]playing['"]/);assert.match(css,/user-select:\s*none/);});
test('launcher and README include Endless Runner',()=>{assert.match(read('index.html'),/\/endless-runner\//);assert.match(read('README.md'),/\.\/endless-runner\//);});
