"use strict";
const test = require("node:test"),
  assert = require("node:assert/strict");
const { Game } = require("../shooter/rules");
test("Storm Carrier warns a bounded sweep with reachable escape, limited escorts, and two phase transitions", () => {
  const g = new Game();
  g.start();
  g.enterBoss("storm-carrier");
  g.phase = "boss";
  const b = g.boss;
  b.y = 110;
  b.cooldown = 0;
  g.updateBoss(0.01);
  assert.equal(b.attack.kind, "laser");
  assert.equal(g.hazards.length, 1);
  const h = g.hazards[0];
  assert.equal(h.active, false);
  assert.ok(h.warning >= 1.3);
  assert.ok((h.w / 2 + g.player.w / 2) / g.player.speed < h.warning);
  const x = h.x;
  g.player.x = 450;
  g.updateHazards(0.5);
  assert.equal(h.x, x);
  g.pulse();
  assert.equal(g.hazards.length, 1);
  g.updateHazards(1);
  assert.equal(h.active, true);
  const beam = h.beamX;
  g.updateHazards(0.2);
  assert.notEqual(h.beamX, beam);
  b.attack = null;
  b.cooldown = 0;
  b.hp=b.maxHp*.6; b.phase=1;
  b.pattern = 0;
  g.updateBoss(0.01);
  for (let i = 0; i < 120; i++) g.updateBoss(1 / 120);
  assert.ok(g.enemies.length > 0 && g.enemies.length <= 4);
  b.hp = b.maxHp * 0.6;
  g.updateBoss(0.01);
  assert.equal(b.phase, 2);
  b.hp = b.maxHp * 0.3;
  g.updateBoss(0.01);
  assert.equal(b.phase, 3);
  g.updateBoss(0.01);
  assert.equal(g.events.filter((e) => e.type === "boss-phase").length, 2);
});
test("Twin Core has independently destructible guns whose removal suppresses new attacks", () => {
  const g = new Game();
  g.start();
  g.enterBoss("twin-core");
  g.phase = "boss";
  const b = g.boss;
  b.y = 110;
  assert.ok(Array.isArray(b.turrets), "independent turrets exist");
  assert.equal(b.turrets.length, 2);
  const hp = b.hp;
  g.hitBoss(10);
  assert.equal(b.hp, hp);
  const left = b.turrets.find((t) => t.part === "left");
  g.hitBoss(left.hp, "left");
  assert.equal(left.hp, 0);
  for (let i = 0; i < 700; i++) g.updateBoss(1 / 120);
  assert.equal(g.enemyBullets.filter((s) => s.source === left.id).length, 0);
  assert.ok(g.enemyBullets.length > 0);
  const right = b.turrets.find((t) => t.part === "right");
  g.hitBoss(right.hp, "right");
  assert.equal(b.phase, 2);
  assert.equal(g.hitBoss(5), true);
  assert.equal(b.hp, hp - 5);
  assert.equal(g.events.filter((e) => e.type === "core-open").length, 1);
});
test("Iron Wing alternates a warned fan and fixed aim and transitions once at low health", () => {
  const g = new Game();
  g.start();
  g.enterBoss("iron-wing");
  g.phase = "boss";
  const b = g.boss;
  b.y = 110;
  b.cooldown = 0;
  g.updateBoss(0.01);
  assert.ok(b.attack, "attack warning exists");
  assert.equal(b.attack.kind, "fan");
  assert.ok(b.attack.timer >= 0.8);
  for (let i = 0; i < 120; i++) g.updateBoss(1 / 120);
  assert.equal(g.enemyBullets.length, 7);
  b.cooldown = 0; b.pattern=2;
  g.updateBoss(0.01);
  assert.equal(b.attack.kind, "aim");
  const lock = JSON.stringify(b.attack.target);
  g.player.x = 20;
  g.updateBoss(0.1);
  assert.equal(JSON.stringify(b.attack.target), lock);
  b.hp = b.maxHp * 0.4;
  g.updateBoss(0.01);
  assert.equal(b.phase, 2);
  g.updateBoss(0.01);
  assert.equal(g.events.filter((e) => e.type === "boss-phase").length, 1);
});
