(()=>{
'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,$=id=>document.getElementById(id);
const BIN={x:70,y:72,w:580,h:590},DANGER_Y=250,GRAVITY=1180,STIR_DURATION=1.35,TOP_CLEAR_DURATION=1.2,TOP_CLEAR_BONUS=3200;
const ui={score:$('score'),best:$('best'),energy:$('energy'),fruitCount:$('fruitCount'),next:$('nextFruit'),nextDot:$('nextDot'),overlay:$('overlay'),message:$('message'),detail:$('detail'),start:$('startButton'),pause:$('pauseButton'),stir:$('stirButton'),mobileStir:$('mobileStirButton'),drop:$('dropButton'),mode:$('modeButton'),route:$('route')};
const FRUITS=[
  {id:'kiwi',label:'KIWI',color:'#82be68',dark:'#578f58',light:'#d3ec9b',r:22,score:10},
  {id:'lemon',label:'LEMON',color:'#f3d15f',dark:'#d39b38',light:'#fff4a8',r:29,score:20},
  {id:'cherry',label:'CHERRY',color:'#dc6274',dark:'#9e405b',light:'#f5a1a8',r:36,score:40},
  {id:'peach',label:'PEACH',color:'#ef9d83',dark:'#c76b65',light:'#ffd0ab',r:44,score:80},
  {id:'orange',label:'ORANGE',color:'#f09a3e',dark:'#c66b29',light:'#ffd477',r:53,score:160},
  {id:'melon',label:'MELON',color:'#78b968',dark:'#4e9055',light:'#d8ee99',r:63,score:320},
  {id:'watermelon',label:'WATERMELON',color:'#5ca865',dark:'#3c7d50',light:'#e1f3a1',r:74,score:640}
];
let state='title',paused=false,fruits=[],particles=[],merges=[],aimX=BIN.x+BIN.w/2,nextLevel=0,dropCooldown=0,energy=100,score=0,best=Number(localStorage.getItem('melonLabBest')||0),dangerTimer=0,fluidPulse=0,clearPulse=0,clearX=BIN.x+BIN.w/2,clearY=BIN.y+BIN.h/2,clock=0,last=0,mode='semi-fluid';
function palette(){const s=getComputedStyle(document.documentElement),read=(n,f)=>s.getPropertyValue(n).trim()||f;return{paper:read('--paper','#fffaf1'),panel:read('--panel','#fffdf8'),ink:read('--ink','#3b302b'),muted:read('--muted','#8e7c70'),line:read('--line','#dfcfbc'),accent:read('--accent','#e97883'),mint:read('--mint','#a7d7b2'),blue:read('--blue','#a8cde3'),yellow:read('--yellow','#f8cb63'),coral:read('--coral','#ed7e78'),purple:read('--purple','#aa9bd8'),shadow:read('--shadow','#d8c5b3')}}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function aimBounds(level=nextLevel){const type=FRUITS[level];return{left:BIN.x+type.r+5,right:BIN.x+BIN.w-type.r-5}}function clampAimX(value,level=nextLevel){const bounds=aimBounds(level);return clamp(value,bounds.left,bounds.right)}function randomNext(){nextLevel=Math.random()<.72?Math.floor(Math.random()*3):Math.floor(Math.random()*4);aimX=clampAimX(aimX);updateNext();}
function updateNext(){ui.next.textContent=FRUITS[nextLevel].label;ui.nextDot.style.background=FRUITS[nextLevel].color;ui.nextDot.style.boxShadow=`inset 5px -4px 0 ${FRUITS[nextLevel].dark}`;}
function updateHud(){ui.score.textContent=String(score).padStart(6,'0');ui.best.textContent=String(best).padStart(6,'0');ui.energy.textContent=`${Math.floor(energy)}/100`;ui.fruitCount.textContent=String(fruits.filter(f=>!f.dead).length).padStart(2,'0');}
function showOverlay(title,detail,button){ui.message.textContent=title;ui.detail.textContent=detail;ui.start.textContent=button;ui.overlay.classList.remove('hidden')}
function hideOverlay(){ui.overlay.classList.add('hidden')}
function reset(){fruits=[];particles=[];merges=[];energy=100;score=0;dangerTimer=0;fluidPulse=0;clearPulse=0;aimX=BIN.x+BIN.w/2;dropCooldown=0;randomNext();state='playing';paused=false;ui.pause.textContent='PAUSE';hideOverlay();updateHud();last=performance.now()}
function start(){reset()}
function gameOver(){if(state==='over')return;state='over';paused=false;best=Math.max(best,score);localStorage.setItem('melonLabBest',String(best));updateHud();showOverlay('LAB OVERLOAD',`SCORE ${score} · BEST ${best}`,'TRY AGAIN')}
function togglePause(){if(state!=='playing')return;paused=!paused;ui.pause.textContent=paused?'RESUME':'PAUSE';if(paused)showOverlay('PAUSED','THE FRUIT WILL WAIT IN SUSPENSION','RESUME');else{hideOverlay();last=performance.now()}}
function spawnFruit(x=aimX,level=nextLevel){if(state!=='playing'||paused||dropCooldown>0)return;const type=FRUITS[level],safeX=clampAimX(x,level);aimX=safeX;const fruit={x:safeX,y:BIN.y+type.r+8,vx:0,vy:70,r:type.r,level,rot:Math.random()*6,age:0,settled:false,dead:false};fruits.push(fruit);dropCooldown=.48;randomNext();burst(fruit.x,fruit.y,type.light,5);}
function mergeFruits(a,b){if(a.dead||b.dead||a.level!==b.level)return false;const type=FRUITS[a.level],x=(a.x+b.x)/2,y=(a.y+b.y)/2;if(a.level===FRUITS.length-1){a.dead=true;b.dead=true;clearX=x;clearY=y;clearPulse=TOP_CLEAR_DURATION;score+=TOP_CLEAR_BONUS;burst(x,y,type.light,48);return true}const next=FRUITS[a.level+1];a.dead=true;b.dead=true;fruits.push({x,y,vx:(a.vx+b.vx)/2,vy:-260,r:next.r,level:a.level+1,rot:0,age:0,settled:false,dead:false});score+=next.score;burst(x,y,type.light,16);return true}
function stirPool(){if(state!=='playing'||paused||energy<30)return;energy-=30;fluidPulse=STIR_DURATION;const cx=BIN.x+BIN.w/2,cy=BIN.y+BIN.h*.62;for(const f of fruits)if(!f.dead){const dx=f.x-cx,dy=f.y-cy,dist=Math.hypot(dx,dy)||1;f.stirTime=STIR_DURATION;f.stirDirection=Math.random()<.5?-1:1;const kick=320+Math.random()*220;f.vx+=(-dy/dist)*f.stirDirection*kick;f.vy+=(dx/dist)*f.stirDirection*kick-160;f.settled=false;}burst(cx,cy,palette().accent,28);updateHud()}
function hitBoundaries(f){const left=BIN.x+f.r+5,right=BIN.x+BIN.w-f.r-5;if(f.x<left){f.x=left;f.vx=Math.abs(f.vx)*.45}if(f.x>right){f.x=right;f.vx=-Math.abs(f.vx)*.45}const floor=BIN.y+BIN.h-f.r-5;if(f.y>floor){f.y=floor;f.vy*=-.18;f.vx*=.82;if(Math.abs(f.vy)<20)f.settled=true}}
function physics(dt){for(const f of fruits){if(f.dead)continue;f.age+=dt;if(f.stirTime>0){f.stirTime=Math.max(0,f.stirTime-dt);const cx=BIN.x+BIN.w/2,cy=BIN.y+BIN.h*.62,dx=f.x-cx,dy=f.y-cy,dist=Math.hypot(dx,dy)||1,direction=f.stirDirection||1,force=520*(f.stirTime/STIR_DURATION);f.vx+=(-dy/dist)*direction*force*dt;f.vy+=(dx/dist)*direction*force*dt-120*dt;f.rot+=direction*dt*7;}f.vy=Math.min(950,f.vy+GRAVITY*dt);f.vx*=mode==='semi-fluid'?Math.pow(.992,dt*60):Math.pow(.96,dt*60);f.x+=f.vx*dt;f.y+=f.vy*dt;f.rot+=f.vx*dt*.006;hitBoundaries(f);if(f.settled&&f.y-f.r<DANGER_Y)f.warning=(f.warning||0)+dt;else f.warning=0;}
  for(let i=0;i<fruits.length;i++){const a=fruits[i];if(a.dead)continue;for(let j=i+1;j<fruits.length;j++){const b=fruits[j];if(b.dead)continue;let dx=b.x-a.x,dy=b.y-a.y,dist=Math.hypot(dx,dy)||.01,min=a.r+b.r;if(dist<min){const nx=dx/dist,ny=dy/dist,overlap=min-dist;if(a.level===b.level&&a.age>.08&&b.age>.08){if(!merges.some(pair=>pair.includes(a)&&pair.includes(b)))merges.push([a,b]);continue}a.x-=nx*overlap*.5;a.y-=ny*overlap*.5;b.x+=nx*overlap*.5;b.y+=ny*overlap*.5;const impulse=mode==='semi-fluid'?.22:.08;a.vx-=nx*overlap*impulse;b.vx+=nx*overlap*impulse;a.vy-=ny*overlap*impulse;b.vy+=ny*overlap*impulse;a.settled=false;b.settled=false;}}}
  for(const [a,b] of merges.splice(0)){mergeFruits(a,b)}fruits=fruits.filter(f=>!f.dead&&f.y<H+120);
  for(const f of fruits)if(f.warning>1.8){gameOver();break;}
}
function update(dt){if(state!=='playing'||paused)return;dropCooldown=Math.max(0,dropCooldown-dt);energy=Math.min(100,energy+dt*4.2);fluidPulse=Math.max(0,fluidPulse-dt);clearPulse=Math.max(0,clearPulse-dt);physics(dt);particles.forEach(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=300*dt;q.life-=dt});particles=particles.filter(q=>q.life>0);updateHud()}
function burst(x,y,color,count=8){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*180,vy:-50-Math.random()*180,life:.35+Math.random()*.5,r:2+Math.random()*3,color})}
function roundedRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath()}
function drawBackdrop(p){ctx.fillStyle=p.paper;ctx.fillRect(0,0,W,H);ctx.strokeStyle=p.line;ctx.globalAlpha=.55;ctx.lineWidth=1;for(let x=0;x<W;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.globalAlpha=1;ctx.fillStyle=p.mint+'55';ctx.beginPath();ctx.arc(110,100,90,0,Math.PI*2);ctx.fill();ctx.fillStyle=p.blue+'55';ctx.beginPath();ctx.arc(620,120,110,0,Math.PI*2);ctx.fill()}
function drawBin(p){ctx.save();const grad=ctx.createLinearGradient(0,BIN.y,0,BIN.y+BIN.h);grad.addColorStop(0,p.paper);grad.addColorStop(1,p.blue+'36');ctx.fillStyle=grad;roundedRect(BIN.x,BIN.y,BIN.w,BIN.h,24);ctx.fill();ctx.strokeStyle=p.ink;ctx.lineWidth=4;ctx.stroke();ctx.fillStyle=p.mint+'35';ctx.beginPath();ctx.moveTo(BIN.x+5,BIN.y+BIN.h-65);for(let x=BIN.x+5;x<=BIN.x+BIN.w-5;x+=30)ctx.quadraticCurveTo(x+15,BIN.y+BIN.h-75,x+30,BIN.y+BIN.h-65);ctx.lineTo(BIN.x+BIN.w-5,BIN.y+BIN.h);ctx.lineTo(BIN.x+5,BIN.y+BIN.h);ctx.closePath();ctx.fill();ctx.strokeStyle=p.accent;ctx.setLineDash([11,9]);ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(BIN.x+8,DANGER_Y);ctx.lineTo(BIN.x+BIN.w-8,DANGER_Y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=p.accent;ctx.font='900 11px ui-monospace, monospace';ctx.fillText('DANGER / 430',BIN.x+16,DANGER_Y-10);ctx.restore()}
function drawFruit(f,p){const t=FRUITS[f.level];ctx.save();ctx.translate(f.x,f.y);ctx.rotate(f.rot);ctx.strokeStyle=p.ink;ctx.lineWidth=2.5;ctx.lineJoin='round';if(t.id==='kiwi'){ctx.fillStyle=t.color;ctx.beginPath();ctx.arc(0,0,f.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=t.light;ctx.beginPath();ctx.arc(0,0,f.r*.58,0,Math.PI*2);ctx.fill();ctx.fillStyle=t.dark;for(let i=0;i<10;i++){const a=i*.63;ctx.beginPath();ctx.arc(Math.cos(a)*f.r*.38,Math.sin(a)*f.r*.38,2,0,Math.PI*2);ctx.fill();}}else if(t.id==='lemon'){ctx.fillStyle=t.color;ctx.beginPath();ctx.ellipse(0,0,f.r*1.15,f.r*.8,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle=t.light;ctx.beginPath();ctx.moveTo(-f.r*.55,-f.r*.15);ctx.lineTo(f.r*.55,f.r*.15);ctx.stroke();}else if(t.id==='cherry'){ctx.strokeStyle='#47794e';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-5,-f.r*.45);ctx.quadraticCurveTo(-12,-f.r-10,-4,-f.r-12);ctx.moveTo(5,-f.r*.45);ctx.quadraticCurveTo(10,-f.r-10,4,-f.r-12);ctx.stroke();ctx.fillStyle=t.color;ctx.beginPath();ctx.arc(-f.r*.36,3,f.r*.62,0,Math.PI*2);ctx.arc(f.r*.36,3,f.r*.62,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=t.light;ctx.beginPath();ctx.arc(-f.r*.55,-2,4,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(f.r*.18,-2,4,0,Math.PI*2);ctx.fill();}else if(t.id==='peach'){ctx.fillStyle=t.color;ctx.beginPath();ctx.arc(0,2,f.r*.92,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle=t.dark;ctx.beginPath();ctx.arc(0,2,f.r*.65,-.8,.8);ctx.stroke();ctx.fillStyle=t.light;ctx.beginPath();ctx.arc(-f.r*.35,-f.r*.35,f.r*.2,0,Math.PI*2);ctx.fill();}else if(t.id==='orange'){ctx.fillStyle=t.color;ctx.beginPath();ctx.arc(0,0,f.r*.93,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle=t.light;for(let i=0;i<9;i++){const a=i*Math.PI/4.5;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(Math.cos(a)*f.r*.72,Math.sin(a)*f.r*.72);ctx.stroke();}ctx.fillStyle=t.dark;ctx.beginPath();ctx.arc(0,-f.r*.82,4,0,Math.PI*2);ctx.fill();}else{ctx.fillStyle=t.color;ctx.beginPath();ctx.arc(0,0,f.r*.95,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle=t.dark;ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,f.r*.68,-.8,.8);ctx.stroke();ctx.strokeStyle=t.light;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,f.r*.48,2.3,4.0);ctx.stroke();ctx.fillStyle=t.light;ctx.beginPath();ctx.arc(-f.r*.35,-f.r*.38,5,0,Math.PI*2);ctx.fill();}ctx.restore()}
function drawStirEffect(p){if(fluidPulse<=0)return;const progress=clamp(1-fluidPulse/STIR_DURATION,0,1),fade=Math.sin(progress*Math.PI),cx=BIN.x+BIN.w/2,cy=BIN.y+BIN.h*.62,spin=clock*.004;ctx.save();ctx.globalAlpha=(.18+.32*fade);for(let i=0;i<4;i++){const radius=78+i*48+progress*18,direction=i%2?-1:1,start=spin*direction+i*.82;ctx.strokeStyle=i%2?p.blue:p.accent;ctx.lineWidth=3-i*.35;ctx.setLineDash([18,13]);ctx.lineDashOffset=-spin*direction*38;ctx.beginPath();ctx.arc(cx,cy,radius,start,start+Math.PI*1.35);ctx.stroke();ctx.setLineDash([]);for(let j=0;j<2;j++){const angle=start+j*2.1,ballX=cx+Math.cos(angle)*radius,ballY=cy+Math.sin(angle)*radius;ctx.fillStyle=j%2?p.yellow:p.accent;ctx.beginPath();ctx.arc(ballX,ballY,5-i*.45,0,Math.PI*2);ctx.fill();ctx.strokeStyle=p.ink;ctx.lineWidth=1;ctx.stroke();}}ctx.globalAlpha=.22+.2*fade;ctx.strokeStyle=p.accent;ctx.lineWidth=4;ctx.beginPath();ctx.arc(cx,cy,34+progress*92,spin,spin+Math.PI*1.8);ctx.stroke();ctx.restore()}
function drawClearEffect(p){if(clearPulse<=0)return;const progress=clamp(1-clearPulse/TOP_CLEAR_DURATION,0,1),pulse=Math.sin(progress*Math.PI),cx=clearX,cy=clearY;ctx.save();ctx.globalAlpha=.18+.62*pulse;ctx.strokeStyle=p.yellow;ctx.lineWidth=5;for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(cx,cy,28+progress*(72+i*34),0,Math.PI*2);ctx.stroke();}ctx.strokeStyle=p.accent;ctx.lineWidth=3;for(let i=0;i<12;i++){const angle=i*Math.PI/6,r1=34+progress*30,r2=r1+24+progress*26;ctx.beginPath();ctx.moveTo(cx+Math.cos(angle)*r1,cy+Math.sin(angle)*r1);ctx.lineTo(cx+Math.cos(angle)*r2,cy+Math.sin(angle)*r2);ctx.stroke();}ctx.globalAlpha=pulse;ctx.fillStyle=p.accent;ctx.font='950 20px ui-rounded, system-ui, sans-serif';ctx.textAlign='center';ctx.fillText('+'+TOP_CLEAR_BONUS,cx,cy-82-progress*22);ctx.textAlign='left';ctx.restore()}
function drawAim(p){ctx.save();ctx.strokeStyle=p.accent;ctx.globalAlpha=.55;ctx.setLineDash([7,8]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(aimX,BIN.y+8);ctx.lineTo(aimX,BIN.y+42);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=p.accent;ctx.beginPath();ctx.moveTo(aimX-7,BIN.y+42);ctx.lineTo(aimX+7,BIN.y+42);ctx.lineTo(aimX,BIN.y+53);ctx.closePath();ctx.fill();ctx.restore()}
function draw(){const p=palette();drawBackdrop(p);drawBin(p);drawStirEffect(p);drawClearEffect(p);drawAim(p);fruits.forEach(f=>drawFruit(f,p));particles.forEach(q=>{ctx.save();ctx.globalAlpha=Math.max(0,q.life*2);ctx.fillStyle=q.color;ctx.strokeStyle=p.ink;ctx.lineWidth=1;ctx.beginPath();ctx.arc(q.x,q.y,q.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()});if(paused){ctx.fillStyle=p.paper+'bb';ctx.fillRect(0,0,W,H)}}
function loop(time){const dt=Math.min(.033,(time-last)/1000||0);last=time;clock=time;update(dt);draw();requestAnimationFrame(loop)}
function pointFromEvent(event){const r=canvas.getBoundingClientRect();return clampAimX(BIN.x+(event.clientX-r.left)/r.width*W-BIN.x)}
canvas.addEventListener('pointermove',event=>{event.preventDefault();aimX=pointFromEvent(event)});canvas.addEventListener('pointerdown',event=>{event.preventDefault();if(state==='title'||state==='over')start();if(state==='playing'){aimX=pointFromEvent(event);spawnFruit(aimX)}});canvas.addEventListener('contextmenu',event=>event.preventDefault());
function bindDrop(button){button.addEventListener('click',()=>{if(state==='title'||state==='over')start();if(state==='playing')spawnFruit(aimX)})}bindDrop(ui.drop);ui.mobileStir.addEventListener('click',stirPool);ui.stir.addEventListener('click',stirPool);ui.mode.addEventListener('click',()=>{mode=mode==='semi-fluid'?'calm':'semi-fluid';ui.mode.innerHTML=mode==='semi-fluid'?'SEMI-FLUID <span>ON</span>':'CALM FLOW <span>ON</span>'});
addEventListener('keydown',event=>{const key=event.key.toLowerCase();if([' ','enter'].includes(key)){event.preventDefault();if(state==='title'||state==='over')start();else spawnFruit(aimX)}if(key==='p')togglePause();if(key==='arrowleft'||key==='a')aimX=clampAimX(aimX-34);if(key==='arrowright'||key==='d')aimX=clampAimX(aimX+34)});
ui.start.addEventListener('click',()=>{if(paused)togglePause();else start()});ui.pause.addEventListener('click',togglePause);document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing'&&!paused)togglePause()});document.addEventListener('themechange',()=>draw());
for(const item of FRUITS.slice(0,6)){const el=document.createElement('div');el.className='route-item';el.innerHTML=`<i class="route-fruit" aria-hidden="true"></i><span>${item.label}</span>`;ui.route.appendChild(el)}
updateNext();loadTitle();function loadTitle(){state='title';showOverlay('MELON LAB','DROP · COLLIDE · MERGE · DISCOVER','START EXPERIMENT');updateHud()}requestAnimationFrame(loop);
})();
