(()=>{'use strict';
const {levels,isLevelUnlocked,completionCount}=window.MinesweeperLevels;
const $=id=>document.getElementById(id),gridEl=$('grid'),levelList=$('levelList');
const COMPLETED_KEY='minesweeper-completed-v1',BEST_KEY='minesweeper-best-times-v1',LEVEL_KEY='minesweeper-level-v1';
const readArray=(key,fallback)=>{try{const value=JSON.parse(localStorage.getItem(key));return Array.isArray(value)?value:fallback}catch{return fallback}};
let completed=readArray(COMPLETED_KEY,Array(20).fill(false)).slice(0,20);while(completed.length<20)completed.push(false);
let bestTimes=readArray(BEST_KEY,Array(20).fill(0)).slice(0,20);while(bestTimes.length<20)bestTimes.push(0);
let levelIndex=Math.max(0,Math.min(levels.length-1,Number(localStorage.getItem(LEVEL_KEY))||0));while(levelIndex>0&&!isLevelUnlocked(levelIndex,completed))levelIndex--;
let rows=9,cols=9,mineCount=10,cells=[],started=false,over=false,flags=0,startTime=0,timer,overlayAction='start';
function saveProgress(){localStorage.setItem(COMPLETED_KEY,JSON.stringify(completed));localStorage.setItem(BEST_KEY,JSON.stringify(bestTimes));localStorage.setItem(LEVEL_KEY,String(levelIndex))}
function pad(value,width=3){return String(value).padStart(width,'0')}
function currentLevel(){return levels[levelIndex]}
function updateMeta(){const level=currentLevel();$('levelLabel').textContent=pad(level.id,2)+' / '+levels.length;$('mines').textContent=pad(mineCount-flags);$('progress').textContent=completionCount(completed)+' / '+levels.length;$('levelsProgress').textContent=completionCount(completed)+' / '+levels.length+' CLEARED';const best=bestTimes[levelIndex];$('best').textContent=best?pad(best):'---';gridEl.style.setProperty('--cols',String(cols))}
function index(r,c){return r*cols+c}
function around(r,c){const result=[];for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++)if(x||y){const yy=r+y,xx=c+x;if(yy>=0&&yy<rows&&xx>=0&&xx<cols)result.push(index(yy,xx))}return result}
function setup(){const level=currentLevel();rows=level.rows;cols=level.cols;mineCount=level.mines;cells=Array.from({length:rows*cols},(_,i)=>({i,mine:false,n:0,open:false,flag:false,long:false}));flags=0;over=false;started=false;clearInterval(timer);$('status').textContent='READY';updateMeta();render()}
function placeMines(safeIndex){const safe=new Set([safeIndex,...around(Math.floor(safeIndex/cols),safeIndex%cols)]),available=cells.map(cell=>cell.i).filter(i=>!safe.has(i));for(let count=0;count<mineCount;count++){const pick=Math.floor(Math.random()*available.length),i=available.splice(pick,1)[0];cells[i].mine=true}cells.forEach(cell=>cell.n=around(Math.floor(cell.i/cols),cell.i%cols).filter(i=>cells[i].mine).length)}
function render(){gridEl.innerHTML='';cells.forEach(cell=>{const button=document.createElement('button');button.type='button';button.className='cell '+(cell.open?'open':'closed')+(cell.flag?' flag':'')+(cell.mine&&cell.open?' mine':'');button.textContent=cell.flag?'⚑':cell.open?(cell.mine?'✹':cell.n||''):'';button.setAttribute('aria-label',cell.open?'Open cell':'Closed cell');if(cell.open&&!cell.mine&&cell.n)button.classList.add('n'+cell.n);button.oncontextmenu=event=>{event.preventDefault();flag(cell.i)};button.ondragstart=event=>event.preventDefault();button.onclick=()=>{if(!cell.long)open(cell.i);cell.long=false};let pressTimer,pressStart;const cancelPress=()=>{clearTimeout(pressTimer);pressTimer=null};button.onpointerdown=event=>{event.preventDefault();if(event.pointerType==='touch'){cell.long=false;pressStart={x:event.clientX,y:event.clientY};if(button.setPointerCapture)try{button.setPointerCapture(event.pointerId)}catch(_){};pressTimer=setTimeout(()=>{cell.long=true;flag(cell.i)},500)}};button.onpointermove=event=>{if(pressStart&&Math.hypot(event.clientX-pressStart.x,event.clientY-pressStart.y)>10){cancelPress();pressStart=null}};button.onpointerup=event=>{event.preventDefault();cancelPress();pressStart=null;if(button.releasePointerCapture&&button.hasPointerCapture&&button.hasPointerCapture(event.pointerId))button.releasePointerCapture(event.pointerId)};button.onpointercancel=event=>{event.preventDefault();cancelPress();pressStart=null};button.onpointerleave=()=>{cancelPress();pressStart=null};gridEl.appendChild(button)})}
function beginLevel(){setup();$('time').textContent='000';$('message').classList.add('hide');$('status').textContent='TAP A PATCH'}
gridEl.addEventListener('selectstart',event=>event.preventDefault());gridEl.addEventListener('contextmenu',event=>event.preventDefault());
function start(safeIndex){if(started)return;placeMines(safeIndex);started=true;startTime=Date.now();$('status').textContent='PLAYING';$('message').classList.add('hide');timer=setInterval(()=>{$('time').textContent=pad(Math.min(999,Math.floor((Date.now()-startTime)/1000)))},1000)}
function flag(i){if(over||cells[i].open)return;cells[i].flag=!cells[i].flag;flags+=cells[i].flag?1:-1;updateMeta();render()}
function finishWin(){over=true;clearInterval(timer);cells.filter(cell=>cell.mine).forEach(cell=>cell.flag=true);flags=mineCount;const seconds=+$('time').textContent;if(!bestTimes[levelIndex]||seconds<bestTimes[levelIndex])bestTimes[levelIndex]=seconds;completed[levelIndex]=true;saveProgress();updateMeta();$('status').textContent='CLEAR';const next=levelIndex<levels.length-1;show('CLEARED','LEVEL '+pad(currentLevel().id,2)+' · TIME '+pad(seconds),next?'NEXT LEVEL':'PLAY AGAIN',next?'next':'replay')}
function open(i){if(over||cells[i].flag)return;if(!started)start(i);const cell=cells[i];if(cell.open)return;if(cell.mine){cell.open=true;over=true;cells.forEach(item=>{if(item.mine)item.open=true});clearInterval(timer);$('status').textContent='BOOM';show('GARDEN BOOM','YOU FOUND A BAD MUSHROOM','PLAY AGAIN','replay');render();return}const stack=[i],seen=new Set();while(stack.length){const current=stack.pop();if(seen.has(current)||cells[current].flag)continue;seen.add(current);cells[current].open=true;if(!cells[current].n)stack.push(...around(Math.floor(current/cols),current%cols).filter(next=>!cells[next].mine&&!seen.has(next)))}if(cells.every(cell=>cell.mine||cell.open))finishWin();updateMeta();render()}
function show(title,hint,button,action){$('title').textContent=title;$('hint').textContent=hint;$('start').textContent=button;overlayAction=action;$('message').classList.remove('hide')}
function renderLevelList(){levelList.innerHTML='';let difficulty='';levels.forEach((level,index)=>{if(level.difficulty!==difficulty){difficulty=level.difficulty;const heading=document.createElement('div');heading.className='difficulty-heading';heading.textContent=difficulty;levelList.appendChild(heading)}const button=document.createElement('button');const unlocked=isLevelUnlocked(index,completed);button.type='button';button.className='level-button '+(unlocked?'':'locked')+(completed[index]?' complete':'')+(index===levelIndex?' selected':'');button.disabled=!unlocked;button.innerHTML='<span>'+pad(level.id,2)+(completed[index]?' ✓':'')+'</span><small>'+level.rows+'×'+level.cols+' · '+level.mines+'M'+(bestTimes[index]?' · '+pad(bestTimes[index]):'')+'</small>';button.onclick=()=>selectLevel(index);levelList.appendChild(button)})}
function selectLevel(index){if(!isLevelUnlocked(index,completed))return;levelIndex=index;saveProgress();$('levelsPanel').classList.add('hide');beginLevel()}
function openLevels(){renderLevelList();$('levelsPanel').classList.remove('hide')}
$('start').onclick=()=>{if(overlayAction==='next'){selectLevel(levelIndex+1)}else beginLevel()};$('new').onclick=beginLevel;$('levels').onclick=openLevels;$('closeLevels').onclick=()=>$('levelsPanel').classList.add('hide');
setup();renderLevelList();show('MOLE PATROL','LEVEL 01 · TAP A PATCH TO START','START DIGGING','start')})();
