(()=>{'use strict';
const R=9,C=9,M=10,$=id=>document.getElementById(id),gridEl=$('grid');
let cells=[],started=false,over=false,flags=0,startTime=0,timer,best=+localStorage.getItem('minesweeper-best')||0;
$('best').textContent=String(best).padStart(3,'0');
function index(r,c){return r*C+c}
function around(r,c){const result=[];for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++)if(x||y){const yy=r+y,xx=c+x;if(yy>=0&&yy<R&&xx>=0&&xx<C)result.push(index(yy,xx))}return result}
function setup(){cells=Array.from({length:R*C},(_,i)=>({i,mine:false,n:0,open:false,flag:false,long:false}));flags=0;over=false;started=false;clearInterval(timer);$('mines').textContent=String(M).padStart(3,'0');$('time').textContent='000';$('status').textContent='READY';render()}
function placeMines(safeIndex){const safe=new Set([safeIndex,...around(Math.floor(safeIndex/C),safeIndex%C)]),available=cells.map(cell=>cell.i).filter(i=>!safe.has(i));for(let count=0;count<M;count++){const pick=Math.floor(Math.random()*available.length),i=available.splice(pick,1)[0];cells[i].mine=true}cells.forEach(cell=>cell.n=around(Math.floor(cell.i/C),cell.i%C).filter(i=>cells[i].mine).length)}
function render(){gridEl.innerHTML='';cells.forEach(cell=>{const button=document.createElement('button');button.className='cell '+(cell.open?'open':'closed')+(cell.flag?' flag':'')+(cell.mine&&cell.open?' mine':'');button.textContent=cell.flag?'⚑':cell.open?(cell.mine?'✹':cell.n||''):'';if(cell.open&&!cell.mine&&cell.n)button.classList.add('n'+cell.n);button.oncontextmenu=event=>{event.preventDefault();flag(cell.i)};button.onclick=()=>{if(!cell.long)open(cell.i);cell.long=false};let pressTimer;button.onpointerdown=event=>{if(event.pointerType==='touch'){cell.long=false;pressTimer=setTimeout(()=>{cell.long=true;flag(cell.i)},500)}};button.onpointerup=event=>{if(event.pointerType==='touch')clearTimeout(pressTimer)};button.onpointercancel=()=>clearTimeout(pressTimer);button.onpointerleave=()=>clearTimeout(pressTimer);gridEl.appendChild(button)})}
function start(safeIndex){if(started)return;placeMines(safeIndex);started=true;startTime=Date.now();$('status').textContent='PLAYING';$('message').classList.add('hide');timer=setInterval(()=>{$('time').textContent=String(Math.min(999,Math.floor((Date.now()-startTime)/1000))).padStart(3,'0')},1000)}
function flag(i){if(over||cells[i].open)return;cells[i].flag=!cells[i].flag;flags+=cells[i].flag?1:-1;$('mines').textContent=String(M-flags).padStart(3,'0');render()}
function finishWin(){over=true;clearInterval(timer);const seconds=+$('time').textContent;if(!best||seconds<best){best=seconds;localStorage.setItem('minesweeper-best',String(best));$('best').textContent=String(best).padStart(3,'0')}$('status').textContent='CLEAR';show('CLEARED','TIME '+String(seconds).padStart(3,'0'),'PLAY AGAIN')}
function open(i){if(over||cells[i].flag)return;if(!started)start(i);const cell=cells[i];if(cell.open)return;if(cell.mine){cell.open=true;over=true;cells.forEach(item=>{if(item.mine)item.open=true});clearInterval(timer);$('status').textContent='BOOM';show('GAME OVER','YOU HIT A MINE','PLAY AGAIN');render();return}const stack=[i],seen=new Set();while(stack.length){const current=stack.pop();if(seen.has(current)||cells[current].flag)continue;seen.add(current);cells[current].open=true;if(!cells[current].n)stack.push(...around(Math.floor(current/C),current%C).filter(next=>!cells[next].mine&&!seen.has(next)))}if(cells.every(cell=>cell.mine||cell.open))finishWin();render()}
function show(title,hint,button){$('title').textContent=title;$('hint').textContent=hint;$('start').textContent=button;$('message').classList.remove('hide')}
$('start').onclick=()=>{setup();$('message').classList.add('hide');$('status').textContent='TAP A CELL'};
$('new').onclick=()=>{setup();$('message').classList.add('hide');$('status').textContent='TAP A CELL'};
setup();show('MINESWEEPER','TAP A CELL TO START','START')})();
