(function (root, factory) {
  "use strict";
  const content = factory();
  if (typeof module === "object") module.exports = content;
  else root.SkyPatrolContent = content;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";
  const ENEMIES = {
    scout: {
      hp: 2,
      score: 30,
      w: 26,
      h: 28,
      speed: 66,
      shape: "triangle",
      name: ["侦察机", "SCOUT"],
    },
    formation: {
      hp: 2,
      score: 40,
      w: 28,
      h: 26,
      speed: 56,
      shape: "wings",
      name: ["编队机", "FORMATION"],
    },
    diver: {
      hp: 3,
      score: 65,
      w: 24,
      h: 42,
      speed: 58,
      shape: "dart",
      name: ["俯冲机", "DIVER"],
    },
    heavy: {
      hp: 7,
      score: 100,
      w: 44,
      h: 36,
      speed: 38,
      shape: "shield",
      name: ["重装机", "ARMORED"],
    },
    sniper: {
      hp: 3,
      score: 70,
      w: 24,
      h: 44,
      speed: 54,
      shape: "barrel",
      name: ["狙击机", "SNIPER"],
    },
    bomber: {
      hp: 4,
      score: 80,
      w: 46,
      h: 30,
      speed: 48,
      shape: "pods",
      name: ["投弹机", "BOMBER"],
    },
    interceptor: { hp:3, score:80, w:42, h:24, speed:68, shape:"chevron", name:["拦截机","INTERCEPTOR"] },
    minelayer: { hp:4, score:95, w:34, h:34, speed:52, shape:"diamond", name:["布雷机","MINELAYER"] },
    support: { hp:4, score:120, w:40, h:32, speed:46, shape:"relay", name:["支援机","SUPPORT"] },
  };
  // Profiles share eight mechanics; variants change choices, not just HP/color.
  const BOSSES = {
    outpost: { hp: 130, w: 116, h: 64, kind: "fan", name: ["前哨指挥机", "OUTPOST"], patterns: ["fan", "aim"], challenge: ["fan", "burst", "aim"], later:["gap","burst","fan"], phaseCount:2, motion:"patrol", tip: "fan" },
    spear: { hp: 160, w: 106, h: 82, kind: "dash", name: ["尖锋突击舰", "SPEAR"], patterns: ["dash","burst"], challenge: ["dash","fan","burst"], tip: "dash", later: ["doubleDash","cross","gap"], phaseCount: 2, motion: "zigzag" },
    "iron-wing": { hp: 360, w: 160, h: 74, kind: "fan", name: ["铁翼巡航舰", "IRON WING"], patterns: ["fan","cross","aim"], later: ["doubleFan","gap","burst"], challenge: ["gap","cross","fan"], tip: "gap", final: ["rotatingGap","lockChain","doubleFan"], phaseCount: 3, motion: "sweep" },
    fortress: { hp: 190, w: 146, h: 80, kind: "bomb", name: ["轰炸堡垒", "BOMB FORTRESS"], patterns: ["bomb","fan","burst"], challenge: ["bomb","cross","fan"], tip: "bomb", later: ["chainBomb","cross","fan"], phaseCount: 2, motion: "hold" },
    hunter: { hp: 180, w: 120, h: 76, kind: "aim", name: ["锁定猎手", "LOCK HUNTER"], patterns: ["aim","burst","cross"], challenge: ["burst","lockChain","cross"], tip: "aim", later: ["lockChain","cross","gap"], phaseCount: 2, motion: "stalk" },
    "twin-core": { hp: 260, turretHp: 110, w: 168, h: 88, kind: "parts", name: ["双核护卫舰", "TWIN CORE"], patterns: ["gap","burst","cross"], challenge: ["gap","cross","burst"], tip: "parts", later: ["gap","cross","burst"], final: ["doubleFan","cross","gap"], phaseCount: 3, motion: "orbit" },
    swarm: { hp: 200, w: 148, h: 78, kind: "summon", name: ["蜂群指挥舰", "SWARM COMMAND"], patterns: ["summonFormation","fan","aim"], challenge: ["summonFormation","cross","burst"], tip: "summon", later: ["summonFormation","cross","gap"], phaseCount: 2, motion: "patrol", escortPressure: true },
    sentinel: { hp: 220, w: 126, h: 86, kind: "laser", name: ["光束哨站", "BEAM SENTINEL"], patterns: ["laser","cross","aim"], challenge: ["laser","burst","cross"], tip: "laser", later: ["reverseLaser","burst","laser"], phaseCount: 2, motion: "hold" },
    "storm-carrier": { hp: 520, w: 190, h: 98, kind: "combined", name: ["风暴母舰", "STORM CARRIER"], patterns: ["laser","aim","gap"], later: ["summonFormation","cross","burst"], final: ["doubleFan","rotatingGap","lockChain"], challenge: ["laser","cross","aim"], tip: "combined", phaseCount: 3, motion: "orbit" },
    "iron-mk2": { hp: 250, w: 160, h: 74, kind: "fan", name: ["铁翼改型", "IRON MK II"], patterns: ["rotatingGap","lockChain","cross"], challenge: ["rotatingGap","burst","doubleFan"], tip: "doubleFan", later: ["doubleFan","rotatingGap","burst"], phaseCount: 2, motion: "zigzag" },
    "twin-armored": { hp: 150, turretHp: 75, w: 174, h: 90, kind: "parts", alternating: true, name: ["双核重装舰", "ARMORED TWINS"], patterns: ["gap","cross","burst"], challenge: ["doubleFan","cross","burst"], tip: "alternating", later: ["cross","rotatingGap","burst"], phaseCount: 2, motion: "sweep" },
    blockade: { hp: 340, w: 184, h: 94, kind: "combined", name: ["封锁旗舰", "BLOCKADE"], patterns: ["bombLanes","fan","aim"], later: ["mineLanes","burst","gap"], challenge: ["bombLanes","cross","doubleFan"], tip: "blockade", final: ["reverseLaser","cross","chainBomb"], phaseCount: 3, motion: "hold" },
    "swarm-carrier": { hp: 270, w: 172, h: 88, kind: "summon", name: ["蜂群母舰", "SWARM CARRIER"], patterns: ["summonSupport","gap","aim"], challenge: ["summonSupport","summonFlank","burst"], tip: "summon", later: ["summonFlank","cross","rotatingGap"], phaseCount: 2, motion: "orbit", escortPressure: true },
    aurora: { hp: 140, turretHp: 80, w: 176, h: 92, kind: "parts", partLaser: true, name: ["极光双核舰", "AURORA TWINS"], patterns: ["gap","cross","aim"], challenge: ["doubleFan","burst","cross"], tip: "laserParts", later: ["rotatingGap","burst","cross"], phaseCount: 2, motion: "stalk", alternating: true },
    skybreaker: { hp: 380, turretHp: 60, w: 194, h: 100, kind: "combined", stagedParts: true, name: ["天幕总旗舰", "SKYBREAKER"], patterns: ["fan","lockChain","cross"], final: ["rotatingGap","laser","summonFlank","reverseLaser","doubleFan"], challenge: ["gap","cross","burst"], tip: "combined", phaseCount: 3, motion: "sweep" },
  };
  const MODES = {
    normal: { hpScale: 1, fireScale: 1, speedScale: 1 },
    challenge: { hpScale: 1.15, fireScale: 1.28, speedScale: 1.08 },
  };
  // Every wave has an authored roster and a distinct tactical role.
  const STAGES = [
    {"id":1,"name":["初次巡航","FIRST PATROL"],"boss":"outpost","chapter":1,"chapterEnd":false,"waves":[{"tactic":"probe","minSeconds":9,"groups":[{"type":"scout","count":3,"at":0.0,"x":100,"elite":false,"key":false},{"type":"formation","count":4,"at":2.0,"x":240,"elite":false,"key":false},{"type":"scout","count":4,"at":4.0,"x":380,"elite":false,"key":false}]},{"tactic":"crossfire","minSeconds":9,"groups":[{"type":"formation","count":4,"at":0.0,"x":240,"elite":false,"key":false,"supply":true},{"type":"scout","count":3,"at":2.12,"x":380,"elite":false,"key":false},{"type":"scout","count":3,"at":4.24,"x":100,"elite":false,"key":false}]},{"tactic":"priority","minSeconds":9,"groups":[{"type":"scout","count":4,"at":0.0,"x":380,"elite":false,"key":false},{"type":"formation","count":4,"at":2.0,"x":100,"elite":false,"key":false},{"type":"scout","count":3,"at":4.0,"x":240,"elite":false,"key":false}]},{"tactic":"squeeze","minSeconds":9,"groups":[{"type":"formation","count":4,"at":0.0,"x":100,"elite":false,"key":false},{"type":"scout","count":4,"at":2.12,"x":240,"elite":false,"key":false},{"type":"formation","count":4,"at":4.24,"x":380,"elite":false,"key":false}]}]},
    {"id":2,"name":["突袭航线","AMBUSH ROUTE"],"boss":"spear","chapter":1,"chapterEnd":false,"waves":[{"tactic":"probe","minSeconds":9,"groups":[{"type":"scout","count":3,"at":0.0,"x":100,"elite":false,"key":false},{"type":"formation","count":4,"at":2.0,"x":240,"elite":false,"key":false},{"type":"diver","count":2,"at":4.0,"x":380,"elite":false,"key":false},{"type":"scout","count":3,"at":6.0,"x":100,"elite":false,"key":false}]},{"tactic":"crossfire","minSeconds":9,"groups":[{"type":"formation","count":4,"at":0.0,"x":240,"elite":false,"key":false},{"type":"heavy","count":1,"at":2.12,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":4.24,"x":100,"elite":false,"key":false},{"type":"diver","count":3,"at":6.36,"x":240,"elite":false,"key":false}]},{"tactic":"priority","minSeconds":9,"groups":[{"type":"diver","count":2,"at":0.0,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":2.0,"x":100,"elite":false,"key":false},{"type":"formation","count":4,"at":4.0,"x":240,"elite":false,"key":false},{"type":"scout","count":2,"at":6.0,"x":380,"elite":false,"key":false}]},{"tactic":"squeeze","minSeconds":9,"groups":[{"type":"heavy","count":1,"at":0.0,"x":100,"elite":false,"key":false},{"type":"diver","count":3,"at":2.12,"x":240,"elite":false,"key":false},{"type":"formation","count":4,"at":4.24,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":6.36,"x":100,"elite":false,"key":false}]}]},
    {"id":3,"name":["铁翼封锁","IRON BLOCKADE"],"boss":"iron-wing","chapter":1,"chapterEnd":true,"waves":[{"tactic":"probe","minSeconds":9,"groups":[{"type":"formation","count":4,"at":0.0,"x":100,"elite":false,"key":false},{"type":"diver","count":2,"at":2.0,"x":240,"elite":false,"key":false},{"type":"scout","count":4,"at":4.0,"x":380,"elite":false,"key":false},{"type":"scout","count":3,"at":6.0,"x":100,"elite":false,"key":false}]},{"tactic":"crossfire","minSeconds":10.28,"groups":[{"type":"heavy","count":1,"at":0.0,"x":240,"elite":false,"key":false},{"type":"formation","count":4,"at":2.12,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":4.24,"x":100,"elite":false,"key":false},{"type":"diver","count":2,"at":6.36,"x":240,"elite":false,"key":false},{"type":"scout","count":2,"at":8.48,"x":380,"elite":false,"key":false}]}]},
    {"id":4,"name":["危险空域","DANGER ZONE"],"boss":"fortress","chapter":2,"chapterEnd":false,"waves":[{"tactic":"probe","minSeconds":5.4,"groups":[{"type":"interceptor","count":1,"at":0.0,"x":100,"elite":false,"key":false},{"type":"scout","count":4,"at":1.2,"x":240,"elite":false,"key":false},{"type":"formation","count":4,"at":2.4,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":3.6,"x":100,"elite":false,"key":false}]},{"tactic":"crossfire","minSeconds":7.0,"groups":[{"type":"bomber","count":1,"at":0.0,"x":240,"elite":false,"key":true},{"type":"formation","count":4,"at":1.3,"x":380,"elite":false,"key":false},{"type":"scout","count":3,"at":2.6,"x":100,"elite":false,"key":false},{"type":"diver","count":2,"at":3.9,"x":240,"elite":false,"key":false},{"type":"scout","count":3,"at":5.2,"x":380,"elite":false,"key":false}]},{"tactic":"priority","minSeconds":5.4,"groups":[{"type":"scout","count":4,"at":0.0,"x":380,"elite":false,"key":false},{"type":"interceptor","count":2,"at":1.2,"x":100,"elite":false,"key":false},{"type":"formation","count":4,"at":2.4,"x":240,"elite":false,"key":false,"supply":true},{"type":"scout","count":3,"at":3.6,"x":380,"elite":false,"key":false}]},{"tactic":"squeeze","minSeconds":7.0,"groups":[{"type":"formation","count":4,"at":0.0,"x":100,"elite":false,"key":false},{"type":"bomber","count":1,"at":1.3,"x":240,"elite":false,"key":true},{"type":"interceptor","count":1,"at":2.6,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":3.9,"x":100,"elite":false,"key":false},{"type":"scout","count":3,"at":5.2,"x":240,"elite":false,"key":false}]}]},
    {"id":5,"name":["瞄准警戒","CROSSHAIRS"],"boss":"hunter","chapter":2,"chapterEnd":false,"waves":[{"tactic":"probe","minSeconds":6.6,"groups":[{"type":"sniper","count":1,"at":0.0,"x":100,"elite":false,"key":false},{"type":"formation","count":4,"at":1.2,"x":240,"elite":false,"key":false},{"type":"scout","count":4,"at":2.4,"x":380,"elite":false,"key":false},{"type":"diver","count":2,"at":3.6,"x":100,"elite":false,"key":false},{"type":"scout","count":3,"at":4.8,"x":240,"elite":false,"key":false}]},{"tactic":"crossfire","minSeconds":7.0,"groups":[{"type":"interceptor","count":2,"at":0.0,"x":240,"elite":false,"key":false},{"type":"sniper","count":1,"at":1.3,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":2.6,"x":100,"elite":false,"key":false},{"type":"formation","count":4,"at":3.9,"x":240,"elite":false,"key":false},{"type":"scout","count":3,"at":5.2,"x":380,"elite":false,"key":false}]},{"tactic":"priority","minSeconds":6.6,"groups":[{"type":"diver","count":2,"at":0.0,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":1.2,"x":100,"elite":false,"key":false},{"type":"sniper","count":2,"at":2.4,"x":240,"elite":false,"key":false},{"type":"formation","count":4,"at":3.6,"x":380,"elite":false,"key":false},{"type":"scout","count":2,"at":4.8,"x":100,"elite":false,"key":false}]},{"tactic":"squeeze","minSeconds":8.3,"groups":[{"type":"formation","count":4,"at":0.0,"x":100,"elite":false,"key":false},{"type":"interceptor","count":1,"at":1.3,"x":240,"elite":false,"key":false},{"type":"bomber","count":1,"at":2.6,"x":380,"elite":false,"key":true},{"type":"sniper","count":1,"at":3.9,"x":100,"elite":false,"key":false},{"type":"scout","count":4,"at":5.2,"x":240,"elite":false,"key":false},{"type":"scout","count":3,"at":6.5,"x":380,"elite":false,"key":false}]}]},
    {"id":6,"name":["双核防线","TWIN DEFENSE"],"boss":"twin-core","chapter":2,"chapterEnd":true,"waves":[{"tactic":"probe","minSeconds":6.6,"groups":[{"type":"heavy","count":1,"at":0.0,"x":100,"elite":false,"key":false},{"type":"formation","count":4,"at":1.2,"x":240,"elite":false,"key":false},{"type":"diver","count":2,"at":2.4,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":3.6,"x":100,"elite":false,"key":false},{"type":"scout","count":4,"at":4.8,"x":240,"elite":false,"key":false}]},{"tactic":"crossfire","minSeconds":7.0,"groups":[{"type":"sniper","count":1,"at":0.0,"x":240,"elite":false,"key":false},{"type":"interceptor","count":1,"at":1.3,"x":380,"elite":false,"key":false},{"type":"formation","count":4,"at":2.6,"x":100,"elite":false,"key":false},{"type":"scout","count":4,"at":3.9,"x":240,"elite":false,"key":false},{"type":"scout","count":5,"at":5.2,"x":380,"elite":false,"key":false}]}]},
    {"id":7,"name":["护卫集群","ESCORT FLEET"],"boss":"swarm","chapter":3,"chapterEnd":false,"waves":[{"tactic":"probe","minSeconds":5.4,"groups":[{"type":"minelayer","count":1,"at":0.0,"x":100,"elite":false,"key":true},{"type":"scout","count":4,"at":1.2,"x":240,"elite":false,"key":false},{"type":"formation","count":4,"at":2.4,"x":380,"elite":false,"key":false},{"type":"scout","count":5,"at":3.6,"x":100,"elite":false,"key":false}]},{"tactic":"crossfire","minSeconds":7.0,"groups":[{"type":"heavy","count":1,"at":0.0,"x":240,"elite":false,"key":false},{"type":"sniper","count":1,"at":1.3,"x":380,"elite":true,"key":false},{"type":"formation","count":4,"at":2.6,"x":100,"elite":false,"key":false},{"type":"scout","count":4,"at":3.9,"x":240,"elite":false,"key":false},{"type":"scout","count":4,"at":5.2,"x":380,"elite":false,"key":false}]},{"tactic":"priority","minSeconds":6.6,"groups":[{"type":"formation","count":4,"at":0.0,"x":380,"elite":false,"key":false,"supply":true},{"type":"minelayer","count":1,"at":1.2,"x":100,"elite":false,"key":true},{"type":"diver","count":2,"at":2.4,"x":240,"elite":true,"key":false},{"type":"scout","count":4,"at":3.6,"x":380,"elite":false,"key":false},{"type":"scout","count":3,"at":4.8,"x":100,"elite":false,"key":false}]},{"tactic":"squeeze","minSeconds":8.3,"groups":[{"type":"interceptor","count":2,"at":0.0,"x":100,"elite":false,"key":false},{"type":"sniper","count":1,"at":1.3,"x":240,"elite":true,"key":false},{"type":"minelayer","count":1,"at":2.6,"x":380,"elite":false,"key":true},{"type":"formation","count":4,"at":3.9,"x":100,"elite":false,"key":false},{"type":"scout","count":3,"at":5.2,"x":240,"elite":false,"key":false},{"type":"scout","count":3,"at":6.5,"x":380,"elite":false,"key":false}]}]},
    {"id":8,"name":["风暴前沿","STORM FRONT"],"boss":"sentinel","chapter":3,"chapterEnd":false,"waves":[{"tactic":"probe","minSeconds":6.6,"groups":[{"type":"bomber","count":1,"at":0.0,"x":100,"elite":false,"key":true},{"type":"diver","count":2,"at":1.2,"x":240,"elite":false,"key":false},{"type":"formation","count":4,"at":2.4,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":3.6,"x":100,"elite":false,"key":false},{"type":"scout","count":4,"at":4.8,"x":240,"elite":false,"key":false}]},{"tactic":"crossfire","minSeconds":7.0,"groups":[{"type":"minelayer","count":1,"at":0.0,"x":240,"elite":false,"key":true},{"type":"interceptor","count":2,"at":1.3,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":2.6,"x":100,"elite":false,"key":false},{"type":"formation","count":4,"at":3.9,"x":240,"elite":false,"key":false},{"type":"scout","count":4,"at":5.2,"x":380,"elite":false,"key":false}]},{"tactic":"priority","minSeconds":7.8,"groups":[{"type":"sniper","count":1,"at":0.0,"x":380,"elite":true,"key":false},{"type":"heavy","count":1,"at":1.2,"x":100,"elite":false,"key":false},{"type":"formation","count":4,"at":2.4,"x":240,"elite":false,"key":false},{"type":"diver","count":2,"at":3.6,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":4.8,"x":100,"elite":false,"key":false},{"type":"scout","count":3,"at":6.0,"x":240,"elite":false,"key":false}]},{"tactic":"squeeze","minSeconds":8.3,"groups":[{"type":"interceptor","count":2,"at":0.0,"x":100,"elite":false,"key":false},{"type":"bomber","count":1,"at":1.3,"x":240,"elite":false,"key":true},{"type":"minelayer","count":1,"at":2.6,"x":380,"elite":false,"key":true},{"type":"formation","count":4,"at":3.9,"x":100,"elite":false,"key":false},{"type":"scout","count":4,"at":5.2,"x":240,"elite":false,"key":false},{"type":"scout","count":3,"at":6.5,"x":380,"elite":false,"key":false}]}]},
    {"id":9,"name":["风暴屏障","STORM BARRIER"],"boss":"storm-carrier","chapter":3,"chapterEnd":true,"waves":[{"tactic":"probe","minSeconds":6.6,"groups":[{"type":"formation","count":5,"at":0.0,"x":100,"elite":false,"key":false},{"type":"interceptor","count":2,"at":1.2,"x":240,"elite":false,"key":false},{"type":"minelayer","count":1,"at":2.4,"x":380,"elite":false,"key":true},{"type":"scout","count":5,"at":3.6,"x":100,"elite":false,"key":false},{"type":"scout","count":4,"at":4.8,"x":240,"elite":false,"key":false}]},{"tactic":"crossfire","minSeconds":8.3,"groups":[{"type":"bomber","count":1,"at":0.0,"x":240,"elite":false,"key":true},{"type":"diver","count":2,"at":1.3,"x":380,"elite":true,"key":false},{"type":"sniper","count":1,"at":2.6,"x":100,"elite":false,"key":false},{"type":"formation","count":4,"at":3.9,"x":240,"elite":false,"key":false},{"type":"scout","count":5,"at":5.2,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":6.5,"x":100,"elite":false,"key":false}]}]},
    {"id":10,"name":["交错火线","CROSSFIRE"],"boss":"iron-mk2","chapter":4,"chapterEnd":false,"waves":[{"tactic":"probe","minSeconds":4.8,"groups":[{"type":"support","count":1,"at":0.0,"x":100,"elite":false,"key":true},{"type":"formation","count":4,"at":1.0,"x":240,"elite":false,"key":false},{"type":"scout","count":3,"at":2.0,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":3.0,"x":100,"elite":false,"key":false}]},{"tactic":"crossfire","minSeconds":5.1,"groups":[{"type":"sniper","count":2,"at":0.0,"x":240,"elite":false,"key":false},{"type":"interceptor","count":2,"at":1.1,"x":380,"elite":false,"key":false},{"type":"formation","count":4,"at":2.2,"x":100,"elite":false,"key":false},{"type":"scout","count":5,"at":3.3,"x":240,"elite":false,"key":false}]},{"tactic":"priority","minSeconds":5.8,"groups":[{"type":"minelayer","count":1,"at":0.0,"x":380,"elite":false,"key":true},{"type":"support","count":1,"at":1.0,"x":100,"elite":false,"key":true},{"type":"formation","count":4,"at":2.0,"x":240,"elite":false,"key":false,"supply":true},{"type":"scout","count":3,"at":3.0,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":4.0,"x":100,"elite":false,"key":false}]},{"tactic":"squeeze","minSeconds":6.2,"groups":[{"type":"heavy","count":1,"at":0.0,"x":100,"elite":false,"key":false},{"type":"sniper","count":1,"at":1.1,"x":240,"elite":true,"key":false},{"type":"interceptor","count":2,"at":2.2,"x":380,"elite":false,"key":false},{"type":"formation","count":4,"at":3.3,"x":100,"elite":false,"key":false},{"type":"scout","count":5,"at":4.4,"x":240,"elite":false,"key":false}]},{"tactic":"ambush","minSeconds":5.8,"groups":[{"type":"support","count":1,"at":0.0,"x":240,"elite":false,"key":true},{"type":"diver","count":2,"at":1.0,"x":380,"elite":false,"key":false},{"type":"formation","count":4,"at":2.0,"x":100,"elite":false,"key":false},{"type":"scout","count":3,"at":3.0,"x":240,"elite":false,"key":false},{"type":"scout","count":3,"at":4.0,"x":380,"elite":false,"key":false}]}]},
    {"id":11,"name":["装甲壁垒","ARMORED WALL"],"boss":"twin-armored","chapter":4,"chapterEnd":false,"waves":[{"tactic":"probe","minSeconds":5.8,"groups":[{"type":"heavy","count":1,"at":0.0,"x":100,"elite":false,"key":false},{"type":"support","count":1,"at":1.0,"x":240,"elite":false,"key":true},{"type":"formation","count":4,"at":2.0,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":3.0,"x":100,"elite":false,"key":false},{"type":"scout","count":3,"at":4.0,"x":240,"elite":false,"key":false}]},{"tactic":"crossfire","minSeconds":5.1,"groups":[{"type":"sniper","count":2,"at":0.0,"x":240,"elite":false,"key":false},{"type":"diver","count":2,"at":1.1,"x":380,"elite":true,"key":false},{"type":"formation","count":4,"at":2.2,"x":100,"elite":false,"key":false},{"type":"scout","count":5,"at":3.3,"x":240,"elite":false,"key":false}]},{"tactic":"priority","minSeconds":5.8,"groups":[{"type":"support","count":1,"at":0.0,"x":380,"elite":false,"key":true},{"type":"interceptor","count":2,"at":1.0,"x":100,"elite":false,"key":false},{"type":"formation","count":4,"at":2.0,"x":240,"elite":false,"key":false},{"type":"scout","count":4,"at":3.0,"x":380,"elite":false,"key":false},{"type":"scout","count":3,"at":4.0,"x":100,"elite":false,"key":false}]},{"tactic":"squeeze","minSeconds":7.3,"groups":[{"type":"minelayer","count":1,"at":0.0,"x":100,"elite":false,"key":true},{"type":"heavy","count":1,"at":1.1,"x":240,"elite":false,"key":false},{"type":"sniper","count":1,"at":2.2,"x":380,"elite":false,"key":false},{"type":"formation","count":4,"at":3.3,"x":100,"elite":false,"key":false},{"type":"scout","count":4,"at":4.4,"x":240,"elite":false,"key":false},{"type":"scout","count":3,"at":5.5,"x":380,"elite":false,"key":false}]},{"tactic":"ambush","minSeconds":5.8,"groups":[{"type":"support","count":1,"at":0.0,"x":240,"elite":false,"key":true},{"type":"sniper","count":2,"at":1.0,"x":380,"elite":false,"key":false},{"type":"diver","count":2,"at":2.0,"x":100,"elite":true,"key":false},{"type":"formation","count":4,"at":3.0,"x":240,"elite":false,"key":false},{"type":"scout","count":5,"at":4.0,"x":380,"elite":false,"key":false}]}]},
    {"id":12,"name":["封锁突破","BREAK THE BLOCKADE"],"boss":"blockade","chapter":4,"chapterEnd":true,"waves":[{"tactic":"probe","minSeconds":5.8,"groups":[{"type":"bomber","count":1,"at":0.0,"x":100,"elite":false,"key":true},{"type":"minelayer","count":1,"at":1.0,"x":240,"elite":false,"key":true},{"type":"formation","count":4,"at":2.0,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":3.0,"x":100,"elite":false,"key":false},{"type":"scout","count":4,"at":4.0,"x":240,"elite":false,"key":false}]},{"tactic":"crossfire","minSeconds":7.3,"groups":[{"type":"support","count":1,"at":0.0,"x":240,"elite":false,"key":true},{"type":"sniper","count":1,"at":1.1,"x":380,"elite":true,"key":false},{"type":"interceptor","count":2,"at":2.2,"x":100,"elite":false,"key":false},{"type":"formation","count":4,"at":3.3,"x":240,"elite":false,"key":false},{"type":"scout","count":3,"at":4.4,"x":380,"elite":false,"key":false},{"type":"scout","count":3,"at":5.5,"x":100,"elite":false,"key":false}]},{"tactic":"priority","minSeconds":6.8,"groups":[{"type":"diver","count":2,"at":0.0,"x":380,"elite":true,"key":false},{"type":"bomber","count":1,"at":1.0,"x":100,"elite":false,"key":true},{"type":"minelayer","count":1,"at":2.0,"x":240,"elite":false,"key":true},{"type":"formation","count":4,"at":3.0,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":4.0,"x":100,"elite":false,"key":false},{"type":"scout","count":2,"at":5.0,"x":240,"elite":false,"key":false}]}]},
    {"id":13,"name":["蜂群深空","SWARM SPACE"],"boss":"swarm-carrier","chapter":5,"chapterEnd":false,"waves":[{"tactic":"probe","minSeconds":5.8,"groups":[{"type":"support","count":1,"at":0.0,"x":100,"elite":false,"key":true},{"type":"formation","count":4,"at":1.0,"x":240,"elite":false,"key":false},{"type":"interceptor","count":2,"at":2.0,"x":380,"elite":false,"key":false},{"type":"scout","count":3,"at":3.0,"x":100,"elite":false,"key":false},{"type":"scout","count":3,"at":4.0,"x":240,"elite":false,"key":false}]},{"tactic":"crossfire","minSeconds":6.2,"groups":[{"type":"diver","count":2,"at":0.0,"x":240,"elite":false,"key":false},{"type":"sniper","count":1,"at":1.1,"x":380,"elite":true,"key":false},{"type":"formation","count":4,"at":2.2,"x":100,"elite":false,"key":false},{"type":"scout","count":3,"at":3.3,"x":240,"elite":false,"key":false},{"type":"scout","count":3,"at":4.4,"x":380,"elite":false,"key":false}]},{"tactic":"priority","minSeconds":6.8,"groups":[{"type":"minelayer","count":1,"at":0.0,"x":380,"elite":false,"key":true},{"type":"support","count":1,"at":1.0,"x":100,"elite":false,"key":true},{"type":"interceptor","count":2,"at":2.0,"x":240,"elite":false,"key":false},{"type":"formation","count":4,"at":3.0,"x":380,"elite":false,"key":false,"supply":true},{"type":"scout","count":3,"at":4.0,"x":100,"elite":false,"key":false},{"type":"scout","count":3,"at":5.0,"x":240,"elite":false,"key":false}]},{"tactic":"squeeze","minSeconds":5.1,"groups":[{"type":"sniper","count":2,"at":0.0,"x":100,"elite":false,"key":false},{"type":"diver","count":2,"at":1.1,"x":240,"elite":true,"key":false},{"type":"formation","count":5,"at":2.2,"x":380,"elite":false,"key":false},{"type":"scout","count":5,"at":3.3,"x":100,"elite":false,"key":false}]},{"tactic":"ambush","minSeconds":5.8,"groups":[{"type":"support","count":1,"at":0.0,"x":240,"elite":false,"key":true},{"type":"interceptor","count":2,"at":1.0,"x":380,"elite":false,"key":false},{"type":"diver","count":2,"at":2.0,"x":100,"elite":true,"key":false},{"type":"formation","count":4,"at":3.0,"x":240,"elite":false,"key":false},{"type":"scout","count":5,"at":4.0,"x":380,"elite":false,"key":false}]}]},
    {"id":14,"name":["极光断层","AURORA RIFT"],"boss":"aurora","chapter":5,"chapterEnd":false,"waves":[{"tactic":"probe","minSeconds":5.8,"groups":[{"type":"minelayer","count":1,"at":0.0,"x":100,"elite":false,"key":true},{"type":"bomber","count":1,"at":1.0,"x":240,"elite":false,"key":true},{"type":"formation","count":4,"at":2.0,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":3.0,"x":100,"elite":false,"key":false},{"type":"scout","count":4,"at":4.0,"x":240,"elite":false,"key":false}]},{"tactic":"crossfire","minSeconds":7.3,"groups":[{"type":"interceptor","count":2,"at":0.0,"x":240,"elite":false,"key":false},{"type":"heavy","count":1,"at":1.1,"x":380,"elite":false,"key":false},{"type":"sniper","count":1,"at":2.2,"x":100,"elite":false,"key":false},{"type":"formation","count":4,"at":3.3,"x":240,"elite":false,"key":false},{"type":"scout","count":3,"at":4.4,"x":380,"elite":false,"key":false},{"type":"scout","count":3,"at":5.5,"x":100,"elite":false,"key":false}]},{"tactic":"priority","minSeconds":6.8,"groups":[{"type":"support","count":1,"at":0.0,"x":380,"elite":false,"key":true},{"type":"minelayer","count":1,"at":1.0,"x":100,"elite":false,"key":true},{"type":"interceptor","count":2,"at":2.0,"x":240,"elite":false,"key":false},{"type":"formation","count":4,"at":3.0,"x":380,"elite":false,"key":false},{"type":"scout","count":3,"at":4.0,"x":100,"elite":false,"key":false},{"type":"scout","count":3,"at":5.0,"x":240,"elite":false,"key":false}]},{"tactic":"squeeze","minSeconds":6.2,"groups":[{"type":"bomber","count":2,"at":0.0,"x":100,"elite":false,"key":true},{"type":"diver","count":2,"at":1.1,"x":240,"elite":true,"key":false},{"type":"formation","count":4,"at":2.2,"x":380,"elite":false,"key":false},{"type":"scout","count":3,"at":3.3,"x":100,"elite":false,"key":false},{"type":"scout","count":4,"at":4.4,"x":240,"elite":false,"key":false}]},{"tactic":"ambush","minSeconds":6.8,"groups":[{"type":"minelayer","count":1,"at":0.0,"x":240,"elite":false,"key":true},{"type":"interceptor","count":2,"at":1.0,"x":380,"elite":false,"key":false},{"type":"support","count":1,"at":2.0,"x":100,"elite":false,"key":true},{"type":"sniper","count":1,"at":3.0,"x":240,"elite":false,"key":false},{"type":"formation","count":5,"at":4.0,"x":380,"elite":false,"key":false},{"type":"scout","count":5,"at":5.0,"x":100,"elite":false,"key":false}]}]},
    {"id":15,"name":["最后巡航","FINAL PATROL"],"boss":"skybreaker","chapter":5,"chapterEnd":true,"waves":[{"tactic":"probe","minSeconds":6.8,"groups":[{"type":"support","count":1,"at":0.0,"x":100,"elite":false,"key":true},{"type":"sniper","count":1,"at":1.0,"x":240,"elite":false,"key":false},{"type":"diver","count":2,"at":2.0,"x":380,"elite":true,"key":false},{"type":"formation","count":4,"at":3.0,"x":100,"elite":false,"key":false},{"type":"scout","count":4,"at":4.0,"x":240,"elite":false,"key":false},{"type":"scout","count":4,"at":5.0,"x":380,"elite":false,"key":false}]},{"tactic":"crossfire","minSeconds":7.3,"groups":[{"type":"minelayer","count":1,"at":0.0,"x":240,"elite":false,"key":true},{"type":"bomber","count":1,"at":1.1,"x":380,"elite":false,"key":true},{"type":"interceptor","count":2,"at":2.2,"x":100,"elite":false,"key":false},{"type":"formation","count":4,"at":3.3,"x":240,"elite":false,"key":false},{"type":"scout","count":4,"at":4.4,"x":380,"elite":false,"key":false},{"type":"scout","count":4,"at":5.5,"x":100,"elite":false,"key":false}]},{"tactic":"priority","minSeconds":6.8,"groups":[{"type":"heavy","count":1,"at":0.0,"x":380,"elite":false,"key":false},{"type":"sniper","count":1,"at":1.0,"x":100,"elite":false,"key":false},{"type":"diver","count":2,"at":2.0,"x":240,"elite":true,"key":false},{"type":"interceptor","count":2,"at":3.0,"x":380,"elite":false,"key":false},{"type":"formation","count":5,"at":4.0,"x":100,"elite":false,"key":false},{"type":"scout","count":5,"at":5.0,"x":240,"elite":false,"key":false}]}]},
  ];
  const LIMITS = {
    enemies: 18,
    enemyBullets: 140,
    bullets: 90,
    hazards: 8,
    particles: 100,
    powerups: 8,
  };
  return {
    ENEMIES,
    BOSSES,
    MODES,
    STAGES,
    LIMITS,
    W: 480,
    H: 648,
    RECORD_KEY: "sky-patrol-records-v4",
    PREVIOUS_RECORD_KEY: "sky-patrol-records-v3",
    LEGACY_RECORD_KEY: "sky-patrol-records-v2",
  };
});
