(()=>{'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,GROUND=365,GRAVITY=1850,JUMP_SPEED=710,MIN_REACTION_TIME=1.15,COYOTE_TIME=.12,JUMP_BUFFER=.14,$=id=>document.getElementById(id);const ui={distance:$('distance'),best:$('best'),speed:$('speed'),overlay:$('overlay'),message:$('message'),detail:$('detail'),startButton:$('startButton'),pauseButton:$('pauseButton'),jumpButton:$('jumpButton'),dropButton:$('dropButton')};
let state='title',paused=false,player,hazards=[],coins=[],particles=[],distance=0,best=+localStorage.getItem('endlessRunnerBest')||0,scrollSpeed=265,last=0,spawnX=0,lastPattern='start',jumpHeld=false,fastFall=false,swipeY=0,jumpBuffer=0,coyoteTime=0;
function start(){state='playing';paused=false;distance=0;scrollSpeed=265;hazards=[];coins=[];particles=[];spawnX=W+280;lastPattern='start';player={x:145,y:GROUND-48,w:34,h:48,vy:0,onGround:true,run:0};jumpHeld=false;fastFall=false;jumpBuffer=0;coyoteTime=COYOTE_TIME;ui.pauseButton.textContent='PAUSE';hideOverlay();updateHud();last=performance.now()}
function showOverlay(title,detail,button){ui.message.textContent=title;ui.detail.textContent=detail;ui.startButton.textContent=button;ui.overlay.classList.remove('hidden')}
function hideOverlay(){ui.overlay.classList.add('hidden')}
function performJump(){if(state!=='playing'||!player||(!player.onGround&&coyoteTime<=0))return;player.vy=-JUMP_SPEED;player.onGround=false;coyoteTime=0;jumpBuffer=0;burst(player.x+10,GROUND,'#f2ca62',7)}
function jump(){if(state!=='playing')start();jumpBuffer=JUMP_BUFFER;performJump();jumpHeld=true}
function releaseJump(){jumpHeld=false;if(player&&player.vy<-300)player.vy=-300}
function setFastFall(value){if(value&&state!=='playing')start();fastFall=value}
function togglePause(){if(state!=='playing')return;paused=!paused;ui.pauseButton.textContent=paused?'RESUME':'PAUSE';if(paused)showOverlay('PAUSED','THE DESK IS WAITING','RESUME');else{hideOverlay();last=performance.now()}}
function gameOver(){if(state!=='playing')return;state='over';jumpHeld=false;fastFall=false;const metres=Math.floor(distance);if(metres>best){best=metres;localStorage.setItem('endlessRunnerBest',String(best))}burst(player.x+player.w/2,player.y+player.h/2,'#e98575',28);updateHud();showOverlay('DESK DETOUR',`DISTANCE ${metres}m · PACE ${(scrollSpeed/265).toFixed(2)}×`,'RUN AGAIN')}
function reactionDistance(){return scrollSpeed*MIN_REACTION_TIME+110}
function addCoinLine(x,y,count=4){for(let i=0;i<count;i++)coins.push({x:x+i*34,y:y-Math.sin(i/(count-1)*Math.PI)*42,r:7,taken:false})}
function spawnPattern(){const safeDistance=reactionDistance(),difficulty=Math.min(1,distance/6000),options=['spike','crate','pencil','ruler','ink','gap','coin'];let type=options[Math.floor(Math.random()*options.length)];if(type===lastPattern&&type!=='coin')type='coin';if(lastPattern==='gap'&&['gap','crate','ruler'].includes(type))type='coin';if(lastPattern==='pencil'&&type==='pencil')type='coin';const x=Math.max(spawnX,W+safeDistance);if(type==='spike'){hazards.push({type:'spike',x,y:GROUND-24,w:30,h:24});if(difficulty>.5&&Math.random()<.35)hazards.push({type:'spike',x:x+38,y:GROUND-24,w:30,h:24});addCoinLine(x-15,GROUND-78,4);spawnX=x+95+safeDistance*.45}else if(type==='crate'){hazards.push({type:'crate',x,y:GROUND-47,w:42,h:47});addCoinLine(x-18,GROUND-94,4);spawnX=x+90+safeDistance*.5}else if(type==='pencil'){hazards.push({type:'pencil',x,y:GROUND-22,w:74,h:22});addCoinLine(x-10,GROUND-78,4);spawnX=x+125+safeDistance*.5}else if(type==='ruler'){hazards.push({type:'ruler',x,y:GROUND-24,w:88,h:24});addCoinLine(x-5,GROUND-86,4);spawnX=x+135+safeDistance*.55}else if(type==='ink'){hazards.push({type:'ink',x,y:GROUND-18,w:48,h:18});addCoinLine(x-10,GROUND-69,4);spawnX=x+105+safeDistance*.45}else if(type==='gap'){const width=Math.min(138,86+difficulty*38);hazards.push({type:'gap',x,y:GROUND,w:width,h:H-GROUND});addCoinLine(x+4,GROUND-74,Math.max(3,Math.floor(width/34)));spawnX=x+width+safeDistance*.72}else{addCoinLine(x,GROUND-62,5);spawnX=x+190+safeDistance*.4}lastPattern=type}
function overGap(x){return hazards.some(h=>h.type==='gap'&&x>h.x&&x<h.x+h.w)}
function checkCollision(){const left=player.x+5,right=player.x+player.w-5,top=player.y+5,bottom=player.y+player.h;for(const h of hazards){if(h.type==='gap')continue;if(right>h.x+3&&left<h.x+h.w-3&&bottom>h.y+3&&top<h.y+h.h)return true}return false}
function update(dt){if(state!=='playing'||paused)return;scrollSpeed=Math.min(540,265+distance*.075);distance+=scrollSpeed*dt/17;player.run+=dt*12;jumpBuffer=Math.max(0,jumpBuffer-dt);coyoteTime=Math.max(0,coyoteTime-dt);const extra=fastFall&&player.vy>0?1500:0,holdLift=jumpHeld&&player.vy<0?560:0;player.vy+=(GRAVITY+extra-holdLift)*dt;player.y+=player.vy*dt;const wasGrounded=player.onGround,feetX=player.x+player.w*.55;if(player.y+player.h>=GROUND&&!overGap(feetX)&&player.vy>=0){player.y=GROUND-player.h;player.vy=0;player.onGround=true;coyoteTime=COYOTE_TIME}else{player.onGround=false;if(wasGrounded)coyoteTime=COYOTE_TIME}if(jumpBuffer>0)performJump();if(player.y>H+50){gameOver();return}const dx=scrollSpeed*dt;hazards.forEach(h=>h.x-=dx);coins.forEach(c=>c.x-=dx);spawnX-=dx;hazards=hazards.filter(h=>h.x+h.w>-60);coins=coins.filter(c=>c.x>-40&&!c.taken);while(spawnX<W+reactionDistance())spawnPattern();coins.forEach(c=>{if(Math.abs(player.x+player.w/2-c.x)<25&&Math.abs(player.y+player.h/2-c.y)<30){c.taken=true;distance+=8;burst(c.x,c.y,'#f2ca62',6)}});particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=400*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);if(checkCollision())gameOver();updateHud()}
function updateHud(){ui.distance.textContent=String(Math.floor(distance)).padStart(5,'0')+'m';ui.best.textContent=String(best).padStart(5,'0')+'m';ui.speed.textContent=(scrollSpeed/265).toFixed(2)+'×'}
function burst(x,y,color,count){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*160,vy:-40-Math.random()*140,life:.3+Math.random()*.35,color})}
function drawDeskDecor(light){ctx.save();ctx.globalAlpha=.86;ctx.fillStyle=light?'#f2ca62':'#f2ce68';ctx.fillRect(560,58,132,82);ctx.fillStyle=light?'#fff7e7':'#fff0c9';ctx.fillRect(570,69,112,61);ctx.strokeStyle=light?'#80bdd8':'#80c7df';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(585,87);ctx.lineTo(663,87);ctx.moveTo(585,104);ctx.lineTo(645,104);ctx.stroke();ctx.fillStyle=light?'#e98575':'#ed927e';ctx.fillRect(520,74,14,76);ctx.fillStyle=light?'#3f3a34':'#fff0c9';ctx.fillRect(517,68,20,9);ctx.strokeStyle=light?'#80bdd8':'#80c7df';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(420,195);ctx.lineTo(545,218);ctx.stroke();ctx.fillStyle=light?'#e98575':'#ed927e';ctx.beginPath();ctx.moveTo(414,194);ctx.lineTo(426,191);ctx.lineTo(426,201);ctx.closePath();ctx.fill();ctx.fillStyle=light?'#8abf93':'#8fd2a4';ctx.fillRect(690,180,38,25);ctx.fillStyle=light?'#3f3a34':'#fff0c9';for(let i=0;i<4;i++)ctx.fillRect(695+i*8,185,3,15);ctx.restore()}
function draw(){const light=document.documentElement?.dataset?.theme==='light';ctx.fillStyle=light?'#fff0c9':'#1a2e3d';ctx.fillRect(0,0,W,H);drawDeskDecor(light);for(let i=0;i<35;i++){ctx.fillStyle=i%5?(light?'#8b806d22':'#fff0c922'):(light?'#80bdd855':'#80c7df55');ctx.fillRect((i*137-distance*4%(W+80))%(W+80),40+(i*59)%245,2,2)}drawGround(light);hazards.forEach(h=>drawHazard(h,light));coins.forEach(c=>{ctx.fillStyle='#f2ca62';ctx.beginPath();ctx.arc(c.x,c.y,c.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff7e7';ctx.beginPath();ctx.arc(c.x-2,c.y-2,2,0,Math.PI*2);ctx.fill()});particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*3);ctx.fillStyle=p.color;ctx.fillRect(p.x-2,p.y-2,4,4)});ctx.globalAlpha=1;if(state!=='over')drawPlayer(light)}
function drawGround(light){ctx.fillStyle=light?'#e7d9b9':'#263f4d';ctx.fillRect(0,GROUND,W,H-GROUND);ctx.fillStyle=light?'#e98575':'#f2ca62';ctx.fillRect(0,GROUND,W,4);ctx.strokeStyle=light?'#b99b6a':'#52717b';ctx.lineWidth=2;for(let x=-((distance*3)%60);x<W;x+=60){ctx.beginPath();ctx.moveTo(x,GROUND+20);ctx.lineTo(x+28,GROUND+20);ctx.stroke()}hazards.filter(h=>h.type==='gap').forEach(h=>{ctx.fillStyle=light?'#fff0c9':'#1a2e3d';ctx.fillRect(h.x,GROUND-1,h.w,H-GROUND+2);ctx.fillStyle=light?'#e98575':'#f2ca62';ctx.fillRect(h.x-3,GROUND,3,H-GROUND);ctx.fillRect(h.x+h.w,GROUND,3,H-GROUND)})}
function drawHazard(h,light){if(h.type==='spike'){ctx.fillStyle=light?'#e98575':'#ed927e';ctx.beginPath();ctx.moveTo(h.x,h.y+h.h);ctx.lineTo(h.x+h.w/2,h.y);ctx.lineTo(h.x+h.w,h.y+h.h);ctx.fill();ctx.fillStyle='#fff0c966';ctx.fillRect(h.x+8,h.y+13,3,7)}else if(h.type==='crate'){ctx.fillStyle=light?'#80bdd8':'#80c7df';ctx.fillRect(h.x,h.y,h.w,h.h);ctx.strokeStyle=light?'#3f3a34':'#132633';ctx.lineWidth=3;ctx.strokeRect(h.x+5,h.y+5,h.w-10,h.h-10);ctx.beginPath();ctx.moveTo(h.x+7,h.y+7);ctx.lineTo(h.x+h.w-7,h.y+h.h-7);ctx.moveTo(h.x+h.w-7,h.y+7);ctx.lineTo(h.x+7,h.y+h.h-7);ctx.stroke()}else if(h.type==='pencil'){ctx.save();ctx.translate(h.x,h.y+h.h/2);ctx.rotate(-.12);ctx.fillStyle=light?'#f2ca62':'#f2ce68';ctx.fillRect(0,-7,h.w-13,14);ctx.fillStyle=light?'#e98575':'#ed927e';ctx.fillRect(h.w-13,-7,13,14);ctx.fillStyle=light?'#3f3a34':'#fff0c9';ctx.beginPath();ctx.moveTo(0,-7);ctx.lineTo(-12,0);ctx.lineTo(0,7);ctx.closePath();ctx.fill();ctx.restore()}else if(h.type==='ruler'){ctx.fillStyle=light?'#80bdd8':'#80c7df';ctx.fillRect(h.x,h.y,h.w,h.h);ctx.strokeStyle=light?'#3f3a34':'#fff0c9';ctx.lineWidth=2;for(let i=8;i<h.w;i+=12){ctx.beginPath();ctx.moveTo(h.x+i,h.y+3);ctx.lineTo(h.x+i,h.y+(i%24?10:17));ctx.stroke()}}else if(h.type==='ink'){ctx.fillStyle=light?'#aa78b8':'#b8a7e8';ctx.beginPath();ctx.ellipse(h.x+16,h.y+12,17,9,0,0,Math.PI*2);ctx.ellipse(h.x+32,h.y+10,13,8,0,0,Math.PI*2);ctx.ellipse(h.x+8,h.y+14,8,6,0,0,Math.PI*2);ctx.fill()}}
function drawPlayer(light){const bob=player.onGround?Math.sin(player.run)*2:0;ctx.save();ctx.translate(player.x+17,player.y+24+bob);const squash=player.onGround?1.02:1,stretch=player.onGround?1:1.08;ctx.scale(squash,stretch);ctx.fillStyle=light?'#3f3a34':'#fff0c9';ctx.beginPath();ctx.roundRect(-17,-21,34,42,7);ctx.fill();ctx.fillStyle=light?'#e98575':'#ed927e';ctx.beginPath();ctx.arc(-7,-15,5,0,Math.PI*2);ctx.arc(7,-15,5,0,Math.PI*2);ctx.fill();ctx.fillStyle=light?'#80bdd8':'#80c7df';ctx.beginPath();ctx.arc(8,-4,4,0,Math.PI*2);ctx.fill();const stride=player.onGround?Math.sin(player.run)*3:0;ctx.fillStyle=light?'#3f3a34':'#1a2e3d';ctx.fillRect(-10,20+stride,7,10-stride);ctx.fillRect(4,20-stride,7,10+stride);ctx.restore()}
function loop(time){const dt=Math.min(.033,(time-last)/1000||0);last=time;update(dt);draw();requestAnimationFrame(loop)}
function bindHold(button,on,off){button.addEventListener('selectstart',e=>e.preventDefault());button.addEventListener('contextmenu',e=>e.preventDefault());button.addEventListener('pointerdown',e=>{e.preventDefault();on();button.classList.add('active');button.setPointerCapture?.(e.pointerId)});['pointerup','pointercancel','pointerleave','lostpointercapture'].forEach(type=>button.addEventListener(type,e=>{e.preventDefault();off();button.classList.remove('active')}))}
bindHold(ui.jumpButton,jump,releaseJump);bindHold(ui.dropButton,()=>setFastFall(true),()=>setFastFall(false));canvas.addEventListener('selectstart',e=>e.preventDefault());canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{e.preventDefault();swipeY=e.clientY;jump();canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(e.buttons&&e.clientY-swipeY>42)setFastFall(true)});['pointerup','pointercancel','lostpointercapture'].forEach(type=>canvas.addEventListener(type,e=>{e.preventDefault();releaseJump();setFastFall(false)}));addEventListener('keydown',event=>{if(event.code==='Space'){event.preventDefault();if(!event.repeat)jump()}if(event.code==='ArrowDown')setFastFall(true);if(event.key.toLowerCase()==='p')togglePause()});addEventListener('keyup',event=>{if(event.code==='Space')releaseJump();if(event.code==='ArrowDown')setFastFall(false)});ui.startButton.onclick=()=>paused?togglePause():start();ui.pauseButton.onclick=togglePause;document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing'&&!paused)togglePause()});window.DeskDash={jump,getSnapshot:()=>({state,onGround:player?.onGround,y:player?.y,buffer:jumpBuffer,coyote:coyoteTime,hazards:hazards.map(h=>h.type)})};player={x:145,y:GROUND-48,w:34,h:48,vy:0,onGround:true,run:0};showOverlay('DESK DASH','JUMP THE PENCILS · CATCH THE STICKERS','START DASH');updateHud();requestAnimationFrame(loop)})();
