(()=>{'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,$=id=>document.getElementById(id),GROUND=365,GRAVITY=1850,JUMP_SPEED=710,MIN_REACTION_TIME=1.15;
const ui={distance:$('distance'),best:$('best'),speed:$('speed'),overlay:$('overlay'),message:$('message'),detail:$('detail'),startButton:$('startButton'),pauseButton:$('pauseButton'),jumpButton:$('jumpButton'),dropButton:$('dropButton')};
let state='title',paused=false,player,hazards=[],coins=[],particles=[],distance=0,best=+localStorage.getItem('endlessRunnerBest')||0,scrollSpeed=265,last=0,spawnX=0,lastPattern='start',jumpHeld=false,fastFall=false,swipeY=0;
function start(){state='playing';paused=false;distance=0;scrollSpeed=265;hazards=[];coins=[];particles=[];spawnX=W+280;lastPattern='start';player={x:145,y:GROUND-48,w:34,h:48,vy:0,onGround:true,run:0};jumpHeld=false;fastFall=false;ui.pauseButton.textContent='PAUSE';hideOverlay();updateHud();last=performance.now()}
function showOverlay(title,detail,button){ui.message.textContent=title;ui.detail.textContent=detail;ui.startButton.textContent=button;ui.overlay.classList.remove('hidden')}
function hideOverlay(){ui.overlay.classList.add('hidden')}
function jump(){if(state!=='playing')start();if(player.onGround){player.vy=-JUMP_SPEED;player.onGround=false;burst(player.x+10,GROUND,'#64e6e0',7)}jumpHeld=true}
function releaseJump(){jumpHeld=false;if(player&&player.vy<-300)player.vy=-300}
function setFastFall(value){if(value&&state!=='playing')start();fastFall=value}
function togglePause(){if(state!=='playing')return;paused=!paused;ui.pauseButton.textContent=paused?'RESUME':'PAUSE';if(paused)showOverlay('PAUSED','CATCH YOUR BREATH','RESUME');else{hideOverlay();last=performance.now()}}
function gameOver(){if(state!=='playing')return;state='over';jumpHeld=false;fastFall=false;const metres=Math.floor(distance);if(metres>best){best=metres;localStorage.setItem('endlessRunnerBest',String(best))}burst(player.x+player.w/2,player.y+player.h/2,'#ff6b7a',28);updateHud();showOverlay('RUN ENDED',`DISTANCE ${metres}m · SPEED ${(scrollSpeed/265).toFixed(2)}×`,'RUN AGAIN')}
function reactionDistance(){return scrollSpeed*MIN_REACTION_TIME+110}
function addCoinLine(x,y,count=4){for(let i=0;i<count;i++)coins.push({x:x+i*34,y:y-Math.sin(i/(count-1)*Math.PI)*42,r:7,taken:false})}
function spawnPattern(){const safeDistance=reactionDistance(),difficulty=Math.min(1,distance/6000),options=['spike','crate','gap','coin'];let type=options[Math.floor(Math.random()*options.length)];if(type===lastPattern&&type!=='coin')type='coin';if(lastPattern==='gap'&&(type==='gap'||type==='crate'))type='coin';const x=Math.max(spawnX,W+safeDistance);if(type==='spike'){hazards.push({type:'spike',x,y:GROUND-24,w:30,h:24});if(difficulty>.5&&Math.random()<.35)hazards.push({type:'spike',x:x+38,y:GROUND-24,w:30,h:24});addCoinLine(x-15,GROUND-78,4);spawnX=x+95+safeDistance*.45}else if(type==='crate'){hazards.push({type:'crate',x,y:GROUND-47,w:42,h:47});addCoinLine(x-18,GROUND-94,4);spawnX=x+90+safeDistance*.5}else if(type==='gap'){const width=Math.min(138,86+difficulty*38);hazards.push({type:'gap',x,y:GROUND,w:width,h:H-GROUND});addCoinLine(x+4,GROUND-74,Math.max(3,Math.floor(width/34)));spawnX=x+width+safeDistance*.72}else{addCoinLine(x,GROUND-62,5);spawnX=x+190+safeDistance*.4}lastPattern=type}
function overGap(x){return hazards.some(h=>h.type==='gap'&&x>h.x&&x<h.x+h.w)}
function checkCollision(){const left=player.x+5,right=player.x+player.w-5,top=player.y+5,bottom=player.y+player.h;for(const h of hazards){if(h.type==='gap')continue;if(right>h.x+3&&left<h.x+h.w-3&&bottom>h.y+3&&top<h.y+h.h)return true}return false}
function update(dt){if(state!=='playing'||paused)return;scrollSpeed=Math.min(540,265+distance*.075);distance+=scrollSpeed*dt/17;player.run+=dt*12;const extra=fastFall&&player.vy>0?1500:0,holdLift=jumpHeld&&player.vy<0?560:0;player.vy+=(GRAVITY+extra-holdLift)*dt;player.y+=player.vy*dt;const feetX=player.x+player.w*.55;if(player.y+player.h>=GROUND&&!overGap(feetX)&&player.vy>=0){player.y=GROUND-player.h;player.vy=0;player.onGround=true}else player.onGround=false;if(player.y>H+50){gameOver();return}const dx=scrollSpeed*dt;hazards.forEach(h=>h.x-=dx);coins.forEach(c=>c.x-=dx);spawnX-=dx;hazards=hazards.filter(h=>h.x+h.w>-60);coins=coins.filter(c=>c.x>-40&&!c.taken);while(spawnX<W+reactionDistance())spawnPattern();coins.forEach(c=>{if(Math.abs(player.x+player.w/2-c.x)<25&&Math.abs(player.y+player.h/2-c.y)<30){c.taken=true;distance+=8;burst(c.x,c.y,'#ffb45c',6)}});particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=400*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);if(checkCollision())gameOver();updateHud()}
function updateHud(){ui.distance.textContent=String(Math.floor(distance)).padStart(5,'0')+'m';ui.best.textContent=String(best).padStart(5,'0')+'m';ui.speed.textContent=(scrollSpeed/265).toFixed(2)+'×'}
function burst(x,y,color,count){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*160,vy:-40-Math.random()*140,life:.3+Math.random()*.35,color})}
function draw(){ctx.fillStyle='#07111d';ctx.fillRect(0,0,W,H);for(let i=0;i<35;i++){ctx.fillStyle=i%5?'#e8f0f722':'#64e6e055';ctx.fillRect((i*137-distance*4%(W+80))%(W+80),40+(i*59)%245,2,2)}drawGround();hazards.forEach(drawHazard);coins.forEach(c=>{ctx.strokeStyle='#ffb45c';ctx.lineWidth=4;ctx.beginPath();ctx.arc(c.x,c.y,c.r,0,Math.PI*2);ctx.stroke()});particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*3);ctx.fillStyle=p.color;ctx.fillRect(p.x-2,p.y-2,4,4)});ctx.globalAlpha=1;if(state!=='over')drawPlayer();if(paused){ctx.fillStyle='#070b1299';ctx.fillRect(0,0,W,H)}}
function drawGround(){ctx.fillStyle='#132633';ctx.fillRect(0,GROUND,W,H-GROUND);ctx.fillStyle='#64e6e0';ctx.fillRect(0,GROUND,W,4);hazards.filter(h=>h.type==='gap').forEach(h=>{ctx.fillStyle='#07111d';ctx.fillRect(h.x,GROUND-1,h.w,H-GROUND+2);ctx.fillStyle='#ff6b7a';ctx.fillRect(h.x-3,GROUND,3,H-GROUND);ctx.fillRect(h.x+h.w,GROUND,3,H-GROUND)})}
function drawHazard(h){if(h.type==='spike'){ctx.fillStyle='#ff6b7a';ctx.beginPath();ctx.moveTo(h.x,h.y+h.h);ctx.lineTo(h.x+h.w/2,h.y);ctx.lineTo(h.x+h.w,h.y+h.h);ctx.fill()}else if(h.type==='crate'){ctx.fillStyle='#ffb45c';ctx.fillRect(h.x,h.y,h.w,h.h);ctx.strokeStyle='#07111d';ctx.lineWidth=4;ctx.strokeRect(h.x+5,h.y+5,h.w-10,h.h-10);ctx.beginPath();ctx.moveTo(h.x+7,h.y+7);ctx.lineTo(h.x+h.w-7,h.y+h.h-7);ctx.moveTo(h.x+h.w-7,h.y+7);ctx.lineTo(h.x+7,h.y+h.h-7);ctx.stroke()}}
function drawPlayer(){const bob=player.onGround?Math.sin(player.run)*2:0;ctx.fillStyle='#e8f0f7';ctx.fillRect(player.x,player.y+bob,player.w,player.h);ctx.fillStyle='#64e6e0';ctx.fillRect(player.x+20,player.y+9+bob,7,7);ctx.fillStyle='#ffb45c';const stride=player.onGround?Math.sin(player.run)*8:5;ctx.fillRect(player.x+4,player.y+player.h-2+bob,7,9+stride);ctx.fillRect(player.x+22,player.y+player.h-2+bob,7,9-stride)}
function loop(time){const dt=Math.min(.033,(time-last)/1000||0);last=time;update(dt);draw();requestAnimationFrame(loop)}
function bindHold(button,on,off){button.addEventListener('selectstart',e=>e.preventDefault());button.addEventListener('contextmenu',e=>e.preventDefault());button.addEventListener('pointerdown',e=>{e.preventDefault();on();button.classList.add('active');button.setPointerCapture?.(e.pointerId)});['pointerup','pointercancel','pointerleave','lostpointercapture'].forEach(type=>button.addEventListener(type,e=>{e.preventDefault();off();button.classList.remove('active')}))}
bindHold(ui.jumpButton,jump,releaseJump);bindHold(ui.dropButton,()=>setFastFall(true),()=>setFastFall(false));canvas.addEventListener('selectstart',e=>e.preventDefault());canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{e.preventDefault();swipeY=e.clientY;jump();canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(e.buttons&&e.clientY-swipeY>42)setFastFall(true)});['pointerup','pointercancel','lostpointercapture'].forEach(type=>canvas.addEventListener(type,e=>{e.preventDefault();releaseJump();setFastFall(false)}));
addEventListener('keydown',event=>{if(event.code==='Space'){event.preventDefault();if(!event.repeat)jump()}if(event.code==='ArrowDown')setFastFall(true);if(event.key.toLowerCase()==='p')togglePause()});addEventListener('keyup',event=>{if(event.code==='Space')releaseJump();if(event.code==='ArrowDown')setFastFall(false)});ui.startButton.onclick=()=>paused?togglePause():start();ui.pauseButton.onclick=togglePause;document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing'&&!paused)togglePause()});
player={x:145,y:GROUND-48,w:34,h:48,vy:0,onGround:true,run:0};showOverlay('ENDLESS RUNNER','JUMP · CLEAR THE GAPS · KEEP MOVING','START RUN');updateHud();requestAnimationFrame(loop)})();
