(()=>{'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,$=id=>document.getElementById(id),GRAVITY=1500;
const ui={score:$('score'),stars:$('stars'),best:$('best'),height:$('height'),overlay:$('overlay'),message:$('message'),detail:$('detail'),start:$('startButton'),pause:$('pauseButton')};
const input={left:false,right:false};
let state='title',paused=false,player,platforms=[],stars=[],particles=[],cameraY=0,highest=0,score=0,starCount=0,best=+localStorage.getItem('doodleHopBest')||0,bestStars=+localStorage.getItem('doodleHopBestStars')||0,last=0,clock=0,nextPlatformY=0,lastPlatformX=W/2;

function palette(){const style=getComputedStyle(document.documentElement);const read=(name,fallback)=>style.getPropertyValue(name).trim()||fallback;return{paper:read('--paper','#fffaf0'),grid:read('--grid','#b9dfe0'),ink:read('--ink','#3d3832'),muted:read('--muted','#8a7c6e'),mint:read('--mint','#9eddbd'),blue:read('--blue','#8fc9eb'),yellow:read('--yellow','#f7d66c'),coral:read('--coral','#f28c78'),purple:read('--purple','#b8a7e8'),shadow:read('--shadow','#d6c8b7')}}
function platformType(height){const roll=Math.random(),difficulty=Math.min(.35,height/9000);if(roll<.08+difficulty*.12)return'breaking';if(roll<.17+difficulty*.12)return'moving';if(roll<.23)return'spring';if(roll<.29+difficulty*.08)return'fading';return'normal'}
function makePlatform(y,forced,anchorX){const type=forced||platformType(-y),w=type==='breaking'?74:88+Math.random()*38,base=anchorX??W/2,x=Math.max(12,Math.min(W-w-12,base+(Math.random()-.5)*210));return{x,y,w,h:12,type,vx:type==='moving'?(Math.random()<.5?-1:1)*(42+Math.random()*32):0,broken:false,touched:false,alpha:1,seed:Math.random()*10}}
function addStar(platform){if(platform.type==='breaking'||Math.random()<.18)return;stars.push({x:platform.x+18+Math.random()*Math.max(20,platform.w-36),y:platform.y-31,r:9,phase:Math.random()*Math.PI*2,collected:false})}
function generatePlatforms(){while(nextPlatformY>cameraY-940){const height=-nextPlatformY,gap=80+Math.min(38,height/430)+Math.random()*28;nextPlatformY-=gap;const platform=makePlatform(nextPlatformY,null,lastPlatformX);lastPlatformX=platform.x+platform.w*.5;platforms.push(platform);addStar(platform)}}
function reset(){cameraY=0;highest=0;score=0;starCount=0;particles=[];stars=[];platforms=[];const starter=makePlatform(650,'normal',W/2);starter.x=145;starter.w=190;platforms.push(starter);let y=568,anchor=240;for(let i=0;i<9;i++){const p=makePlatform(y,i<2?'normal':null,anchor);platforms.push(p);addStar(p);anchor=p.x+p.w*.5;y-=84+Math.random()*23}lastPlatformX=anchor;nextPlatformY=y;player={x:W/2-22,y:590,w:44,h:48,vx:0,vy:-650};generatePlatforms();state='playing';paused=false;ui.pause.textContent='PAUSE';hideOverlay();updateHud();last=performance.now()}
function start(){reset()}
function resumeOrStart(){if(state!=='playing')start();else if(paused)togglePause()}
function showOverlay(title,detail,button){ui.message.textContent=title;ui.detail.textContent=detail;ui.start.textContent=button;ui.overlay.classList.remove('hidden')}
function hideOverlay(){ui.overlay.classList.add('hidden')}
function togglePause(){if(state!=='playing')return;paused=!paused;ui.pause.textContent=paused?'RESUME':'PAUSE';if(paused)showOverlay('PAUSED','THE SKY IS WAITING FOR YOU','RESUME');else{hideOverlay();last=performance.now()}}
function gameOver(){if(state!=='playing')return;state='over';paused=false;if(score>best){best=score;localStorage.setItem('doodleHopBest',String(best))}if(starCount>bestStars){bestStars=starCount;localStorage.setItem('doodleHopBestStars',String(bestStars))}updateHud();showOverlay('WHOOPS!','HEIGHT '+Math.floor(highest/10)+'m · '+starCount+' STARS FOUND','TRY AGAIN')}
function landOnPlatform(platform,previousBottom){if(player.vy<=0||platform.broken||platform.alpha<=.15)return false;const worldBottom=player.y+player.h+cameraY;if(previousBottom>platform.y+3||worldBottom<platform.y||player.x+player.w<platform.x||player.x>platform.x+platform.w)return false;player.y=platform.y-cameraY-player.h;player.vy=platform.type==='spring'?-900:-670;platform.touched=true;if(platform.type==='breaking')platform.breakTimer=.12;if(platform.type==='fading')platform.alpha=.38;const gain=platform.type==='spring'?45:10;score+=gain;burst(player.x+player.w/2,platform.y,palette().mint,platform.type==='spring'?14:6);return true}
function burst(x,y,color,count){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*150,vy:-60-Math.random()*140,life:.28+Math.random()*.38,size:2+Math.random()*3,color})}
function collectStars(){const worldTop=player.y+cameraY,worldBottom=worldTop+player.h;for(const star of stars){if(star.collected)continue;if(player.x+player.w>star.x-star.r&&player.x<star.x+star.r&&worldBottom>star.y-star.r&&worldTop<star.y+star.r){star.collected=true;starCount++;score+=25;burst(star.x,star.y,palette().yellow,10)}}}
function update(dt){if(state!=='playing'||paused)return;const previousBottom=player.y+player.h+cameraY,dir=(input.right?1:0)-(input.left?1:0);player.vx+=dir*1450*dt;player.vx*=Math.pow(.82,dt*10);player.vx=Math.max(-330,Math.min(330,player.vx));player.x+=player.vx*dt;if(player.x+player.w<0)player.x=W;else if(player.x>W)player.x=-player.w;player.vy+=GRAVITY*dt;player.y+=player.vy*dt;
platforms.forEach(p=>{if(p.type==='moving'){p.x+=p.vx*dt;if(p.x<4){p.x=4;p.vx=Math.abs(p.vx)}if(p.x+p.w>W-4){p.x=W-4-p.w;p.vx=-Math.abs(p.vx)}}if(p.breakTimer){p.breakTimer-=dt;if(p.breakTimer<=0)p.broken=true}if(p.broken){p.y+=260*dt;p.alpha-=1.8*dt}else if(p.type==='fading'&&p.touched)p.alpha-=.28*dt});
for(const p of platforms)if(landOnPlatform(p,previousBottom))break;collectStars();
if(player.y<250){const shift=250-player.y;player.y=250;cameraY-=shift;highest=Math.max(highest,-cameraY);score=Math.max(score,Math.floor(highest/5));generatePlatforms()}
particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=360*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);platforms=platforms.filter(p=>p.y-cameraY<H+170&&p.alpha>0);stars=stars.filter(s=>!s.collected&&s.y-cameraY<H+130);updateHud();if(player.y>H+90)gameOver()}
function updateHud(){ui.score.textContent=String(score).padStart(6,'0');ui.stars.textContent=String(starCount).padStart(2,'0');ui.best.textContent=String(best).padStart(6,'0');ui.height.textContent=String(Math.floor(highest/10)).padStart(4,'0')+'m'}
function roundedRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath()}
function drawGrid(p){ctx.fillStyle=p.paper;ctx.fillRect(0,0,W,H);ctx.strokeStyle=p.grid;ctx.globalAlpha=.46;ctx.lineWidth=1;const offset=((cameraY*.18)%32+32)%32;for(let x=0;x<=W;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=-32+offset;y<=H+32;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.globalAlpha=1}
function drawCloud(x,y,s,p){ctx.save();ctx.translate(x,y);ctx.strokeStyle=p.ink;ctx.lineWidth=2.5;ctx.lineCap='round';ctx.fillStyle=p.panel||p.paper;ctx.beginPath();ctx.moveTo(-34*s,8*s);ctx.bezierCurveTo(-39*s,-3*s,-29*s,-13*s,-18*s,-11*s);ctx.bezierCurveTo(-15*s,-28*s,7*s,-31*s,14*s,-13*s);ctx.bezierCurveTo(30*s,-19*s,42*s,-5*s,35*s,9*s);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle=p.blue;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-24*s,12*s);ctx.lineTo(-15*s,8*s);ctx.moveTo(-5*s,14*s);ctx.lineTo(5*s,10*s);ctx.moveTo(16*s,13*s);ctx.lineTo(26*s,8*s);ctx.stroke();ctx.restore()}
function drawSun(x,y,r,p){ctx.save();ctx.translate(x,y);ctx.strokeStyle=p.ink;ctx.lineWidth=3;ctx.lineCap='round';for(let i=0;i<10;i++){const a=i*Math.PI/5;ctx.beginPath();ctx.moveTo(Math.cos(a)*(r+7),Math.sin(a)*(r+7));ctx.lineTo(Math.cos(a)*(r+15),Math.sin(a)*(r+15));ctx.stroke()}ctx.fillStyle=p.yellow;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=p.ink;ctx.beginPath();ctx.arc(-r*.28,-r*.08,2.5,0,Math.PI*2);ctx.arc(r*.28,-r*.08,2.5,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(0,r*.12,r*.28,0,Math.PI);ctx.stroke();ctx.restore()}
function drawBackground(p){const cloudY=((180-cameraY*.12)%760+760)%760-40;drawCloud(78,cloudY,.72,p);drawCloud(396,((470-cameraY*.1)%790+790)%790-50,.54,p);drawSun(386,106-cameraY*.07%420,34,p);ctx.save();ctx.globalAlpha=.45;ctx.strokeStyle=p.coral;ctx.lineWidth=2;ctx.lineCap='round';for(let i=0;i<7;i++){const x=28+i*71,y=((i*127-cameraY*.06)%H+H)%H;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+7,y-7);ctx.lineTo(x+14,y);ctx.stroke()}ctx.restore()}
function drawStar(star,p){const y=star.y-cameraY;if(y<-30||y>H+30)return;ctx.save();ctx.translate(star.x,y);ctx.rotate(Math.sin(clock*.004+star.phase)*.16);ctx.fillStyle=p.yellow;ctx.strokeStyle=p.ink;ctx.lineWidth=2.5;ctx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?star.r*.42:star.r;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}
function drawPlatform(platform,p){const y=platform.y-cameraY;if(y<-36||y>H+40)return;ctx.save();ctx.globalAlpha=Math.max(0,platform.alpha);const colors={normal:p.mint,moving:p.blue,breaking:p.coral,spring:p.yellow,fading:p.purple},color=colors[platform.type];ctx.fillStyle=color;ctx.strokeStyle=p.ink;ctx.lineWidth=2.5;ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(platform.x,y+4);ctx.quadraticCurveTo(platform.x+platform.w*.18,y-4,platform.x+platform.w*.34,y+2);ctx.quadraticCurveTo(platform.x+platform.w*.54,y-6,platform.x+platform.w*.68,y+2);ctx.quadraticCurveTo(platform.x+platform.w*.86,y-5,platform.x+platform.w,y+4);ctx.lineTo(platform.x+platform.w-5,y+18);ctx.quadraticCurveTo(platform.x+platform.w*.82,y+24,platform.x+platform.w*.66,y+18);ctx.quadraticCurveTo(platform.x+platform.w*.5,y+29,platform.x+platform.w*.34,y+18);ctx.quadraticCurveTo(platform.x+platform.w*.16,y+25,platform.x+5,y+17);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle=p.ink;ctx.globalAlpha*=.35;ctx.lineWidth=1.5;for(let i=0;i<4;i++){const sx=platform.x+12+i*platform.w/5;ctx.beginPath();ctx.moveTo(sx,y+11);ctx.lineTo(sx+5,y+16);ctx.stroke()}ctx.globalAlpha=Math.max(0,platform.alpha);if(platform.type==='breaking'){ctx.strokeStyle=p.ink;ctx.globalAlpha=.8;ctx.beginPath();ctx.moveTo(platform.x+platform.w*.42,y+3);ctx.lineTo(platform.x+platform.w*.35,y+18);ctx.moveTo(platform.x+platform.w*.66,y+3);ctx.lineTo(platform.x+platform.w*.74,y+18);ctx.stroke()}if(platform.type==='spring'){ctx.strokeStyle=p.ink;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(platform.x+platform.w/2-8,y-1);ctx.lineTo(platform.x+platform.w/2-4,y-9);ctx.lineTo(platform.x+platform.w/2+1,y-1);ctx.lineTo(platform.x+platform.w/2+6,y-9);ctx.lineTo(platform.x+platform.w/2+10,y-1);ctx.stroke()}ctx.restore()}
function drawPlayer(p){if(!player)return;ctx.save();ctx.translate(player.x+player.w/2,player.y+player.h/2);ctx.rotate(Math.sin(clock*.006)*.035);ctx.strokeStyle=p.ink;ctx.fillStyle=p.mint;ctx.lineWidth=3;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(-18,-5);ctx.quadraticCurveTo(-17,-24,0,-25);ctx.quadraticCurveTo(18,-24,19,-4);ctx.quadraticCurveTo(22,16,8,23);ctx.quadraticCurveTo(0,28,-10,23);ctx.quadraticCurveTo(-23,16,-18,-5);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle=p.mint;ctx.beginPath();ctx.ellipse(-23,-3,7,12,-.55,0,Math.PI*2);ctx.ellipse(23,-3,7,12,.55,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=p.ink;ctx.beginPath();ctx.ellipse(-7,-6,3,5,0,0,Math.PI*2);ctx.ellipse(7,-6,3,5,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=p.ink;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,1,7,.15*Math.PI,.85*Math.PI);ctx.stroke();ctx.fillStyle=p.coral;ctx.beginPath();ctx.arc(-12,2,3.8,0,Math.PI*2);ctx.arc(12,2,3.8,0,Math.PI*2);ctx.fill();ctx.fillStyle=p.yellow;ctx.strokeStyle=p.ink;ctx.lineWidth=2.5;ctx.beginPath();ctx.arc(0,-24,13,Math.PI,Math.PI*2);ctx.lineTo(13,-23);ctx.quadraticCurveTo(2,-17,-13,-21);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle=p.coral;ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(-18,11);ctx.quadraticCurveTo(0,16,18,10);ctx.stroke();ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(14,12);ctx.lineTo(27,17);ctx.lineTo(18,21);ctx.stroke();ctx.fillStyle=p.ink;ctx.strokeStyle=p.ink;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-10,22);ctx.lineTo(-7,28);ctx.moveTo(10,22);ctx.lineTo(7,28);ctx.stroke();ctx.restore()}
function draw(){const p=palette();drawGrid(p);drawBackground(p);platforms.forEach(platform=>drawPlatform(platform,p));stars.forEach(star=>drawStar(star,p));particles.forEach(part=>{ctx.save();ctx.globalAlpha=Math.max(0,part.life*2.4);ctx.fillStyle=part.color;ctx.strokeStyle=p.ink;ctx.lineWidth=1;ctx.beginPath();ctx.arc(part.x,part.y-cameraY,part.size,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()});drawPlayer(p);if(paused){ctx.fillStyle=p.paper+'cc';ctx.fillRect(0,0,W,H)}}
function loop(time){const dt=Math.min(.033,(time-last)/1000||0);last=time;clock=time;update(dt);draw();requestAnimationFrame(loop)}
function bindHold(id,key){const button=$(id),on=event=>{event.preventDefault();if(state!=='playing')start();input[key]=true;button.classList.add('active');button.setPointerCapture?.(event.pointerId)},off=()=>{input[key]=false;button.classList.remove('active')};button.addEventListener('pointerdown',on);['pointerup','pointercancel','pointerleave','lostpointercapture'].forEach(type=>button.addEventListener(type,off));button.addEventListener('selectstart',event=>event.preventDefault());button.addEventListener('contextmenu',event=>event.preventDefault())}
bindHold('leftButton','left');bindHold('rightButton','right');canvas.addEventListener('pointerdown',event=>{event.preventDefault();if(state!=='playing')start();const rect=canvas.getBoundingClientRect(),key=event.clientX-rect.left<rect.width/2?'left':'right';input[key]=true;canvas.setPointerCapture?.(event.pointerId);canvas.dataset.held=key});const releaseCanvas=()=>{if(canvas.dataset.held){input[canvas.dataset.held]=false;delete canvas.dataset.held}};['pointerup','pointercancel','lostpointercapture','pointerleave'].forEach(type=>canvas.addEventListener(type,releaseCanvas));
addEventListener('keydown',event=>{const key=event.key.toLowerCase();if(['arrowleft','a'].includes(key)){event.preventDefault();if(state!=='playing')start();input.left=true}if(['arrowright','d'].includes(key)){event.preventDefault();if(state!=='playing')start();input.right=true}if(key==='p')togglePause()});addEventListener('keyup',event=>{const key=event.key.toLowerCase();if(['arrowleft','a'].includes(key))input.left=false;if(['arrowright','d'].includes(key))input.right=false});ui.start.onclick=()=>paused?togglePause():start();ui.pause.onclick=togglePause;document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing'&&!paused)togglePause()});document.addEventListener('themechange',()=>draw());
player={x:W/2-22,y:590,w:44,h:48,vx:0,vy:0};platforms=[];showOverlay('DOODLE HOP!','BOUNCE UP · COLLECT LITTLE STARS','START JUMPING');updateHud();requestAnimationFrame(loop)})();
