(()=>{'use strict';
const R=window.SudokuRules,$=id=>document.getElementById(id),boardEl=$('board');
let puzzle,solution,board,notes,givens,selected={r:0,c:0},history=[],mistakes=0,state='title',notesMode=false,startTime=0,timerId=0,elapsed=0;
const ui={timer:$('timer'),mistakes:$('mistakes'),best:$('best'),difficulty:$('difficulty'),overlay:$('overlay'),title:$('overlayTitle'),text:$('overlayText'),start:$('startButton'),notes:$('notesButton')};
const pad=n=>String(n).padStart(2,'0'),formatTime=s=>`${pad(Math.floor(s/60))}:${pad(s%60)}`,bestKey=()=>`sudokuBest-${ui.difficulty.value}`;
function updateTimer(){if(state==='playing')elapsed=Math.floor((Date.now()-startTime)/1000);ui.timer.textContent=formatTime(elapsed)}
function updateBest(){const value=localStorage.getItem(bestKey());ui.best.textContent=value?formatTime(+value):'--:--'}
function setOverlay(title,text,button){ui.title.textContent=title;ui.text.textContent=text;ui.start.textContent=button;ui.overlay.classList.remove('hide')}
function hideOverlay(){ui.overlay.classList.add('hide')}
function snapshot(){return{board:R.clone(board),notes:notes.map(row=>row.map(set=>[...set])),selected:{...selected},mistakes}}
function restore(s){board=R.clone(s.board);notes=s.notes.map(row=>row.map(values=>new Set(values)));selected={...s.selected};mistakes=s.mistakes;updateHud();render()}
function updateHud(){ui.mistakes.textContent=`${mistakes} / 3`;ui.notes.classList.toggle('active',notesMode);ui.notes.setAttribute('aria-pressed',String(notesMode));updateBest()}
function newGame(showIntro=false){const game=R.generatePuzzle(ui.difficulty.value);puzzle=game.puzzle;solution=game.solution;board=R.clone(puzzle);givens=puzzle.map(row=>row.map(Boolean));notes=Array.from({length:9},()=>Array.from({length:9},()=>new Set()));selected={r:0,c:0};history=[];mistakes=0;elapsed=0;clearInterval(timerId);state=showIntro?'title':'playing';updateHud();render();updateTimer();if(showIntro)setOverlay('BENTO NUMBERS','SELECT A CELL AND PACK A NUMBER','START');else startClock()}
function startClock(){state='playing';startTime=Date.now()-elapsed*1000;clearInterval(timerId);timerId=setInterval(updateTimer,500);hideOverlay()}
function render(){boardEl.innerHTML='';const selectedValue=board[selected.r][selected.c];for(let r=0;r<9;r++)for(let c=0;c<9;c++){const value=board[r][c],cell=document.createElement('button');cell.type='button';cell.className='cell';cell.dataset.row=r;cell.dataset.col=c;cell.setAttribute('role','gridcell');if(givens[r][c])cell.classList.add('given');if(r===selected.r||c===selected.c||(Math.floor(r/3)===Math.floor(selected.r/3)&&Math.floor(c/3)===Math.floor(selected.c/3)))cell.classList.add('peer');if(selectedValue&&value===selectedValue)cell.classList.add('same');if(r===selected.r&&c===selected.c)cell.classList.add('selected');if(value){cell.textContent=value}else{const note=document.createElement('span');note.className='notes';for(let n=1;n<=9;n++){const slot=document.createElement('span');slot.textContent=notes[r][c].has(n)?n:'';note.appendChild(slot)}cell.appendChild(note)}cell.addEventListener('pointerdown',event=>{event.preventDefault();selectCell(r,c)});boardEl.appendChild(cell)}}
function selectCell(r,c){selected={r,c};render()}
function clearPeerNotes(r,c,value){for(let i=0;i<9;i++){notes[r][i].delete(value);notes[i][c].delete(value)}const br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;for(let y=br;y<br+3;y++)for(let x=bc;x<bc+3;x++)notes[y][x].delete(value)}
function enterNumber(value){if(state!=='playing'||givens[selected.r][selected.c])return;const {r,c}=selected;history.push(snapshot());if(notesMode&&!board[r][c]){notes[r][c].has(value)?notes[r][c].delete(value):notes[r][c].add(value);render();return}if(value!==solution[r][c]){mistakes++;updateHud();const cell=boardEl.children[r*9+c];cell.classList.add('error');setTimeout(()=>cell.classList.remove('error'),350);if(mistakes>=3){state='over';clearInterval(timerId);setOverlay('GAME OVER','THREE MISTAKES','TRY AGAIN')}return}board[r][c]=value;notes[r][c].clear();clearPeerNotes(r,c,value);render();if(R.isComplete(board))finish()}
function erase(){if(state!=='playing'||givens[selected.r][selected.c])return;history.push(snapshot());board[selected.r][selected.c]=0;notes[selected.r][selected.c].clear();render()}
function undo(){if(!history.length||state!=='playing')return;restore(history.pop())}
function hint(){if(state!=='playing')return;const empties=[];for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(!board[r][c])empties.push({r,c});if(!empties.length)return;history.push(snapshot());const cell=empties[Math.floor(Math.random()*empties.length)];selected=cell;board[cell.r][cell.c]=solution[cell.r][cell.c];notes[cell.r][cell.c].clear();clearPeerNotes(cell.r,cell.c,board[cell.r][cell.c]);render();if(R.isComplete(board))finish()}
function finish(){state='won';clearInterval(timerId);updateTimer();const previous=+(localStorage.getItem(bestKey())||Infinity);if(elapsed<previous)localStorage.setItem(bestKey(),String(elapsed));updateBest();setOverlay('PUZZLE CLEAR',`TIME ${formatTime(elapsed)} · ${mistakes} MISTAKES`,'NEW PUZZLE')}
function moveSelection(dr,dc){selected={r:Math.max(0,Math.min(8,selected.r+dr)),c:Math.max(0,Math.min(8,selected.c+dc))};render()}
document.querySelectorAll('[data-number]').forEach(button=>button.addEventListener('pointerdown',event=>{event.preventDefault();enterNumber(+button.dataset.number)}));
$('notesButton').onclick=()=>{notesMode=!notesMode;updateHud()};$('eraseButton').onclick=erase;$('undoButton').onclick=undo;$('hintButton').onclick=hint;$('newButton').onclick=()=>newGame(false);ui.difficulty.onchange=()=>newGame(false);ui.start.onclick=()=>state==='title'?startClock():newGame(false);
window.addEventListener('keydown',event=>{if(/^[1-9]$/.test(event.key)){event.preventDefault();enterNumber(+event.key);return}const moves={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1]};if(moves[event.key]){event.preventDefault();moveSelection(...moves[event.key])}else if(event.key==='Backspace'||event.key==='Delete'||event.key==='0'){event.preventDefault();erase()}else if(event.key.toLowerCase()==='n'){notesMode=!notesMode;updateHud()}else if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();undo()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing'){updateTimer();clearInterval(timerId)}else if(!document.hidden&&state==='playing')startClock()});
newGame(true)})();
