(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.SudokuRules=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const SIZE=9,BOX=3;
const clone=board=>board.map(row=>row.slice());
function canPlace(board,row,col,value){if(!value)return true;for(let i=0;i<SIZE;i++){if(i!==col&&board[row][i]===value)return false;if(i!==row&&board[i][col]===value)return false}const br=Math.floor(row/BOX)*BOX,bc=Math.floor(col/BOX)*BOX;for(let r=br;r<br+BOX;r++)for(let c=bc;c<bc+BOX;c++)if((r!==row||c!==col)&&board[r][c]===value)return false;return true}
function findEmpty(board){let best=null,bestOptions=null;for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++)if(!board[r][c]){const options=[];for(let n=1;n<=9;n++)if(canPlace(board,r,c,n))options.push(n);if(!options.length)return{row:r,col:c,options};if(!best||options.length<bestOptions.length){best={row:r,col:c};bestOptions=options;if(options.length===1)return{...best,options}}}return best?{...best,options:bestOptions}:null}
function solve(input){const board=clone(input);function fill(){const empty=findEmpty(board);if(!empty)return true;if(!empty.options.length)return false;for(const value of empty.options){board[empty.row][empty.col]=value;if(fill())return true;board[empty.row][empty.col]=0}return false}return fill()?board:null}
function countSolutions(input,limit=2){const board=clone(input);let count=0;function visit(){if(count>=limit)return;const empty=findEmpty(board);if(!empty){count++;return}if(!empty.options.length)return;for(const value of empty.options){board[empty.row][empty.col]=value;visit();board[empty.row][empty.col]=0;if(count>=limit)return}}visit();return count}
function isComplete(board){for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++)if(!board[r][c]||!canPlace(board,r,c,board[r][c]))return false;return true}
function shuffled(values,rng){const a=values.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function createSolution(rng=Math.random){const base=[1,2,3,4,5,6,7,8,9],rows=shuffled([0,1,2],rng).flatMap(b=>shuffled([0,1,2],rng).map(r=>b*3+r)),cols=shuffled([0,1,2],rng).flatMap(b=>shuffled([0,1,2],rng).map(c=>b*3+c)),nums=shuffled(base,rng);return rows.map(r=>cols.map(c=>nums[(r*3+Math.floor(r/3)+c)%9]))}
function generatePuzzle(difficulty='medium',rng=Math.random){const ranges={easy:[38,44],medium:[31,37],hard:[25,30]},range=ranges[difficulty]||ranges.medium;for(let attempt=0;attempt<8;attempt++){const solution=createSolution(rng),puzzle=clone(solution),target=range[0]+Math.floor(rng()*(range[1]-range[0]+1)),positions=shuffled(Array.from({length:81},(_,i)=>i),rng);for(const pos of positions){if(puzzle.flat().filter(Boolean).length<=target)break;const r=Math.floor(pos/9),c=pos%9,old=puzzle[r][c];puzzle[r][c]=0;if(countSolutions(puzzle,2)!==1)puzzle[r][c]=old}const clues=puzzle.flat().filter(Boolean).length;if(clues>=range[0]&&clues<=range[1])return{puzzle,solution,difficulty}}throw new Error('Unable to generate a unique puzzle')}
function candidates(board,row,col){if(board[row][col])return[];const list=[];for(let n=1;n<=9;n++)if(canPlace(board,row,col,n))list.push(n);return list}
return{canPlace,solve,countSolutions,isComplete,generatePuzzle,candidates,clone};});
