(() => {
'use strict';
const R=window.SolitaireRules,$=id=>document.getElementById(id),suitSymbol={clubs:'♣',diamonds:'♦',hearts:'♥',spades:'♠'},rankText={1:'A',11:'J',12:'Q',13:'K'};
const piles=Array.from({length:7},(_,i)=>$(`tableau${i}`)),foundations=Array.from({length:4},(_,i)=>$(`foundation${i}`));
let state,history=[],selected=null,startedAt=0,timer=null,wins=Number(localStorage.getItem('solitaire-wins')||0),best=Number(localStorage.getItem('solitaire-best')||0);
function cardText(card){return `${rankText[card.rank]||card.rank}${suitSymbol[card.suit]}`}
function cardNode(card,source,index,top=0){const el=document.createElement('button');el.type='button';el.className=`card${card.faceUp?'':' back'}${card.suit==='hearts'||card.suit==='diamonds'?' red':''}${selected&&selected.source===source&&selected.index===index?' selected':''}`;el.style.top=`${top}px`;el.dataset.source=source;el.dataset.index=String(index);el.setAttribute('aria-label',card.faceUp?cardText(card):'Face-down card');if(card.faceUp)el.innerHTML=`${rankText[card.rank]||card.rank}<span class="suit">${suitSymbol[card.suit]}</span>`;el.addEventListener('click',event=>handleCard(source,index,event.detail));return el;}
function spacing(pile,index){let y=0;for(let i=0;i<index;i++)y+=pile[i].faceUp?26:13;return y;}
function render(){piles.forEach((el,pileIndex)=>{el.replaceChildren();const pile=state.tableau[pileIndex];pile.forEach((card,index)=>el.appendChild(cardNode(card,`t${pileIndex}`,index,spacing(pile,index))));el.style.minHeight=`calc(var(--ch) + ${pile.length?spacing(pile,pile.length-1):0}px)`;});
 const stock=$('stock');stock.replaceChildren();stock.classList.toggle('has-cards',state.stock.length>0);if(!state.stock.length&&state.waste.length)stock.textContent='↻';
 const waste=$('waste');waste.replaceChildren();if(state.waste.length)waste.appendChild(cardNode(state.waste.at(-1),'w',state.waste.length-1));
 foundations.forEach((el,i)=>{const pile=state.foundations[i];el.querySelectorAll('.card').forEach(c=>c.remove());el.classList.toggle('filled',pile.length>0);if(pile.length)el.appendChild(cardNode(pile.at(-1),`f${i}`,pile.length-1));});
 $('moves').textContent=String(state.moves).padStart(3,'0');$('wins').textContent=wins;$('best').textContent=best?formatTime(best):'---';$('undoButton').disabled=!history.length;
 if(R.isComplete(state))win();}
function snapshot(){history.push(R.cloneState(state));if(history.length>100)history.shift()}
function changed(fn){const before=R.cloneState(state);if(fn()){history.push(before);selected=null;render();return true}return false}
function select(source,index){selected={source,index};render()}
function handleCard(source,index,detail){if(detail>1){if(source==='w')changed(()=>R.moveToFoundation(state,'w'));else if(source[0]==='t')changed(()=>R.moveToFoundation(state,Number(source.slice(1)),index));return;}
 if(selected){if(source[0]==='t'){const to=Number(source.slice(1));let ok=false;if(selected.source==='w')ok=changed(()=>R.moveWasteToTableau(state,to));else if(selected.source[0]==='t')ok=changed(()=>R.moveTableau(state,Number(selected.source.slice(1)),selected.index,to));else if(selected.source[0]==='f')ok=changed(()=>R.moveFoundationToTableau(state,Number(selected.source.slice(1)),to));if(ok)return;}selected=null;render();}
 const card=source==='w'?state.waste[index]:source[0]==='t'?state.tableau[Number(source.slice(1))][index]:state.foundations[Number(source.slice(1))][index];if(card&&card.faceUp)select(source,index);}
function start(){state=R.deal(R.shuffle(R.createDeck()));history=[];selected=null;startedAt=Date.now();$('resultOverlay').classList.remove('show');clearInterval(timer);timer=setInterval(updateTime,1000);updateTime();render()}
function updateTime(){if(startedAt)$('time').textContent=formatTime(Math.floor((Date.now()-startedAt)/1000))}
function formatTime(seconds){return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
function win(){if($('resultOverlay').classList.contains('show'))return;const elapsed=Math.floor((Date.now()-startedAt)/1000);wins++;if(!best||elapsed<best)best=elapsed;localStorage.setItem('solitaire-wins',wins);localStorage.setItem('solitaire-best',best);clearInterval(timer);$('wins').textContent=wins;$('best').textContent=formatTime(best);$('resultOverlay').classList.add('show')}
function undo(){if(!history.length)return;state=history.pop();selected=null;$('resultOverlay').classList.remove('show');render()}
function hint(){selected=null;for(let i=0;i<7;i++){const pile=state.tableau[i],card=pile.at(-1);if(card&&R.canPlaceOnFoundation(card,state.foundations[R.SUITS.indexOf(card.suit)].at(-1)||null)){select(`t${i}`,pile.length-1);return;}}const waste=state.waste.at(-1);if(waste){const fi=R.SUITS.indexOf(waste.suit);if(R.canPlaceOnFoundation(waste,state.foundations[fi].at(-1)||null)){select('w',state.waste.length-1);return;}for(let i=0;i<7;i++)if(R.canPlaceOnTableau(waste,state.tableau[i].at(-1)||null)){select('w',state.waste.length-1);return;}}$('stock').classList.add('selected');setTimeout(()=>$('stock').classList.remove('selected'),500)}
$('stock').addEventListener('click',()=>changed(()=>R.drawStock(state)));$('waste').addEventListener('click',()=>{if(state.waste.length)handleCard('w',state.waste.length-1,1)});foundations.forEach((el,i)=>el.addEventListener('click',event=>{if(event.target!==el)return;if(selected){let ok=false;if(selected.source==='w')ok=changed(()=>R.moveToFoundation(state,'w'));else if(selected.source[0]==='t')ok=changed(()=>R.moveToFoundation(state,Number(selected.source.slice(1)),selected.index));if(ok)return;}const pile=state.foundations[i];if(pile.length)select(`f${i}`,pile.length-1)}));piles.forEach((el,i)=>el.addEventListener('click',event=>{if(event.target!==el)return;if(selected){if(selected.source==='w')changed(()=>R.moveWasteToTableau(state,i));else if(selected.source[0]==='t')changed(()=>R.moveTableau(state,Number(selected.source.slice(1)),selected.index,i));else if(selected.source[0]==='f')changed(()=>R.moveFoundationToTableau(state,Number(selected.source.slice(1)),i));}}));
$('newButton').addEventListener('click',start);$('resultButton').addEventListener('click',start);$('undoButton').addEventListener('click',undo);$('hintButton').addEventListener('click',hint);document.addEventListener('keydown',event=>{if(event.key.toLowerCase()==='n')start();if(event.key.toLowerCase()==='u')undo()});
start();
})();
