(function(root,factory){const node=typeof module==='object'&&module.exports,api=factory(node?require('./rules.js'):root.BubbleFrontier.Rules,node?require('./content.js'):root.BubbleFrontier.Content);if(node)module.exports=api;else(root.BubbleFrontier||={}).Weapons=api;})(typeof globalThis!=='undefined'?globalThis:this,function(R,D){
 'use strict';
 const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
 function fire(state,room,gun,target,h){
  const p=state.player,m=R.mount(gun),angle=p.angle+(gun.angle||0),x=p.x+Math.cos(p.angle)*m.x-Math.sin(p.angle)*m.y,y=p.y+Math.sin(p.angle)*m.x+Math.cos(p.angle)*m.y,branch=p.branches?.[gun.id];
  const damage=R.baseDamage(gun);
  const emit=(offset=0,opts={})=>h.shot(state,room,x,y,angle+offset,{weapon:gun.id,mount:gun.slot,damage,...opts});
  if(gun.id==='twin'){for(let i=0;i<(branch?3:2);i++)emit(0,{delay:i*.12});return true;}
  if(gun.id==='needle'){emit(0,{delay:.25,speed:640,damage:damage,r:3,pierce:branch?2:1,ttl:1.1});h.effect(room,'playerAim',x,y,{angle,length:660,ttl:.25,duration:.25});return true;}
  if(gun.id==='pierce'){emit(0,{speed:500,damage:damage,r:branch?7:4,pierce:branch?5:3,delay:branch?.3:0,ttl:1.5});if(branch)h.effect(room,'playerAim',x,y,{angle,length:680,ttl:.3,duration:.3});return true;}
  if(gun.id==='stream'){p.heat||={};const heat=p.heat[gun.slot]||0;if(heat>=1){p.heat[gun.slot]=.3;state.cooldowns[gun.slot]=p.relics?.hot_chamber?1.4:.85;h.effect(room,'vent',x,y,{r:23});return true;}p.heat[gun.slot]=heat+.13;p.jetBeat=(p.jetBeat||0)+1;emit(branch?(p.jetBeat%2?.16:-.16):(state.rng()-.5)*.12,{damage:(damage)*(p.relics?.hot_chamber?1+heat*.65:1),r:3,speed:420,ttl:1.3});return true;}
  if(gun.id==='beam'){p.beamBeat=(p.beamBeat||0)+1;const a=angle+(branch?((p.beamBeat%3)-1)*.13:0),length=500;h.effect(room,'beam',x,y,{toX:x+Math.cos(a)*length,toY:y+Math.sin(a)*length,angle:a,ttl:.13,duration:.13});for(const e of room.enemies){const dx=e.x-x,dy=e.y-y,along=dx*Math.cos(a)+dy*Math.sin(a),side=Math.abs(dx*Math.sin(a)-dy*Math.cos(a));if(e.hp>0&&along>=0&&along<=length&&side<e.r+3)h.hurt(state,room,e,damage,{weapon:'beam',x,y});}return true;}
  if(gun.id==='missile'){for(const offset of branch?[-.18,.18]:[0])emit(offset,{tracking:true,targetId:target?.id,damage:(damage)*(branch?.7:1),speed:175,ttl:3,r:6});return true;}
  if(gun.id==='mine'){if(room.shots.filter(b=>b.weapon==='mine'&&b.mount===gun.slot&&b.ttl>0).length<4)emit(0,{vx:0,vy:0,r:8,arm:.4,ttl:9,mount:gun.slot,damage:damage,mist:!!branch});return true;}
  if(gun.id==='orbit'){if(room.shots.some(b=>b.weapon==='orbit'&&b.mount===gun.slot&&b.ttl>.2))return true;for(let i=0;i<3;i++)emit(0,{vx:0,vy:0,orbitPhase:i*Math.PI*2/3,mount:gun.slot,orbitRadius:49+R.tier(p.mass)*3+(p.relics?.flow_core?20:0),eccentric:!!branch,damage:damage,r:8,ttl:3+(p.relics?.flow_core?1:0),contactClock:0});return true;}
  if(gun.id==='vortex'){let center=target?{x:target.x,y:target.y}:{x:x+Math.cos(angle)*120,y:y+Math.sin(angle)*120};const mines=room.shots.filter(b=>b.weapon==='mine'&&b.ttl>0);if(mines.length)center=mines.sort((a,b)=>distance(a,center)-distance(b,center))[0];else if(R.activeLoadout(p).some(g=>g.id==='scatter'))center={x:center.x+(p.x-center.x)*.28,y:center.y+(p.y-center.y)*.28};const d=Math.hypot(center.x-400,center.y-400);if(d>270)center={x:400+(center.x-400)/d*270,y:400+(center.y-400)/d*270};h.shot(state,room,center.x,center.y,0,{weapon:'vortex',vx:0,vy:0,r:10,fieldRadius:110,pull:55*(p.relics?.gravity_sac?1.5:1),clock:0,damage:damage,ttl:2.5,pulse:!!branch});return true;}
  if(gun.id==='pulse'&&branch){emit(0,{bounces:1});return true;}
  if(gun.id==='scatter'&&branch){for(let i=0;i<5;i++)emit((i-2)*.16,{damage,r:4.5,speed:330,canSplit:true,generation:0});return true;}
  if(gun.id==='arc'&&branch){const hitIds=new Set();let at={x,y},next=target;for(let jump=0;next&&jump<3+(p.relics?.conductive_sea?1:0);jump++){if(distance(at,next)>(jump?115+(p.passives.conductive||0)*50:330))break;const hit=next;hitIds.add(hit.id);h.effect(room,'arc',at.x,at.y,{toX:hit.x,toY:hit.y,targetId:hit.id,ttl:.2,duration:.2});h.hurt(state,room,hit,damage*(1-jump*.15),{weapon:'arc',x:at.x,y:at.y});at=hit;if(jump===0){const side=room.enemies.find(e=>e.hp>0&&!hitIds.has(e.id)&&distance(e,hit)<130);if(side){hitIds.add(side.id);h.effect(room,'arc',hit.x,hit.y,{toX:side.x,toY:side.y,targetId:side.id,ttl:.2,duration:.2});h.hurt(state,room,side,(damage-2)*.6,{weapon:'arc',x:hit.x,y:hit.y});}}next=room.enemies.filter(e=>e.hp>0&&!hitIds.has(e.id)).sort((a,b)=>distance(a,at)-distance(b,at))[0];}return true;}
  // NEW WEAPON HANDLERS
  return false;
 }
 function updateShot(state,room,shot,dt,h){
  if(shot.tracking){const candidates=room.enemies.filter(e=>e.hp>0).sort((a,b)=>(b.mark||0)-(a.mark||0)||distance(a,shot)-distance(b,shot)),target=candidates.find(e=>e.id===shot.targetId&&(!candidates[0]?.mark||e.mark))||candidates[0];if(target){shot.targetId=target.id;const current=Math.atan2(shot.vy,shot.vx),desired=Math.atan2(target.y-shot.y,target.x-shot.x),delta=Math.atan2(Math.sin(desired-current),Math.cos(desired-current)),a=current+R.clamp(delta,-1.8*dt,1.8*dt);shot.vx=Math.cos(a)*175;shot.vy=Math.sin(a)*175;}}
  if(shot.weapon==='mine'){shot.arm=Math.max(0,(shot.arm||0)-dt);if(!shot.arm&&room.enemies.some(e=>e.hp>0&&distance(e,shot)<55+e.r)){for(const e of room.enemies)if(e.hp>0&&distance(e,shot)<82+e.r)h.hurt(state,room,e,shot.damage,{weapon:'mine',x:shot.x,y:shot.y});h.effect(room,'burst',shot.x,shot.y,{r:82});if(shot.mist)h.effect(room,'coldfield',shot.x,shot.y,{r:85,ttl:2,duration:2});shot.ttl=0;}return true;}
  if(shot.weapon==='orbit'){const p=state.player,a=state.time*2.4+shot.orbitPhase,r=shot.orbitRadius+(shot.eccentric?Math.sin(a*1.7)*12:0);shot.x=(shot.anchorX??p.x)+Math.cos(a)*r;shot.y=(shot.anchorY??p.y)+Math.sin(a)*r;shot.contactClock-=dt;if(shot.contactClock<=0){shot.hitIds=[];shot.contactClock+=.6;}for(const e of room.enemies)if(e.hp>0&&!shot.hitIds.includes(e.id)&&distance(e,shot)<e.r+shot.r){shot.hitIds.push(e.id);h.hurt(state,room,e,shot.damage,{weapon:'orbit',x:shot.x,y:shot.y});}for(const b of room.shots)if(b.owner==='enemy'&&b.ttl>0&&distance(b,shot)<b.r+shot.r){b.ttl=0;h.effect(room,'intercept',shot.x,shot.y,{r:14,ttl:.2,duration:.2});if(p.passives.shield&&state.time-(p.lastInterceptTime??-1)>=.5){p.shield=Math.min(p.passives.shield*10,p.shield+1);p.lastInterceptTime=state.time;}}return true;}
  if(shot.weapon==='vortex'){shot.clock-=dt;const damageTick=shot.clock<=0;if(damageTick)shot.clock+=.25;for(const e of room.enemies){const d=distance(e,shot);if(e.hp<=0||d>shot.fieldRadius||!d)continue;const move=Math.min(d,shot.pull*dt*(e.kind==='boss'?.1:1));e.x+=(shot.x-e.x)/d*move;e.y+=(shot.y-e.y)/d*move;if(damageTick)h.hurt(state,room,e,shot.damage,{weapon:'vortex',x:shot.x,y:shot.y});if(shot.pulse&&shot.ttl<=dt){e.x-=(shot.x-e.x)/d*12;e.y-=(shot.y-e.y)/d*12;}}if(shot.pulse&&shot.ttl<=dt)h.effect(room,'vortexPulse',shot.x,shot.y,{r:110});return true;}
  if(shot.weapon==='drone')return true;
  if(shot.weapon==='hostile_mine'){shot.arm=Math.max(0,shot.arm-dt);if(!shot.arm&&distance(shot,state.player)<45){h.hurtPlayer(state,room,shot.damage);h.effect(room,'enemyBlast',shot.x,shot.y,{r:45});shot.ttl=0;}return true;}
  // SPECIAL SHOT HANDLERS
  return false;
 }
 function reflectShot(shot){if(!shot.bounces)return;const dx=shot.x-400,dy=shot.y-400,d=Math.hypot(dx,dy);if(d<345-shot.r)return;const nx=dx/d,ny=dy/d,dot=shot.vx*nx+shot.vy*ny;if(dot<=0)return;shot.vx-=2*dot*nx;shot.vy-=2*dot*ny;shot.x=400+nx*(344-shot.r);shot.y=400+ny*(344-shot.r);shot.bounces--;shot.damage*=1+(shot.refractBonus||0);}
 return{fire,updateShot,reflectShot,distance};
});
