(() => {
  'use strict';

  const canvas = document.getElementById('game');
  const ctx = canvas.getContext('2d');
  const W = canvas.width, H = canvas.height, GROUND_Y = H - 32;
  const R = window.FlappyRules;
  const STORAGE_KEY = 'flappy-best-v1';
  const $ = id => document.getElementById(id);
  const ui = {scoreStat:$('scoreStat'),bestStat:$('bestStat'),overlay:$('overlay'),title:$('overlayTitle'),text:$('overlayText'),start:$('startButton'),pause:$('pauseButton')};
  let state='title',score=0,best=Number(localStorage.getItem(STORAGE_KEY)||0),bird=null,pipes=[],particles=[],lastTime=0,clock=0,spawnTimer=0;

  function css(name,fallback){const value=getComputedStyle(document.documentElement).getPropertyValue(name).trim();return value||fallback}
  function palette(){return{paper:css('--paper','#fffaf0'),grid:css('--grid','#b9dfe0'),ink:css('--ink','#3d3832'),muted:css('--muted','#8a7c6e'),mint:css('--mint','#9eddbd'),blue:css('--blue','#8fc9eb'),yellow:css('--yellow','#f7d66c'),coral:css('--coral','#f28c78'),purple:css('--purple','#b8a7e8')}}
  function spawnPipe(x){const gapHeight=140,minTop=65,maxTop=GROUND_Y-gapHeight-65,topY=minTop+Math.random()*(maxTop-minTop);pipes.push({x,width:52,topY,bottomY:topY+gapHeight,scored:false,seed:Math.random()*10})}
  function resetGame(){score=0;bird={x:90,y:260,vy:0,r:14,angle:0};pipes=[];particles=[];spawnTimer=0;spawnPipe(W+60);spawnPipe(W+280);updateHud()}
  function updateHud(){ui.scoreStat.textContent=String(score);ui.bestStat.textContent=String(best)}
  function flap(){if(state==='title'||state==='over'){resetGame();state='playing';ui.overlay.classList.add('hide');ui.pause.textContent='PAUSE';bird=R.flap(bird,-350);lastTime=performance.now();return}if(state!=='playing'||!bird)return;bird=R.flap(bird,-350);if(navigator.vibrate)navigator.vibrate(10)}
  function togglePause(){if(state==='playing'){state='paused';ui.title.textContent='PAUSED';ui.text.textContent=`CURRENT SCORE: ${score}`;ui.start.textContent='RESUME';ui.overlay.classList.remove('hide');ui.pause.textContent='RESUME'}else if(state==='paused'){state='playing';ui.overlay.classList.add('hide');ui.pause.textContent='PAUSE';lastTime=performance.now()}}
  function triggerExplosion(x,y){const p=palette();for(let i=0;i<25;i++){const angle=Math.random()*Math.PI*2,speed=50+Math.random()*180;particles.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,life:.7+Math.random()*.4,color:i%2?p.yellow:p.coral})}}
  function gameOver(){if(state!=='playing')return;state='over';if(score>best){best=score;localStorage.setItem(STORAGE_KEY,String(best))}updateHud();if(bird)triggerExplosion(bird.x,bird.y);bird=null;setTimeout(()=>{ui.title.textContent='MAIL DELAYED';ui.text.textContent=`SCORE ${score} · BEST ${best}`;ui.start.textContent='FLY AGAIN';ui.overlay.classList.remove('hide')},350);if(navigator.vibrate)navigator.vibrate([60,40,80])}
  function update(dt){if(bird){bird=R.updatePhysics(bird,dt,1050);bird.angle=bird.vy<-50?-.38:Math.min(1.2,bird.angle+dt*2.8);if(bird.y+bird.r>=GROUND_Y||bird.y-bird.r<=0){gameOver();return}for(const pipe of pipes){if(R.checkPipeCollision(bird,pipe)){gameOver();return}if(!pipe.scored&&pipe.x+pipe.width<bird.x){pipe.scored=true;score++;if(score>best)best=score;updateHud();if(navigator.vibrate)navigator.vibrate(20)}}}for(const pipe of pipes)pipe.x-=135*dt;const lastPipe=pipes[pipes.length-1];if(lastPipe&&lastPipe.x<W-210)spawnPipe(W+20);pipes=pipes.filter(pipe=>pipe.x+pipe.width>-20);for(const part of particles){part.x+=part.vx*dt;part.y+=part.vy*dt;part.vy+=300*dt;part.life-=dt}particles=particles.filter(part=>part.life>0)}
  function drawGrid(p){ctx.fillStyle=p.paper;ctx.fillRect(0,0,W,H);ctx.strokeStyle=p.grid;ctx.globalAlpha=.46;ctx.lineWidth=1;const offset=(clock*.012)%28;for(let x=0;x<=W;x+=28){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=-28+offset;y<H+28;y+=28){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.globalAlpha=1}
  function drawCloud(x,y,s,p,fill){ctx.save();ctx.translate(x,y);ctx.strokeStyle=p.ink;ctx.lineWidth=2.5;ctx.lineCap='round';ctx.fillStyle=fill||p.paper;ctx.beginPath();ctx.moveTo(-30*s,8*s);ctx.bezierCurveTo(-38*s,-4*s,-28*s,-16*s,-16*s,-12*s);ctx.bezierCurveTo(-12*s,-29*s,8*s,-29*s,14*s,-13*s);ctx.bezierCurveTo(29*s,-19*s,40*s,-5*s,31*s,9*s);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}
  function drawBackground(p){drawGrid(p);drawCloud(64,93,.75,p,p.paper);drawCloud(342,190,.5,p,p.paper);drawCloud(270,450,.6,p,p.paper);ctx.save();ctx.strokeStyle=p.coral;ctx.lineWidth=2;ctx.lineCap='round';for(let i=0;i<6;i++){const x=24+i*72,y=((i*97+clock*.018)%GROUND_Y);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+6,y-7);ctx.lineTo(x+13,y);ctx.stroke()}ctx.restore();ctx.fillStyle=p.mint;ctx.fillRect(0,GROUND_Y,W,H-GROUND_Y);ctx.strokeStyle=p.ink;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,GROUND_Y);ctx.lineTo(W,GROUND_Y);ctx.stroke();for(let x=10;x<W;x+=26){ctx.strokeStyle=p.blue;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,GROUND_Y+8);ctx.lineTo(x+5,GROUND_Y+2);ctx.lineTo(x+10,GROUND_Y+8);ctx.stroke()}}
  function cloudPillar(x,y,h,p,top){ctx.save();ctx.fillStyle=p.blue;ctx.strokeStyle=p.ink;ctx.lineWidth=2.5;ctx.globalAlpha=.93;ctx.fillRect(x+7,y,38,h);ctx.strokeRect(x+7,y,38,h);const capY=top?y+h-8:y;drawCloud(x+26,capY,0.52,p,p.blue);ctx.restore()}
  function drawPipes(p){for(const pipe of pipes){cloudPillar(pipe.x,0,pipe.topY,p,true);cloudPillar(pipe.x,pipe.bottomY,GROUND_Y-pipe.bottomY,p,false);ctx.save();ctx.strokeStyle=p.coral;ctx.lineWidth=2;ctx.setLineDash([4,5]);ctx.beginPath();ctx.moveTo(pipe.x+26,pipe.topY+22);ctx.lineTo(pipe.x+26,pipe.bottomY-22);ctx.stroke();ctx.setLineDash([]);ctx.restore()}}
  function drawBird(p){if(!bird)return;ctx.save();ctx.translate(bird.x,bird.y);ctx.rotate(bird.angle);ctx.strokeStyle=p.ink;ctx.lineWidth=2.5;ctx.lineJoin='round';ctx.fillStyle=p.yellow;ctx.beginPath();ctx.ellipse(0,0,16,14,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=p.mint;ctx.beginPath();ctx.ellipse(-5,5,10,6,.2,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=p.coral;ctx.strokeStyle=p.ink;ctx.beginPath();ctx.moveTo(10,-1);ctx.lineTo(20,3);ctx.lineTo(10,7);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle=p.paper;ctx.beginPath();ctx.arc(5,-6,5,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=p.ink;ctx.beginPath();ctx.arc(6,-6,2,0,Math.PI*2);ctx.fill();ctx.strokeStyle=p.coral;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-14,-10);ctx.quadraticCurveTo(0,-22,14,-10);ctx.stroke();ctx.strokeStyle=p.ink;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-4,-14);ctx.lineTo(-1,-22);ctx.lineTo(5,-19);ctx.stroke();ctx.restore()}
  function draw(){const p=palette();drawBackground(p);drawPipes(p);for(const part of particles){ctx.save();ctx.globalAlpha=Math.max(0,part.life);ctx.fillStyle=part.color;ctx.beginPath();ctx.arc(part.x,part.y,3,0,Math.PI*2);ctx.fill();ctx.restore()}drawBird(p);if(state==='paused'){ctx.fillStyle=p.paper+'bb';ctx.fillRect(0,0,W,H)}}
  function loop(time){const dt=Math.min(.04,(time-lastTime)/1000||0);lastTime=time;clock=time;if(state==='playing')update(dt);draw();requestAnimationFrame(loop)}
  canvas.addEventListener('pointerdown',event=>{event.preventDefault();flap()});window.addEventListener('keydown',event=>{if(['Space','ArrowUp','KeyW'].includes(event.code)){event.preventDefault();flap()}else if(['KeyP','Escape'].includes(event.code)){event.preventDefault();togglePause()}});ui.start.addEventListener('click',flap);ui.pause.addEventListener('click',togglePause);document.addEventListener('themechange',draw);
  resetGame();updateHud();requestAnimationFrame(loop);
  window.FlappyGame={flap,getSnapshot:()=>({state,score,best,hasBird:Boolean(bird)})};
})();
